/* Skills, project catalog, career roles, English vocabulary and freelance simulations. */

export const SKILLS: { key: string; title: string; category: string; kind: "discipline" | "tool"; description: string }[] = [
  { key: "python", title: "Python", category: "programming", kind: "tool", description: "Idiomatic, testable Python across data and services." },
  { key: "programming-fundamentals", title: "Programming Fundamentals", category: "programming", kind: "discipline", description: "Values, control flow, abstraction, tracing and reasoning about code." },
  { key: "data-structures", title: "Data Structures", category: "cs", kind: "discipline", description: "Choosing and implementing structures by access pattern and cost." },
  { key: "algorithms", title: "Algorithms", category: "cs", kind: "discipline", description: "Greedy, divide and conquer, dynamic programming, graph algorithms." },
  { key: "complexity-analysis", title: "Complexity Analysis", category: "cs", kind: "discipline", description: "Asymptotic reasoning about time and space." },
  { key: "problem-solving", title: "Problem Solving", category: "cs", kind: "discipline", description: "Decomposition, strategy selection and verification." },
  { key: "oop", title: "Object-Oriented Design", category: "programming", kind: "discipline", description: "Encapsulation, abstraction, inheritance vs composition." },
  { key: "debugging", title: "Debugging", category: "engineering", kind: "discipline", description: "Hypothesis-driven diagnosis of broken systems." },
  { key: "c-programming", title: "C and Memory Model", category: "cs", kind: "tool", description: "Pointers, stack/heap, compilation and the machine model." },
  { key: "systems", title: "Systems", category: "cs", kind: "discipline", description: "Memory hierarchy, processes, threads, concurrency, OS concepts." },
  { key: "performance", title: "Performance Engineering", category: "engineering", kind: "discipline", description: "Measuring and removing bottlenecks rather than guessing." },
  { key: "mathematics", title: "Mathematical Reasoning", category: "mathematics", kind: "discipline", description: "Derivation, proof habits and symbolic fluency." },
  { key: "linear-algebra", title: "Linear Algebra", category: "mathematics", kind: "discipline", description: "Vectors, matrices, eigenstructure, projections." },
  { key: "calculus", title: "Calculus", category: "mathematics", kind: "discipline", description: "Derivatives, partials, gradients, chain rule." },
  { key: "optimization", title: "Optimization", category: "mathematics", kind: "discipline", description: "Gradient methods, convexity, conditioning." },
  { key: "probability", title: "Probability", category: "statistics", kind: "discipline", description: "Random variables, conditioning, expectation, likelihood." },
  { key: "statistics", title: "Statistics", category: "statistics", kind: "discipline", description: "Estimation, inference, uncertainty, experimental design." },
  { key: "experimentation", title: "Experimentation / A·B Testing", category: "statistics", kind: "discipline", description: "Designing and interpreting controlled experiments." },
  { key: "numpy", title: "NumPy", category: "data", kind: "tool", description: "Vectorized numerical computing." },
  { key: "pandas", title: "Pandas", category: "data", kind: "tool", description: "Tabular wrangling, joins, grouping, reshaping." },
  { key: "data-analysis", title: "Data Analysis", category: "data", kind: "discipline", description: "End-to-end exploratory analysis with defensible conclusions." },
  { key: "visualization", title: "Data Visualization", category: "data", kind: "discipline", description: "Encoding choice, honesty and narrative." },
  { key: "data-quality", title: "Data Quality", category: "data", kind: "discipline", description: "Validation, missingness, leakage and provenance." },
  { key: "feature-engineering", title: "Feature Engineering", category: "data", kind: "discipline", description: "Constructing predictive, leakage-free representations." },
  { key: "excel", title: "Excel", category: "business", kind: "tool", description: "Spreadsheet modelling and stakeholder deliverables." },
  { key: "power-bi", title: "Power BI", category: "business", kind: "tool", description: "Semantic modelling, DAX and dashboards." },
  { key: "sql", title: "SQL", category: "data", kind: "tool", description: "Querying, window functions, optimization." },
  { key: "databases", title: "Database Systems", category: "data", kind: "discipline", description: "Indexing, transactions, isolation, distribution." },
  { key: "data-modeling", title: "Data Modeling", category: "data", kind: "discipline", description: "Normalization, star schemas, contracts." },
  { key: "data-acquisition", title: "Data Acquisition", category: "data", kind: "discipline", description: "APIs, scraping, legality, provenance recording." },
  { key: "data-engineering", title: "Data Engineering", category: "data", kind: "discipline", description: "Pipelines, idempotency, orchestration, quality gates." },
  { key: "spark", title: "Spark", category: "data", kind: "tool", description: "Distributed processing, shuffle and partitioning." },
  { key: "airflow", title: "Airflow / Orchestration", category: "data", kind: "tool", description: "DAGs, retries, backfills, lineage." },
  { key: "machine-learning", title: "Machine Learning", category: "ai", kind: "discipline", description: "Supervised and unsupervised modelling with honest evaluation." },
  { key: "scikit-learn", title: "scikit-learn", category: "ai", kind: "tool", description: "Pipelines, estimators, model selection." },
  { key: "model-evaluation", title: "Model Evaluation", category: "ai", kind: "discipline", description: "Metric selection, calibration, subgroup and failure analysis." },
  { key: "deep-learning", title: "Deep Learning", category: "ai", kind: "discipline", description: "Architectures, training dynamics, experimentation." },
  { key: "tensorflow", title: "TensorFlow / Keras", category: "ai", kind: "tool", description: "Building and training neural networks." },
  { key: "experiment-tracking", title: "Experiment Tracking", category: "ai", kind: "discipline", description: "Reproducible experiment metadata and comparison." },
  { key: "computer-vision", title: "Computer Vision", category: "ai", kind: "discipline", description: "CNNs, transfer learning, detection and segmentation." },
  { key: "time-series", title: "Time Series", category: "ai", kind: "discipline", description: "Sequence modelling and leakage-free temporal validation." },
  { key: "nlp", title: "Natural Language Processing", category: "ai", kind: "discipline", description: "Text representation, modelling and evaluation." },
  { key: "llm", title: "Large Language Models", category: "ai", kind: "discipline", description: "Transformers, inference, fine-tuning, evaluation." },
  { key: "prompt-engineering", title: "Prompt Engineering", category: "ai", kind: "tool", description: "Structured prompting with measurable outcomes." },
  { key: "rag", title: "Retrieval-Augmented Generation", category: "ai", kind: "discipline", description: "Retrieval design, grounding, citation, evaluation." },
  { key: "vector-search", title: "Vector Search", category: "ai", kind: "tool", description: "Embeddings, ANN indexes, hybrid retrieval." },
  { key: "agents", title: "Agent Engineering", category: "ai", kind: "discipline", description: "Tool use, orchestration, permissions, trajectory evaluation." },
  { key: "responsible-ai", title: "Responsible AI", category: "governance", kind: "discipline", description: "Fairness, privacy, provenance, documented limitations." },
  { key: "security", title: "Application and AI Security", category: "governance", kind: "discipline", description: "Authorization, injection, untrusted content, auditability." },
  { key: "software-engineering", title: "Software Engineering", category: "engineering", kind: "discipline", description: "Design, review, maintainability, release engineering." },
  { key: "testing", title: "Testing", category: "engineering", kind: "discipline", description: "Unit, integration, E2E and ML-specific tests." },
  { key: "git", title: "Git and Code Review", category: "engineering", kind: "tool", description: "Branching, atomic commits, reviewable pull requests." },
  { key: "system-design", title: "System Design", category: "engineering", kind: "discipline", description: "Components, interfaces, failure modes, scaling, cost." },
  { key: "fastapi", title: "FastAPI", category: "engineering", kind: "tool", description: "Typed, validated HTTP services." },
  { key: "docker", title: "Docker", category: "engineering", kind: "tool", description: "Containerization and reproducible runtimes." },
  { key: "deployment", title: "Deployment", category: "engineering", kind: "discipline", description: "Release, rollout, rollback and operability." },
  { key: "cloud", title: "Cloud Engineering", category: "cloud", kind: "discipline", description: "Identity, storage, compute, networking, cost." },
  { key: "aws", title: "AWS", category: "cloud", kind: "tool", description: "IAM, S3, Lambda, API Gateway, ECS, CloudWatch." },
  { key: "azure", title: "Azure", category: "cloud", kind: "tool", description: "Entra ID, storage, functions, AI services, monitoring." },
  { key: "terraform", title: "Infrastructure as Code", category: "cloud", kind: "tool", description: "Declarative, reviewable infrastructure." },
  { key: "mlops", title: "MLOps", category: "ai", kind: "discipline", description: "Lifecycle from data validation to retraining and rollback." },
  { key: "monitoring", title: "Monitoring and Observability", category: "engineering", kind: "discipline", description: "Signals, thresholds, ownership and actionable alerts." },
  { key: "typescript", title: "TypeScript", category: "programming", kind: "tool", description: "Typed application and AI-surface development." },
  { key: "bash", title: "Bash / Shell", category: "programming", kind: "tool", description: "Reliable automation and system interaction." },
  { key: "r-lang", title: "R", category: "statistics", kind: "tool", description: "Applied statistics and statistical modelling." },
  { key: "sas", title: "SAS", category: "statistics", kind: "tool", description: "Role-triggered familiarity for regulated analytics environments." },
  { key: "java", title: "Java", category: "programming", kind: "tool", description: "Role-triggered familiarity for enterprise services." },
  { key: "graph-databases", title: "Graph Databases / GraphRAG", category: "data", kind: "tool", description: "Entity-relationship retrieval for multi-hop questions." },
  { key: "research", title: "Research Engineering", category: "research", kind: "discipline", description: "Reading, reproduction, ablation and scientific writing." },
  { key: "research-literacy", title: "Source and Research Literacy", category: "research", kind: "discipline", description: "Verifying claims against primary sources." },
  { key: "technical-english", title: "Technical English", category: "communication", kind: "discipline", description: "Professional reading, writing, speaking and interaction." },
  { key: "communication", title: "Technical Communication", category: "communication", kind: "discipline", description: "Explaining decisions, trade-offs and risk to any audience." },
  { key: "career", title: "Career Engineering", category: "career", kind: "discipline", description: "Requirement analysis, evidence building, interview performance." },
  { key: "freelancing", title: "Freelance Practice", category: "career", kind: "discipline", description: "Discovery, scoping, proposals, delivery, maintenance." },
];

type ProjectSpec = {
  key: string;
  title: string;
  ladderLevel: number;
  sourceCategory: string;
  brief: string;
  dataPolicy: string;
  suggestedData: { name: string; url: string; note: string }[];
  milestones: string[];
  definitionOfDone: string[];
  skillKeys: string[];
  evidenceClass: string;
};

const DOD_BASE = [
  "Requirements and acceptance criteria written before implementation",
  "Data provenance recorded: source, licence/terms, retrieval date, schema, known limitations",
  "Reproducible environment (pinned dependencies) and a README a stranger can follow",
  "Tests pass and edge cases are considered",
  "Evaluation is valid and leakage was explicitly checked",
  "Failure analysis performed, including worst-performing subgroup where applicable",
  "Limitations documented honestly",
  "Evidence captured in the platform (repository link and at least one artifact)",
];

const dataNote = "Public source listed for convenience. Verify the current licence and terms before use, and record the retrieval date.";

export const PROJECTS: ProjectSpec[] = [
  {
    key: "p-library-management",
    title: "Library Management System",
    ladderLevel: 1,
    sourceCategory: "Original Curriculum",
    brief:
      "Build a Python application that models books, members, loans and returns, with persistence, validation and a test suite. Exercise OOP, error handling and file/database I/O on a domain with real invariants (a book cannot be loaned twice).",
    dataPolicy: "No external dataset required. Any seed data must be clearly labelled as sample data, never as real users.",
    suggestedData: [],
    milestones: ["Domain model and invariants", "Persistence layer", "CLI or API surface", "Test suite", "README and demo"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["python", "oop", "testing", "software-engineering"],
    evidenceClass: "Technical Artifact",
  },
  {
    key: "p-uber-analysis",
    title: "Uber Data Analysis",
    ladderLevel: 2,
    sourceCategory: "Original Curriculum",
    brief:
      "Exploratory analysis of trip data: temporal demand patterns, geography, outliers and data-quality issues. Deliver findings with uncertainty stated, not just charts.",
    dataPolicy: "Use a real public trip dataset. Record source, licence, retrieval date and schema. Do not fabricate rows.",
    suggestedData: [{ name: "NYC TLC Trip Record Data", url: "https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page", note: dataNote }],
    milestones: ["Acquire and validate data", "Cleaning log", "Univariate and bivariate analysis", "Findings with caveats", "Reproducible notebook"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["pandas", "data-analysis", "visualization", "data-quality"],
    evidenceClass: "Portfolio Project",
  },
  {
    key: "p-superstore-dashboard",
    title: "Superstore Data Analysis Dashboard",
    ladderLevel: 2,
    sourceCategory: "Original Curriculum",
    brief:
      "Build a stakeholder dashboard over retail sales data with a documented semantic model, business-named measures and a data-freshness indicator.",
    dataPolicy: "Use a real public retail dataset; document licence and retrieval date.",
    suggestedData: [{ name: "Public retail/sales datasets (Kaggle Datasets search)", url: "https://www.kaggle.com/datasets", note: dataNote }],
    milestones: ["Star schema", "Measures", "Dashboard layout", "Stakeholder walkthrough"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["power-bi", "data-modeling", "visualization", "communication"],
    evidenceClass: "Portfolio Project",
  },
  {
    key: "p-hr-dashboard",
    title: "HR Dashboard",
    ladderLevel: 2,
    sourceCategory: "Original Curriculum",
    brief:
      "Headcount, attrition and tenure analytics with explicit privacy handling and a written note on which HR metrics can mislead.",
    dataPolicy: "Use a public HR analytics dataset. Never use real personal data without lawful basis and consent.",
    suggestedData: [{ name: "Open HR analytics datasets (Kaggle Datasets search)", url: "https://www.kaggle.com/datasets", note: dataNote }],
    milestones: ["Metric definitions", "Privacy review", "Dashboard", "Misinterpretation note"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["power-bi", "data-analysis", "responsible-ai", "communication"],
    evidenceClass: "Portfolio Project",
  },
  {
    key: "p-bank-loan-analysis",
    title: "Bank Loan Data Analysis",
    ladderLevel: 3,
    sourceCategory: "Original Curriculum",
    brief:
      "Analyse lending data for approval patterns, default drivers and potential disparate impact. Include a fairness section, not an afterthought.",
    dataPolicy: "Use a public lending dataset with a documented licence; treat protected attributes carefully.",
    suggestedData: [{ name: "UCI Machine Learning Repository (credit datasets)", url: "https://archive.ics.uci.edu/", note: dataNote }],
    milestones: ["EDA", "Segment analysis", "Fairness analysis", "Report"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["data-analysis", "statistics", "responsible-ai"],
    evidenceClass: "Portfolio Project",
  },
  {
    key: "p-sales-database",
    title: "Sales Database",
    ladderLevel: 3,
    sourceCategory: "Original Curriculum",
    brief:
      "Design a normalized schema, load real data, write analytical SQL with window functions, and optimise two slow queries with before/after plans.",
    dataPolicy: "Public sales data or a documented generated-for-teaching dataset clearly labelled as synthetic.",
    suggestedData: [{ name: "Data.gov open datasets", url: "https://data.gov/", note: dataNote }],
    milestones: ["ERD", "DDL and constraints", "Load pipeline", "Analytical queries", "Optimization report"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["sql", "data-modeling", "databases", "performance"],
    evidenceClass: "Technical Artifact",
  },
  {
    key: "p-etl-pipeline",
    title: "End-to-End ETL Pipeline (Scrape → Clean → Store → Query)",
    ladderLevel: 3,
    sourceCategory: "Original Curriculum",
    brief:
      "Acquire data from a public API or a permitted source, validate it, load it idempotently, and expose analytical queries. Add quality gates that fail the run.",
    dataPolicy: "Check terms of service and robots.txt; prefer official APIs; throttle; store retrieval timestamps.",
    suggestedData: [{ name: "Public APIs directory", url: "https://github.com/public-apis/public-apis", note: dataNote }],
    milestones: ["Source assessment and legality check", "Ingestion", "Quality gates", "Idempotent load", "Query layer"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["data-engineering", "python", "sql", "data-quality"],
    evidenceClass: "Portfolio Project",
  },
  {
    key: "p-titanic",
    title: "Titanic Prediction",
    ladderLevel: 4,
    sourceCategory: "Original Curriculum",
    brief:
      "A teaching classification problem used deliberately for pipeline discipline: baseline first, leakage-free preprocessing, honest cross-validation, calibration.",
    dataPolicy: "Public competition dataset. Treat it as a learning artifact, not as portfolio-grade evidence of applied impact.",
    suggestedData: [{ name: "Kaggle — Titanic", url: "https://www.kaggle.com/competitions/titanic", note: dataNote }],
    milestones: ["Baseline", "Pipeline", "Model comparison", "Calibration and error analysis"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["machine-learning", "scikit-learn", "model-evaluation"],
    evidenceClass: "Skill Evidence",
  },
  {
    key: "p-house-pricing",
    title: "House Pricing Prediction",
    ladderLevel: 4,
    sourceCategory: "Original Curriculum",
    brief:
      "Regression with real estate data: feature engineering, residual diagnostics, metric selection and an interpretable baseline comparison.",
    dataPolicy: "Public housing dataset with documented licence; note geographic and temporal scope limitations.",
    suggestedData: [{ name: "Kaggle — House Prices", url: "https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques", note: dataNote }],
    milestones: ["EDA", "Baseline regression", "Feature engineering", "Residual analysis", "Report"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["machine-learning", "statistics", "feature-engineering", "model-evaluation"],
    evidenceClass: "Skill Evidence",
  },
  {
    key: "p-credit-card-fraud",
    title: "Credit Card Fraud Detection",
    ladderLevel: 4,
    sourceCategory: "Original Curriculum",
    brief:
      "Severe class imbalance: PR-AUC over ROC-AUC, threshold selection by cost, resampling inside folds, and a written cost analysis of false positives vs false negatives.",
    dataPolicy: "Public anonymised transaction dataset; document the anonymisation and its effect on interpretability.",
    suggestedData: [{ name: "Kaggle — Credit Card Fraud Detection", url: "https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud", note: dataNote }],
    milestones: ["Imbalance strategy", "Metric choice", "Threshold and cost analysis", "Failure analysis"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["machine-learning", "model-evaluation", "responsible-ai"],
    evidenceClass: "Portfolio Project",
  },
  {
    key: "p-stock-prediction",
    title: "Stock Market Prediction",
    ladderLevel: 5,
    sourceCategory: "Original Curriculum",
    brief:
      "A deliberately humbling time-series project. Walk-forward validation, naive baselines, transaction-cost realism, and an honest conclusion — which is frequently 'this does not beat the baseline'.",
    dataPolicy: "Real market data via a public API. Never present backtest results as investment advice or as realised returns.",
    suggestedData: [{ name: "Public market data APIs (verify terms)", url: "https://github.com/public-apis/public-apis#finance", note: dataNote }],
    milestones: ["Problem framing", "Baselines", "Walk-forward validation", "Honest conclusion"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["time-series", "machine-learning", "model-evaluation"],
    evidenceClass: "Skill Evidence",
  },
  {
    key: "p-breast-cancer",
    title: "Breast Cancer Detection",
    ladderLevel: 5,
    sourceCategory: "Original Curriculum",
    brief:
      "Clinical-context classification where false negatives dominate the cost function. Includes calibration, subgroup evaluation and an explicit statement that this is an educational artifact, not a medical device.",
    dataPolicy: "Public, de-identified clinical dataset. Never claim clinical validity or deployment readiness.",
    suggestedData: [{ name: "UCI — Breast Cancer Wisconsin (Diagnostic)", url: "https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic", note: dataNote }],
    milestones: ["Cost analysis", "Model and calibration", "Subgroup evaluation", "Model card with limitations"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["machine-learning", "model-evaluation", "responsible-ai"],
    evidenceClass: "Portfolio Project",
  },
  {
    key: "p-skin-disease",
    title: "Skin Disease Prediction",
    ladderLevel: 6,
    sourceCategory: "Original Curriculum",
    brief:
      "Image classification with transfer learning. Must include a skin-tone representation analysis of the training data and a limitations section — dermatology datasets are well known for imbalanced representation.",
    dataPolicy: "Public dermatology image dataset with an explicit research licence. Educational artifact only, not a diagnostic tool.",
    suggestedData: [{ name: "ISIC Archive", url: "https://www.isic-archive.com/", note: dataNote }],
    milestones: ["Dataset audit", "Transfer learning", "Subgroup evaluation", "Model card"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["computer-vision", "deep-learning", "responsible-ai"],
    evidenceClass: "Portfolio Project",
  },
  {
    key: "p-brain-tumor",
    title: "Brain Tumor Detection",
    ladderLevel: 6,
    sourceCategory: "Original Curriculum",
    brief:
      "Medical imaging classification/segmentation with careful patient-level splitting (GroupKFold) — slice-level splitting leaks and produces fictional accuracy.",
    dataPolicy: "Public de-identified imaging dataset with documented licence. Educational artifact only.",
    suggestedData: [{ name: "The Cancer Imaging Archive", url: "https://www.cancerimagingarchive.net/", note: dataNote }],
    milestones: ["Patient-level split design", "Model", "Evaluation", "Limitations"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["computer-vision", "deep-learning", "model-evaluation"],
    evidenceClass: "Portfolio Project",
  },
  {
    key: "p-face-recognition",
    title: "Face Recognition / Detection / Verification",
    ladderLevel: 6,
    sourceCategory: "Original Curriculum",
    brief:
      "Detection, embedding and verification pipeline, plus a mandatory written analysis of consent, demographic performance differences and lawful use.",
    dataPolicy: "Use only datasets with explicit permission for research use. Do not collect images of people without informed consent.",
    suggestedData: [{ name: "Public face datasets (verify licence and consent terms individually)", url: "https://paperswithcode.com/datasets?task=face-recognition", note: dataNote }],
    milestones: ["Detection", "Embedding and verification", "Threshold analysis", "Ethics and consent analysis"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["computer-vision", "deep-learning", "responsible-ai", "security"],
    evidenceClass: "Portfolio Project",
  },
  {
    key: "p-realtime-object-detection",
    title: "Real-time Object Detection",
    ladderLevel: 6,
    sourceCategory: "Original Curriculum",
    brief:
      "Deploy a detection model under a latency budget. Report mAP *and* p95 latency on specified hardware; apply at least one optimization and measure its effect.",
    dataPolicy: "Public detection dataset; record licence. Any live camera demo must respect local privacy law.",
    suggestedData: [{ name: "COCO Dataset", url: "https://cocodataset.org/", note: dataNote }],
    milestones: ["Baseline inference", "Latency measurement", "Optimization", "Demo"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["computer-vision", "performance", "deployment"],
    evidenceClass: "Portfolio Project",
  },
  {
    key: "p-sign-language",
    title: "Sign Language Classifier",
    ladderLevel: 6,
    sourceCategory: "Original Curriculum",
    brief:
      "Gesture classification with careful attention to signer-independent evaluation: splitting by signer, not by frame, is the difference between a real result and a fake one.",
    dataPolicy: "Public sign-language dataset with documented licence and consent.",
    suggestedData: [{ name: "Public sign language datasets (verify licence)", url: "https://paperswithcode.com/datasets?q=sign+language", note: dataNote }],
    milestones: ["Signer-independent split", "Model", "Confusion analysis", "Report"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["computer-vision", "deep-learning", "model-evaluation"],
    evidenceClass: "Portfolio Project",
  },
  {
    key: "p-gan-image-generation",
    title: "Image Generation using GANs",
    ladderLevel: 6,
    sourceCategory: "Original Curriculum",
    brief:
      "Train a generative model and confront evaluation honestly: FID/IS limitations, mode collapse diagnosis, training instability, and a statement on synthetic-media responsibility.",
    dataPolicy: "Public image dataset with a licence permitting generative training. Generated outputs must be labelled as synthetic.",
    suggestedData: [{ name: "Public image datasets (verify licence)", url: "https://paperswithcode.com/datasets?mod=images", note: dataNote }],
    milestones: ["Training loop", "Stability diagnosis", "Evaluation", "Responsibility statement"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["deep-learning", "computer-vision", "responsible-ai"],
    evidenceClass: "Portfolio Project",
  },
  {
    key: "p-text-classification",
    title: "Text Classification",
    ladderLevel: 6,
    sourceCategory: "Original Curriculum",
    brief:
      "Compare a TF-IDF + linear baseline against a fine-tuned transformer on the same split, and report the cost/latency/accuracy trade-off — the baseline often wins on value.",
    dataPolicy: "Public text dataset with documented licence; check for personal data.",
    suggestedData: [{ name: "Hugging Face Datasets", url: "https://huggingface.co/datasets", note: dataNote }],
    milestones: ["Baseline", "Transformer fine-tune", "Trade-off table", "Error analysis"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["nlp", "machine-learning", "model-evaluation"],
    evidenceClass: "Portfolio Project",
  },
  {
    key: "p-document-summarization",
    title: "Document Summarization",
    ladderLevel: 7,
    sourceCategory: "Original Curriculum",
    brief:
      "Summarization with a real evaluation design: ROUGE is weak, so add faithfulness checking against the source and a human-rated sample with documented criteria.",
    dataPolicy: "Public documents with redistribution-permitting licences; never summarise confidential material in a public artifact.",
    suggestedData: [{ name: "Hugging Face Datasets — summarization", url: "https://huggingface.co/datasets?task_categories=task_categories:summarization", note: dataNote }],
    milestones: ["Pipeline", "Faithfulness evaluation", "Human-rated sample", "Report"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["nlp", "llm", "model-evaluation"],
    evidenceClass: "Portfolio Project",
  },
  {
    key: "p-chatbot",
    title: "Chatbot",
    ladderLevel: 7,
    sourceCategory: "Original Curriculum",
    brief:
      "A scoped assistant with defined in-scope and out-of-scope behaviour, a refusal policy, conversation state, an evaluation set and logging — not a demo wrapper around an API key.",
    dataPolicy: "Any knowledge source must be licensed for the use. Do not log user content without a stated retention policy.",
    suggestedData: [],
    milestones: ["Scope and refusal policy", "Implementation", "Evaluation set", "Logging and cost tracking"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["llm", "prompt-engineering", "software-engineering", "security"],
    evidenceClass: "Portfolio Project",
  },
  {
    key: "p-rag-system",
    title: "RAG System",
    ladderLevel: 7,
    sourceCategory: "Original Curriculum",
    brief:
      "A production-shaped retrieval system: chunking strategy, hybrid search, reranking, citation enforcement, permission-aware retrieval, and separate retrieval/generation evaluation.",
    dataPolicy: "Corpus must be lawfully usable. Store source, licence and permissions metadata on every chunk.",
    suggestedData: [{ name: "Open documentation corpora or your own licensed documents", url: "https://huggingface.co/datasets", note: dataNote }],
    milestones: ["Corpus and provenance", "Retrieval evaluation set", "Hybrid retrieval + rerank", "Grounded generation with citations", "Evaluation report"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["rag", "llm", "vector-search", "model-evaluation", "security"],
    evidenceClass: "Signature Project",
  },
  {
    key: "p-agentic-system",
    title: "Agentic Workflow System",
    ladderLevel: 8,
    sourceCategory: "Industry Extension",
    brief:
      "An agent that uses tools to complete a bounded real task, with an architecture decision record justifying why a deterministic workflow was insufficient, permission scoping, budget caps and trajectory evaluation.",
    dataPolicy: "Tools must act only within the user's own permissions. Log every tool call with a run id.",
    suggestedData: [],
    milestones: ["ADR: why an agent", "Tool schemas and permissions", "Orchestration", "Trajectory evaluation", "Cost and latency report"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["agents", "llm", "system-design", "security", "monitoring"],
    evidenceClass: "Signature Project",
  },
  {
    key: "p-production-ai-service",
    title: "Deployed Production-style AI Service",
    ladderLevel: 9,
    sourceCategory: "Industry Extension",
    brief:
      "Take one earlier model and make it operable: typed API, authentication, containerization, CI/CD, cloud deployment, monitoring dashboards, drift detection, documented rollback and an on-call runbook.",
    dataPolicy: "Real data with documented provenance; no personal data without lawful basis.",
    suggestedData: [],
    milestones: ["API contract", "Container + CI/CD", "Cloud deployment", "Monitoring and alerts", "Runbook and rollback test"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["mlops", "deployment", "cloud", "monitoring", "security", "docker"],
    evidenceClass: "Signature Project",
  },
  {
    key: "p-research-reproduction",
    title: "Research Reproduction and Ablation",
    ladderLevel: 10,
    sourceCategory: "Research Extension",
    brief:
      "Select a paper with available code or sufficient detail, reproduce the headline result within a declared tolerance, run one clean ablation, and write a report that states clearly whether reproduction succeeded.",
    dataPolicy: "Use the paper's dataset under its licence; document any substitution and its effect on comparability.",
    suggestedData: [{ name: "Papers with Code", url: "https://paperswithcode.com/", note: dataNote }],
    milestones: ["Claim extraction", "Baseline reproduction", "Method reproduction", "Ablation", "Report"],
    definitionOfDone: DOD_BASE,
    skillKeys: ["research", "deep-learning", "model-evaluation", "technical-english"],
    evidenceClass: "Signature Project",
  },
];

export const CAREER_ROLES = [
  {
    key: "role-navisoft-ai-engineer",
    title: "AI Engineer (Navisoft-style reference blueprint)",
    company: "Navisoft (reference posting)",
    sourceUrl: "https://app.devfound.ai/jobs/ai-engineers-navisoft/140943",
    verificationStatus: "likely_not_verified",
    snapshotDate: "2026-01-01",
    region: "unspecified",
    seniority: "unspecified",
    notes:
      "Blueprint supplied in the build specification. Availability, seniority and location were NOT re-verified during this build; treat as a requirement blueprint, not as an open vacancy. Re-check the posting before applying.",
    requirements: [
      { skillKey: "machine-learning", importance: "hard", note: "AI/ML model development" },
      { skillKey: "tensorflow", importance: "hard", note: "TensorFlow (PyTorch commonly expected alongside)" },
      { skillKey: "deep-learning", importance: "hard", note: "Deep learning model development" },
      { skillKey: "nlp", importance: "hard", note: "Natural language processing" },
      { skillKey: "statistics", importance: "hard", note: "Statistical modelling" },
      { skillKey: "sql", importance: "hard", note: "SQL and database design" },
      { skillKey: "data-modeling", importance: "hard", note: "Database design" },
      { skillKey: "spark", importance: "hard", note: "Spark / Hadoop ecosystem" },
      { skillKey: "data-engineering", importance: "hard", note: "ETL pipelines (Talend listed in the blueprint)" },
      { skillKey: "aws", importance: "hard", note: "Cloud deployment on AWS" },
      { skillKey: "llm", importance: "hard", note: "Generative AI" },
      { skillKey: "model-evaluation", importance: "hard", note: "Model evaluation and data mining" },
      { skillKey: "python", importance: "hard", note: "Primary language" },
      { skillKey: "bash", importance: "preferred", note: "Bash scripting" },
      { skillKey: "r-lang", importance: "preferred", note: "R for statistical modelling" },
      { skillKey: "sas", importance: "familiarity", note: "SAS listed; targeted familiarity is sufficient unless the role is regulated-analytics heavy" },
      { skillKey: "java", importance: "familiarity", note: "Java listed; applied familiarity" },
      { skillKey: "c-programming", importance: "familiarity", note: "C listed; foundational understanding" },
      { skillKey: "system-design", importance: "preferred", note: "Scalable systems" },
    ],
  },
  {
    key: "role-nuwave-ai-engineer",
    title: "Production AI Engineer (NUWAVE-style reference blueprint)",
    company: "NUWAVE (reference posting)",
    sourceUrl: "https://jobs.nuwave.com/apply/JshTpQ8tb8/AI-Engineer",
    verificationStatus: "likely_not_verified",
    snapshotDate: "2026-01-01",
    region: "unspecified — the original posting may carry location restrictions",
    seniority: "unspecified",
    notes:
      "Blueprint supplied in the build specification. Location restrictions, seniority and availability were NOT re-verified during this build. This is a reference role, not an employment guarantee.",
    requirements: [
      { skillKey: "python", importance: "hard", note: "Primary language" },
      { skillKey: "typescript", importance: "hard", note: "Application surfaces and tooling" },
      { skillKey: "aws", importance: "hard", note: "Cloud engineering" },
      { skillKey: "azure", importance: "hard", note: "Azure, Entra ID, Microsoft ecosystem" },
      { skillKey: "docker", importance: "hard", note: "Containers" },
      { skillKey: "cloud", importance: "hard", note: "Serverless and identity" },
      { skillKey: "rag", importance: "hard", note: "RAG and GraphRAG" },
      { skillKey: "vector-search", importance: "hard", note: "Vector search" },
      { skillKey: "graph-databases", importance: "hard", note: "Graph databases for GraphRAG" },
      { skillKey: "agents", importance: "hard", note: "Agent workflows and multi-agent orchestration" },
      { skillKey: "git", importance: "hard", note: "Version control and review" },
      { skillKey: "testing", importance: "hard", note: "Testing discipline" },
      { skillKey: "deployment", importance: "hard", note: "Deployment and rollback" },
      { skillKey: "terraform", importance: "preferred", note: "Infrastructure as code (Terraform/OpenTofu)" },
      { skillKey: "monitoring", importance: "hard", note: "Observability" },
      { skillKey: "security", importance: "hard", note: "Security and ISO/IEC 42001-style governance concepts" },
      { skillKey: "systems", importance: "preferred", note: "Distributed systems reasoning" },
      { skillKey: "technical-english", importance: "hard", note: "Technical documentation and incident communication" },
      { skillKey: "communication", importance: "hard", note: "Incident response communication" },
    ],
  },
];

export const ENGLISH_TERMS = [
  { term: "idempotent", simpleDefinition: "Safe to run more than once — repeating it does not change the result again.", arabic: "عملية تكرارها لا يغيّر النتيجة", example: "Make the load step idempotent so a retry does not duplicate rows.", domain: "engineering", collocations: ["idempotent operation", "idempotency key"] },
  { term: "observability", simpleDefinition: "How well you can understand what is happening inside a system from its outputs.", arabic: "قابلية الرصد", example: "We added tracing to improve observability of the retrieval step.", domain: "engineering", collocations: ["observability stack", "improve observability"] },
  { term: "encapsulation", simpleDefinition: "Keeping implementation details inside a component and exposing a controlled interface.", arabic: "التغليف", example: "Encapsulation lets us swap the storage layer without touching callers.", domain: "programming", collocations: ["proper encapsulation", "break encapsulation"] },
  { term: "abstraction", simpleDefinition: "Hiding irrelevant detail so you can reason about the important part.", arabic: "التجريد", example: "The Retriever abstraction hides whether we use BM25 or vectors.", domain: "programming", collocations: ["leaky abstraction", "level of abstraction"] },
  { term: "robustness", simpleDefinition: "How well something keeps working when conditions change or input is unusual.", arabic: "المتانة", example: "We tested robustness against malformed input.", domain: "engineering", collocations: ["robustness check", "robust to noise"] },
  { term: "generalization", simpleDefinition: "How well a model performs on data it has never seen.", arabic: "التعميم", example: "The gap between train and validation shows poor generalization.", domain: "ai", collocations: ["generalization gap", "generalize to"] },
  { term: "calibration", simpleDefinition: "Whether predicted probabilities match real-world frequencies.", arabic: "المعايرة", example: "The model is accurate but poorly calibrated above 0.8.", domain: "ai", collocations: ["calibration curve", "well-calibrated"] },
  { term: "inference", simpleDefinition: "Running a trained model to get predictions (also: drawing a conclusion from data).", arabic: "الاستدلال", example: "Inference latency is 120 ms at p95.", domain: "ai", collocations: ["inference latency", "batch inference"] },
  { term: "orchestration", simpleDefinition: "Coordinating several steps or services so they run in the right order with the right handling.", arabic: "التنسيق/التنظيم", example: "Airflow handles orchestration of the nightly pipeline.", domain: "engineering", collocations: ["orchestration layer", "orchestrate tasks"] },
  { term: "concurrency", simpleDefinition: "Structuring work so several tasks can progress without waiting for each other.", arabic: "التزامن", example: "Use async concurrency for I/O-bound provider calls.", domain: "systems", collocations: ["concurrency model", "concurrency limit"] },
  { term: "reproducibility", simpleDefinition: "Getting the same result again from the same inputs and code.", arabic: "قابلية إعادة الإنتاج", example: "Pin the seed and the dependency versions for reproducibility.", domain: "research", collocations: ["reproducibility crisis", "ensure reproducibility"] },
  { term: "maintainability", simpleDefinition: "How easily other engineers can change the system safely later.", arabic: "قابلية الصيانة", example: "That clever one-liner hurts maintainability.", domain: "engineering", collocations: ["long-term maintainability"] },
  { term: "scalability", simpleDefinition: "Whether the system keeps working as load or data grows.", arabic: "قابلية التوسع", example: "The shuffle step limits scalability past 2 TB.", domain: "engineering", collocations: ["horizontal scalability"] },
  { term: "uncertainty", simpleDefinition: "How much you do not know about an estimate or prediction.", arabic: "عدم اليقين", example: "Report the uncertainty, not just the point estimate.", domain: "statistics", collocations: ["quantify uncertainty", "uncertainty estimate"] },
  { term: "trade-off", simpleDefinition: "Something you give up in order to gain something else.", arabic: "مفاضلة", example: "We accepted a latency trade-off for better recall.", domain: "engineering", collocations: ["accept a trade-off", "trade-off between"] },
  { term: "leakage", simpleDefinition: "When information that would not be available at prediction time gets into training.", arabic: "تسريب البيانات", example: "The feature was written after the event — that is leakage.", domain: "ai", collocations: ["data leakage", "target leakage"] },
  { term: "drift", simpleDefinition: "When the data or the real-world relationship changes after deployment.", arabic: "الانجراف", example: "We alert on feature drift beyond the agreed threshold.", domain: "mlops", collocations: ["data drift", "concept drift"] },
  { term: "regression", simpleDefinition: "Something that used to work and no longer does (also: a statistical model type).", arabic: "تراجع/انحدار", example: "The release caused a latency regression.", domain: "engineering", collocations: ["regression test", "performance regression"] },
  { term: "provenance", simpleDefinition: "The documented origin and history of data or an artifact.", arabic: "مصدر البيانات وتاريخها", example: "Every chunk stores its provenance and licence.", domain: "governance", collocations: ["data provenance", "track provenance"] },
  { term: "deterministic", simpleDefinition: "Always produces the same output for the same input.", arabic: "حتمي", example: "Prefer a deterministic workflow where the steps are known.", domain: "engineering", collocations: ["deterministic behaviour"] },
  { term: "latency", simpleDefinition: "How long a single operation takes, end to end.", arabic: "زمن الاستجابة", example: "Report p95 latency, not the average.", domain: "engineering", collocations: ["tail latency", "latency budget"] },
  { term: "throughput", simpleDefinition: "How much work the system completes per unit of time.", arabic: "الإنتاجية", example: "Batching increased throughput but raised latency.", domain: "engineering", collocations: ["sustained throughput"] },
  { term: "baseline", simpleDefinition: "The simple reference result that any new method must beat.", arabic: "خط الأساس", example: "The deep model did not beat the seasonal naive baseline.", domain: "ai", collocations: ["strong baseline", "beat the baseline"] },
  { term: "ablation", simpleDefinition: "Removing one component to measure how much it actually contributed.", arabic: "دراسة الحذف", example: "The ablation showed the reranker contributed most of the gain.", domain: "research", collocations: ["ablation study"] },
  { term: "faithfulness", simpleDefinition: "Whether a generated answer is actually supported by the retrieved evidence.", arabic: "الأمانة للمصدر", example: "Faithfulness dropped when we increased chunk size.", domain: "ai", collocations: ["faithfulness score"] },
  { term: "least privilege", simpleDefinition: "Giving an identity only the permissions it truly needs.", arabic: "أقل امتياز ممكن", example: "The role follows least privilege: read access to one prefix.", domain: "security", collocations: ["principle of least privilege"] },
  { term: "prompt injection", simpleDefinition: "When untrusted text tries to act as instructions to a language model.", arabic: "حقن التعليمات", example: "Treat document text as data to prevent prompt injection.", domain: "security", collocations: ["indirect prompt injection"] },
  { term: "acceptance criteria", simpleDefinition: "The agreed, testable conditions that define when work is complete.", arabic: "معايير القبول", example: "Each deliverable needs testable acceptance criteria.", domain: "professional", collocations: ["meet the acceptance criteria"] },
  { term: "rollback", simpleDefinition: "Returning to the previous working version after a bad release.", arabic: "التراجع إلى نسخة سابقة", example: "An untested rollback is a hope, not a plan.", domain: "engineering", collocations: ["rollback plan", "roll back a release"] },
  { term: "post-incident review", simpleDefinition: "A written analysis after an outage focused on causes and prevention, not blame.", arabic: "مراجعة ما بعد الحادثة", example: "The post-incident review found a missing schema check.", domain: "professional", collocations: ["blameless post-incident review"] },
];

export const FREELANCE_SCENARIOS = [
  {
    key: "fs-chatbot",
    title: "“I need an AI chatbot”",
    clientMessage:
      "Hi — we run a mid-size logistics company. We want an AI chatbot on our website that can answer customer questions. Our competitor has one. How much and how long?",
    hiddenConstraints: [
      "Knowledge lives in 400 PDFs plus a Zendesk export, both partly outdated",
      "Legal requires that the bot never gives shipping-liability commitments",
      "Peak traffic is 60 concurrent users during weekday mornings",
      "They expect you to maintain it; no in-house engineer",
      "Budget is far smaller than the scope implies",
    ],
    requiredQuestions: [
      "Who are the users and what decision are they trying to make?",
      "What knowledge must it use, where does it live, and who owns/updates it?",
      "What must the assistant never say or do?",
      "Which systems must it integrate with?",
      "What data is sensitive, and what are the privacy/retention requirements?",
      "Expected volume and acceptable response time?",
      "How will we agree that it works — what is the acceptance test?",
      "Who operates and maintains it after delivery?",
      "What is the budget range and the deadline?",
    ],
    deliverableRubric: [
      "Asked at least six discovery questions before any price discussion",
      "Proposal defines scope, exclusions and testable acceptance criteria",
      "Identified the knowledge-freshness and liability risks explicitly",
      "Specified maintenance terms and a change-request process",
    ],
  },
  {
    key: "fs-forecasting",
    title: "“Can you predict our sales?”",
    clientMessage:
      "We have three years of monthly sales in spreadsheets. We want a model that predicts next quarter accurately so we can plan inventory. Can you do it by the end of the month?",
    hiddenConstraints: [
      "36 monthly observations total — very little data",
      "A pricing change 14 months ago broke the historical relationship",
      "They actually need inventory decisions, not a forecast number",
      "Spreadsheets have inconsistent product naming across years",
    ],
    requiredQuestions: [
      "What decision will the forecast drive, and what error is tolerable?",
      "How much history exists and at what granularity?",
      "What changed in the business during that period?",
      "Are there known drivers (price, promotions, seasonality, stockouts)?",
      "What is the current method and how wrong is it today?",
      "How will we measure success at the end?",
    ],
    deliverableRubric: [
      "Reframed the request around the inventory decision",
      "Stated the data-volume limitation honestly before quoting",
      "Proposed a baseline-first approach with a measurable comparison",
      "Defined acceptance criteria in terms of the decision, not the model",
    ],
  },
  {
    key: "fs-scope-change",
    title: "Mid-project scope change",
    clientMessage:
      "Great progress on the document assistant! Small addition: can it also read our SharePoint, handle voice input, and support Arabic? Should be quick since the hard part is done.",
    hiddenConstraints: [
      "SharePoint access requires identity integration and permission-aware retrieval",
      "Voice input is a new modality with its own evaluation needs",
      "Arabic support changes tokenization, retrieval quality and evaluation entirely",
      "The original fixed price assumed one English document corpus",
    ],
    requiredQuestions: [
      "Which of the three is most valuable, and by when?",
      "Who controls SharePoint permissions, and must retrieval respect per-user access?",
      "What accuracy is acceptable for Arabic, and who evaluates it?",
      "Shall we handle this as a change request with its own scope and price?",
    ],
    deliverableRubric: [
      "Did not accept the change silently inside the original price",
      "Explained why each item is a distinct piece of work, in plain language",
      "Offered a prioritised change request with separate acceptance criteria",
      "Preserved the relationship — professional, not defensive",
    ],
  },
];
