import type { Importance, NotebookGuidance, SourceCategory } from "./types";

/**
 * Additive layers (§130–§138, §153–§169, §178). These never replace original
 * material: each carries its own source category and sits in its own course.
 */

export interface ExtensionLesson {
  id: string;
  courseId: string;
  title: string;
  sourceCategory: SourceCategory;
  importance: Importance;
  level: 1 | 2 | 3 | 4 | 5;
  topics: string[];
  objectives: string[];
  mastery: string[];
  skills: string[];
  effort: number;
  prereqs: string[];
  notebook: NotebookGuidance;
  projects?: string[];
  roles?: string[];
  harvardMappings?: string[];
  sources?: string[];
}

const nb = (mustWrite: string[], recommended: string[], optional: string[]): NotebookGuidance => ({ mustWrite, recommended, optional });

export const EXTENSION_LESSONS: ExtensionLesson[] = [
  // ---------- Computer Science Foundations (§130) ----------
  {
    id: "l-cs-1",
    courseId: "c-cs-foundations",
    title: "C, Compilation and the Memory Model",
    sourceCategory: "Harvard College",
    importance: "CORE",
    level: 2,
    topics: ["C programming", "memory model", "pointers", "stack/heap", "compilation/linking", "debugging", "segmentation faults", "buffer overflow"],
    objectives: [
      "Explain what the compiler, assembler and linker each produce.",
      "Draw the stack and heap for a running program and locate every variable.",
      "Diagnose a segmentation fault from first principles.",
    ],
    mastery: ["Explain why a dangling pointer sometimes 'works'.", "Trace memory for a program that passes an array to a function."],
    skills: ["sk-c-memory", "sk-debugging"],
    effort: 300,
    prereqs: ["l-om1-3"],
    notebook: nb(
      ["Compilation pipeline: preprocess → compile → assemble → link", "Stack vs heap: lifetime, cost, failure mode", "One pointer diagram you drew yourself"],
      ["Common C memory bugs and their symptoms"],
      ["Full pointer-arithmetic rules"],
    ),
    harvardMappings: ["hv-cs50", "hv-cs61"],
    sources: ["src-cs50-fall-2026-syllabus"],
  },
  {
    id: "l-cs-2",
    courseId: "c-cs-foundations",
    title: "Linux, the Command Line and Processes",
    sourceCategory: "Industry Extension",
    importance: "CORE",
    level: 1,
    topics: ["Linux/CLI", "file system", "permissions", "pipes and redirection", "processes/threads", "signals", "shell scripting"],
    objectives: ["Compose shell pipelines to answer a question about a system.", "Inspect and control running processes.", "Write a defensive shell script."],
    mastery: ["Find and kill the process holding a port, explaining each command.", "Explain what a pipe does to file descriptors."],
    skills: ["sk-bash-linux", "sk-os-concurrency"],
    effort: 180,
    prereqs: [],
    notebook: nb(["Ten commands you will use daily", "Permission bits explained", "set -euo pipefail and why"], ["Process states diagram"], ["Full signal list"]),
  },
  {
    id: "l-cs-3",
    courseId: "c-cs-foundations",
    title: "Data Structures in Depth",
    sourceCategory: "Harvard College",
    importance: "CORE",
    level: 3,
    topics: ["linked lists", "stacks/queues", "trees", "binary search trees", "hash tables", "tries", "graphs", "abstract data types"],
    objectives: [
      "Implement each structure and state its cost for each operation.",
      "Choose a structure from access patterns rather than familiarity.",
      "Explain hash collisions and their resolution strategies.",
    ],
    mastery: ["Justify a structure choice with a complexity table you produced.", "Explain why a hash table degrades to O(n)."],
    skills: ["sk-datastructures"],
    effort: 360,
    prereqs: ["l-om1-4", "l-cs-1"],
    notebook: nb(["Operation cost table for all structures", "Hash collision strategies", "One tree traversal written by hand"], ["Trie use cases"], ["Self-balancing tree proofs"]),
    harvardMappings: ["hv-cs1240"],
  },
  {
    id: "l-cs-4",
    courseId: "c-cs-foundations",
    title: "Algorithms, Complexity and Computational Limits",
    sourceCategory: "Harvard College",
    importance: "CORE",
    level: 4,
    topics: ["recursion", "divide and conquer", "greedy algorithms", "dynamic programming", "sorting/searching", "asymptotic complexity", "formal logic", "proof techniques", "computational limitations"],
    objectives: [
      "Design an algorithm and prove its complexity bound.",
      "Recognise when greedy fails and dynamic programming is required.",
      "State what undecidability means for engineering practice.",
    ],
    mastery: ["Produce a correct DP formulation for an unfamiliar problem.", "Give a counter-example that breaks a plausible greedy strategy."],
    skills: ["sk-algorithms", "sk-complexity"],
    effort: 420,
    prereqs: ["l-cs-3"],
    notebook: nb(["DP recipe: state, transition, base case, order", "Master theorem cases", "One proof you wrote yourself"], ["Greedy exchange-argument sketch"], ["NP-completeness catalogue"]),
    harvardMappings: ["hv-cs1200", "hv-cs1210", "hv-cs1240"],
  },
  {
    id: "l-cs-5",
    courseId: "c-cs-foundations",
    title: "Systems, Concurrency and Networking for AI Services",
    sourceCategory: "Harvard College",
    importance: "SUPPORT",
    level: 3,
    topics: ["computer organization", "operating-system concepts", "processes/threads", "concurrency", "networking fundamentals", "HTTP/TCP/IP/DNS concepts", "database transactions", "distributed systems"],
    objectives: [
      "Explain where latency comes from in a request to a model endpoint.",
      "Identify a race condition and describe the synchronisation that removes it.",
      "Reason about transactions and consistency when a pipeline writes state.",
    ],
    mastery: ["Draw the full path of one inference request and annotate each latency contribution.", "Explain at-least-once vs exactly-once in your own pipeline."],
    skills: ["sk-os-concurrency", "sk-networking"],
    effort: 300,
    prereqs: ["l-cs-2"],
    notebook: nb(["Latency budget breakdown", "Race condition definition + your example", "ACID properties with one failure each"], ["Caching layers and invalidation"], ["TCP congestion control detail"]),
    harvardMappings: ["hv-cs61", "hv-cs1410-1411"],
  },

  // ---------- Statistics depth ----------
  {
    id: "l-stat-1",
    courseId: "c-statistics",
    title: "Probability Depth: Random Variables, Expectation and Bayes",
    sourceCategory: "Harvard College",
    importance: "CORE",
    level: 3,
    topics: ["random variables", "expectation", "variance", "covariance", "distributions", "conditional probability", "Bayes", "likelihood", "maximum likelihood", "MAP"],
    objectives: ["Derive expectation and variance for standard distributions.", "Write a likelihood and maximise it.", "Explain the difference between MLE and MAP."],
    mastery: ["Derive the MLE for a Bernoulli sample by hand.", "Explain what prior information changes in a MAP estimate."],
    skills: ["sk-probability", "sk-statistics"],
    effort: 360,
    prereqs: ["l-om2-5"],
    notebook: nb(["E[X] and Var[X] definitions", "Likelihood vs probability", "MLE recipe"], ["Distribution family cheat sheet"], ["Moment generating functions"]),
    harvardMappings: ["hv-stat110"],
  },
  {
    id: "l-stat-2",
    courseId: "c-statistics",
    title: "Inference, Testing and Experimental Design",
    sourceCategory: "Harvard College",
    importance: "CORE",
    level: 3,
    topics: ["statistical inference", "hypothesis testing", "confidence intervals", "experimental design", "power", "multiple comparisons", "regression inference"],
    objectives: ["Design an experiment that can answer the stated question.", "Compute and interpret an interval correctly.", "Explain the multiple-comparisons problem in a model-selection context."],
    mastery: ["Critique an A/B test that peeked at results daily.", "State the assumptions your test requires and check two of them."],
    skills: ["sk-statistics"],
    effort: 300,
    prereqs: ["l-stat-1", "l-om3-2"],
    notebook: nb(["Test selection table", "Power and sample size relationship", "What a CI claims"], ["Peeking and sequential testing"], ["Bayesian A/B alternatives"]),
  },

  // ---------- Data engineering extension ----------
  {
    id: "l-de-1",
    courseId: "c-data-engineering",
    title: "Modelling, Warehouses and Lakehouses",
    sourceCategory: "Industry Extension",
    importance: "INDUSTRY_EXTENSION",
    level: 3,
    topics: ["data modeling", "warehouse concepts", "lake/lakehouse concepts", "partitioning", "file formats", "schema evolution"],
    objectives: ["Choose a storage layout from query patterns.", "Explain partitioning's effect on scan cost.", "Plan a schema change that does not break consumers."],
    mastery: ["Justify a partition key with a query-pattern argument.", "Describe a backwards-compatible schema migration."],
    skills: ["sk-data-engineering"],
    effort: 240,
    prereqs: ["l-om5-4"],
    notebook: nb(["Star vs snowflake vs wide table", "Partition key selection rule", "Columnar format advantage"], ["Lakehouse table formats"], ["Vendor comparison"]),
    harvardMappings: ["hv-cs1650"],
  },
  {
    id: "l-de-2",
    courseId: "c-data-engineering",
    title: "Orchestration, Batch and Streaming",
    sourceCategory: "Industry Extension",
    importance: "INDUSTRY_EXTENSION",
    level: 3,
    topics: ["ETL/ELT", "batch vs streaming", "Airflow", "dbt", "Spark", "Spark SQL", "shuffle concepts", "Hadoop concepts", "HDFS", "MapReduce concepts", "Databricks awareness", "Talend awareness"],
    objectives: ["Express a pipeline as a DAG with retries and idempotent tasks.", "Explain a shuffle and why it dominates Spark cost.", "Decide batch vs streaming from the latency requirement."],
    mastery: ["Describe how your DAG recovers from a mid-run failure.", "Explain one Spark job you would rewrite to avoid a shuffle."],
    skills: ["sk-data-engineering"],
    effort: 300,
    prereqs: ["l-de-1"],
    notebook: nb(["DAG design rules", "Shuffle definition and cost", "Batch vs streaming decision rule"], ["dbt model layering"], ["MapReduce history"]),
    roles: ["role-navisoft"],
  },

  // ---------- LLM depth ----------
  {
    id: "l-llm-1",
    courseId: "c-llm",
    title: "Tokenisation, Context and Inference Controls",
    sourceCategory: "Industry Extension",
    importance: "CORE",
    level: 3,
    topics: ["tokenization", "embeddings", "context windows", "generation controls", "temperature and sampling", "inference", "latency", "cost"],
    objectives: ["Predict how tokenisation changes cost and truncation behaviour.", "Choose sampling parameters for a task and justify them.", "Estimate the cost and latency of a feature before building it."],
    mastery: ["Compute the token cost of a planned feature and defend the estimate.", "Explain why temperature 0 is not determinism in a distributed service."],
    skills: ["sk-transformers", "sk-llm-eval"],
    effort: 240,
    prereqs: ["l-om7-6"],
    notebook: nb(["Tokenisation effects list", "Sampling parameter meanings", "Cost formula for your feature"], ["Context window budgeting"], ["Tokeniser algorithm internals"]),
    sources: ["src-puter-deepseek-v4"],
    roles: ["role-nuwave"],
  },
  {
    id: "l-llm-2",
    courseId: "c-llm",
    title: "LLM Evaluation and Hallucination Analysis",
    sourceCategory: "Industry Extension",
    importance: "CORE",
    level: 4,
    topics: ["evaluation", "hallucination analysis", "task metrics", "regression suites", "human review", "LLM-as-judge limitations", "failure taxonomies"],
    objectives: [
      "Build an evaluation set before building the feature.",
      "Classify failures into a taxonomy that drives fixes.",
      "State the limits of LLM-as-judge evaluation.",
    ],
    mastery: ["Prove a prompt change did not regress an existing capability.", "Produce a failure taxonomy from twenty real outputs."],
    skills: ["sk-llm-eval"],
    effort: 300,
    prereqs: ["l-llm-1"],
    notebook: nb(["Evaluation-first rule", "Failure taxonomy categories", "Why judge models are biased"], ["Regression suite structure"], ["Benchmark landscape"]),
    roles: ["role-nuwave"],
  },
  {
    id: "l-llm-3",
    courseId: "c-llm",
    title: "Fine-tuning, LoRA/QLoRA and Quantisation",
    sourceCategory: "Harvard Extension",
    importance: "ADVANCED",
    level: 4,
    topics: ["fine-tuning", "LoRA", "QLoRA", "quantization", "Hugging Face", "data curation", "catastrophic forgetting"],
    objectives: ["Decide whether fine-tuning is justified against prompting and retrieval.", "Explain what LoRA changes and why it is cheap.", "Describe the quality cost of quantisation."],
    mastery: ["Write the decision memo for a fine-tune, including data and cost.", "Explain the evaluation you would run before and after."],
    skills: ["sk-transformers"],
    effort: 300,
    prereqs: ["l-llm-2"],
    notebook: nb(["Fine-tune decision criteria", "LoRA rank intuition", "Quantisation trade-off"], ["Dataset curation checklist"], ["PEFT variants"]),
    harvardMappings: ["hv-csci-e222"],
  },

  // ---------- RAG ----------
  {
    id: "l-rag-1",
    courseId: "c-rag",
    title: "Retrieval Pipelines: Chunking, Embedding and Search",
    sourceCategory: "Industry Extension",
    importance: "CORE",
    level: 3,
    topics: ["retrieval", "chunking", "embeddings", "vector search", "hybrid search", "metadata filtering", "reranking concepts"],
    objectives: ["Design chunking from the question shape, not a default size.", "Explain when lexical search beats vector search.", "Add metadata filters that make retrieval auditable."],
    mastery: ["Diagnose which pipeline stage caused a wrong answer.", "Justify a hybrid search configuration with retrieval metrics."],
    skills: ["sk-rag"],
    effort: 300,
    prereqs: ["l-om7-6"],
    notebook: nb(["Pipeline stages in order", "Chunking decision rule", "Hybrid search: why both"], ["Reranking cost/benefit"], ["Index type comparison"]),
    projects: ["pj-rag-system"],
    roles: ["role-nuwave"],
  },
  {
    id: "l-rag-2",
    courseId: "c-rag",
    title: "Grounding, Citation and RAG Evaluation",
    sourceCategory: "Industry Extension",
    importance: "CORE",
    level: 4,
    topics: ["citation grounding", "RAG evaluation", "faithfulness", "context precision/recall", "answer refusal", "freshness"],
    objectives: ["Measure retrieval and generation quality separately.", "Make a system refuse rather than fabricate.", "Keep citations verifiable end to end."],
    mastery: ["Show a retrieval metric and a generation metric for your own system.", "Demonstrate a correct refusal on an unanswerable question."],
    skills: ["sk-rag", "sk-llm-eval"],
    effort: 300,
    prereqs: ["l-rag-1"],
    notebook: nb(["Separate retrieval vs generation metrics", "Refusal policy", "Citation verification check"], ["Freshness strategy"], ["RAG metric libraries"]),
    projects: ["pj-rag-system"],
  },
  {
    id: "l-rag-3",
    courseId: "c-rag",
    title: "Knowledge Graphs and GraphRAG",
    sourceCategory: "Industry Extension",
    importance: "SPECIALIZATION",
    level: 4,
    topics: ["knowledge graphs", "GraphRAG", "graph databases", "entity extraction", "relationship modelling", "graph traversal for retrieval"],
    objectives: ["Decide when graph structure earns its ingestion cost.", "Model entities and relations for a real corpus.", "Combine graph traversal with vector retrieval."],
    mastery: ["Give a question type your vector-only system cannot answer and show the graph answering it.", "State the maintenance cost of your graph."],
    skills: ["sk-graphrag"],
    effort: 300,
    prereqs: ["l-rag-2"],
    notebook: nb(["When a graph beats vectors", "Entity/relation schema", "Traversal + vector hybrid sketch"], ["Graph DB options"], ["Ontology design"]),
    roles: ["role-nuwave"],
  },

  // ---------- Agents ----------
  {
    id: "l-agent-1",
    courseId: "c-agents",
    title: "The Agent Decision Framework",
    sourceCategory: "Industry Extension",
    importance: "CORE",
    level: 3,
    topics: ["deterministic workflow", "single LLM call", "tool-using workflow", "single agent", "multi-agent system", "cost and failure analysis"],
    objectives: ["Place a requirement on the five-option design ladder and justify the choice.", "Argue against an agent where a workflow suffices.", "Predict failure modes for each option."],
    mastery: ["Produce a written design decision rejecting an agent for a real requirement.", "Explain how non-determinism changes your testing strategy."],
    skills: ["sk-agents"],
    effort: 180,
    prereqs: ["l-rag-1"],
    notebook: nb(["The five design options in order of cost", "Questions that decide the level", "Failure modes per option"], ["Determinism vs flexibility"], ["Framework landscape"]),
  },
  {
    id: "l-agent-2",
    courseId: "c-agents",
    title: "Tool Calling, Memory and Orchestration",
    sourceCategory: "Industry Extension",
    importance: "SPECIALIZATION",
    level: 4,
    topics: ["tool calling", "agent planning", "memory/state", "orchestration", "multi-agent patterns", "permissions", "safety", "observability", "loop limits"],
    objectives: ["Define tool schemas that constrain the model usefully.", "Design state and memory with explicit boundaries.", "Enforce permissions and loop limits so an agent cannot run away."],
    mastery: ["Show your agent refusing an out-of-scope tool call.", "Demonstrate a hard iteration limit and its logging."],
    skills: ["sk-agents", "sk-security", "sk-observability"],
    effort: 300,
    prereqs: ["l-agent-1"],
    notebook: nb(["Tool schema design rules", "Permission model", "Loop-limit and timeout policy"], ["Memory types and lifetimes"], ["Multi-agent topologies"]),
    roles: ["role-nuwave"],
  },

  // ---------- Software engineering ----------
  {
    id: "l-se-1",
    courseId: "c-software-engineering",
    title: "Requirements, Git and Code Review",
    sourceCategory: "Industry Extension",
    importance: "CORE",
    level: 2,
    topics: ["requirements", "acceptance criteria", "decomposition", "issue tracking", "Git", "GitHub", "branching", "commits", "pull requests", "code review", "semantic versioning"],
    objectives: ["Turn a vague request into acceptance criteria.", "Produce a pull request that is fast to review.", "Give review feedback that improves the code and the author."],
    mastery: ["Write acceptance criteria a stranger could test against.", "Review a PR and catch a correctness issue, not just style."],
    skills: ["sk-git", "sk-communication"],
    effort: 240,
    prereqs: ["l-om1-5"],
    notebook: nb(["Acceptance criteria template", "Commit message convention", "Review checklist"], ["Branching strategy"], ["Git internals"]),
  },
  {
    id: "l-se-2",
    courseId: "c-software-engineering",
    title: "Testing, Typing and Debugging Discipline",
    sourceCategory: "Industry Extension",
    importance: "CORE",
    level: 3,
    topics: ["typing", "linting", "formatting", "unit tests", "integration tests", "E2E tests", "debugging", "logging", "configuration"],
    objectives: ["Choose the right test level for a risk.", "Test non-deterministic behaviour without pretending it is deterministic.", "Debug by hypothesis rather than by shotgun."],
    mastery: ["Write a failing test that reproduces a real bug before fixing it.", "Explain what your test suite does not cover."],
    skills: ["sk-testing", "sk-debugging"],
    effort: 300,
    prereqs: ["l-se-1"],
    notebook: nb(["Test pyramid with your own examples", "Fixture vs mock decision", "Debugging loop: observe → hypothesise → test"], ["Logging levels policy"], ["Property-based testing"]),
  },
  {
    id: "l-se-3",
    courseId: "c-software-engineering",
    title: "API Design, Idempotency and Release Engineering",
    sourceCategory: "Industry Extension",
    importance: "CORE",
    level: 3,
    topics: ["API design", "REST", "authentication", "authorization", "caching", "retries", "idempotency", "background jobs", "queues", "concurrency / async", "performance", "refactoring", "release engineering", "rollback"],
    objectives: ["Design an endpoint that is safe to retry and cheap to cache.", "Separate authentication from authorisation in your design.", "Plan a release you can roll back."],
    mastery: ["Make a non-idempotent endpoint idempotent and prove it.", "Describe your rollback procedure concretely."],
    skills: ["sk-api-design", "sk-security"],
    effort: 300,
    prereqs: ["l-se-2"],
    notebook: nb(["Idempotency key pattern", "AuthN vs AuthZ definitions", "Rollback checklist"], ["Caching invalidation strategies"], ["gRPC comparison"]),
    roles: ["role-nuwave"],
  },

  // ---------- Cloud ----------
  {
    id: "l-cloud-1",
    courseId: "c-cloud",
    title: "AWS Core for AI Services",
    sourceCategory: "Industry Extension",
    importance: "CORE",
    level: 3,
    topics: ["IAM", "S3", "Lambda", "API Gateway", "EC2 fundamentals", "ECR", "ECS fundamentals", "CloudWatch", "VPC/networking basics", "secrets concepts", "model/API hosting", "serverless patterns"],
    objectives: ["Write a least-privilege IAM policy for a stated job.", "Choose serverless vs container hosting from the workload shape.", "Instrument a service so failures are visible."],
    mastery: ["Explain every permission in your policy.", "Justify your hosting choice with cold-start, cost and latency arguments."],
    skills: ["sk-cloud-aws", "sk-observability"],
    effort: 360,
    prereqs: ["l-se-3"],
    notebook: nb(["IAM policy anatomy", "Serverless vs container decision rule", "What to log, what never to log"], ["VPC basics sketch"], ["Full service catalogue"]),
    roles: ["role-navisoft", "role-nuwave"],
  },
  {
    id: "l-cloud-2",
    courseId: "c-cloud",
    title: "Azure Working Familiarity, Containers and IaC",
    sourceCategory: "Industry Extension",
    importance: "SUPPORT",
    level: 3,
    topics: ["Entra ID", "Azure storage", "Azure compute", "Azure serverless", "monitoring", "identity and access", "Docker", "orchestration", "Terraform/OpenTofu", "infrastructure as code"],
    objectives: ["Map AWS concepts onto their Azure counterparts.", "Describe identity-centric access with Entra ID.", "Express infrastructure as reviewable code."],
    mastery: ["Produce a Terraform plan and explain each resource.", "Explain what drift is and how you detect it."],
    skills: ["sk-cloud-azure", "sk-containers"],
    effort: 300,
    prereqs: ["l-cloud-1"],
    notebook: nb(["AWS ↔ Azure concept map", "IaC state and drift", "Dockerfile layer rules"], ["Entra ID app registration flow"], ["Kubernetes objects"]),
    roles: ["role-nuwave"],
  },

  // ---------- MLOps ----------
  {
    id: "l-mlops-1",
    courseId: "c-mlops",
    title: "The Production ML Lifecycle",
    sourceCategory: "Industry Extension",
    importance: "CORE",
    level: 4,
    topics: ["data validation", "training", "experiment tracking", "evaluation", "packaging", "deployment", "monitoring", "drift / failure", "retraining / rollback", "MLflow", "model registry", "CI/CD", "reproducibility"],
    objectives: ["Describe every lifecycle stage and the artefact it produces.", "Track an experiment so it can be reproduced months later.", "Define the monitoring that would catch your model's most likely failure."],
    mastery: ["Reproduce a past experiment from the tracked metadata alone.", "Write the rollback criterion for a deployed model."],
    skills: ["sk-mlops"],
    effort: 360,
    prereqs: ["l-om8-1"],
    notebook: nb(["Lifecycle stages and artefacts", "Experiment metadata minimum set", "Rollback trigger definition"], ["Registry promotion flow"], ["Tool comparison"]),
    harvardMappings: ["hv-ac215"],
    roles: ["role-navisoft", "role-nuwave"],
  },
  {
    id: "l-mlops-2",
    courseId: "c-mlops",
    title: "Monitoring, Drift and Incident Response",
    sourceCategory: "Industry Extension",
    importance: "CORE",
    level: 4,
    topics: ["metrics", "logs", "traces", "alerting", "data drift", "concept drift", "cost spikes", "latency regression", "triage", "postmortems"],
    objectives: ["Distinguish data drift from concept drift from a pipeline bug.", "Triage an incident in a defined order.", "Write a postmortem without blame and with actions."],
    mastery: ["Run a simulated incident to mitigation and write the postmortem.", "Define alert thresholds you can defend."],
    skills: ["sk-observability", "sk-mlops"],
    effort: 300,
    prereqs: ["l-mlops-1"],
    notebook: nb(["Drift types and detection signals", "Triage order", "Postmortem template"], ["Alert fatigue avoidance"], ["Statistical drift tests"]),
    roles: ["role-nuwave"],
  },

  // ---------- Responsible AI ----------
  {
    id: "l-sec-1",
    courseId: "c-responsible-ai",
    title: "API and LLM Security",
    sourceCategory: "Industry Extension",
    importance: "CORE",
    level: 4,
    topics: ["broken object-level authorization", "broken authentication", "excessive data exposure", "injection", "SSRF", "unsafe file upload", "path traversal", "prompt injection", "tool abuse", "rate limiting"],
    objectives: ["Threat-model your own feature before building it.", "Design against prompt injection rather than hoping.", "Enforce object-level authorisation at the data layer."],
    mastery: ["Attack your own endpoint and document what you found.", "Show the authorisation check that cannot be bypassed by a crafted request."],
    skills: ["sk-security"],
    effort: 300,
    prereqs: ["l-se-3"],
    notebook: nb(["Top risks and one mitigation each", "Prompt injection defence layers", "Ownership check location rule"], ["Rate limit design"], ["Full OWASP list"]),
    sources: ["src-owasp-api-top10-2023"],
    roles: ["role-nuwave"],
  },
  {
    id: "l-sec-2",
    courseId: "c-responsible-ai",
    title: "Privacy, Fairness, Governance and Model Cards",
    sourceCategory: "Harvard College",
    importance: "CORE",
    level: 3,
    topics: ["bias", "fairness", "privacy", "governance", "accountability", "AI regulation", "responsible deployment", "model cards", "data provenance", "safe evaluation", "misuse", "social impact", "ISO/IEC 42001 concepts"],
    objectives: ["Audit a dataset for provenance and representation issues.", "Write a model card that a reviewer can challenge.", "Describe a governance control that is real, not decorative."],
    mastery: ["Produce a model card with limitations you did not want to write.", "Identify a misuse pathway for your own project and mitigate it."],
    skills: ["sk-security", "sk-communication"],
    effort: 300,
    prereqs: ["l-sec-1"],
    notebook: nb(["Model card sections", "Fairness metric choices and conflicts", "Provenance record fields"], ["Regulatory landscape summary"], ["Full standard text"]),
    harvardMappings: ["hv-cs1050", "hv-ext-ai-cert"],
  },

  // ---------- English ----------
  {
    id: "l-en-1",
    courseId: "c-english",
    title: "Standard Technical English: Reading and Vocabulary in Context",
    sourceCategory: "Industry Extension",
    importance: "SUPPORT",
    level: 2,
    topics: ["technical reading", "vocabulary", "collocations", "documentation reading", "error message comprehension", "paper abstracts"],
    objectives: ["Read authentic documentation without translating word by word.", "Use the canonical technical term even when the explanation is simplified.", "Build collocations, not isolated words."],
    mastery: ["Explain a documentation page in your own English.", "Use ten target terms correctly in your own writing."],
    skills: ["sk-english-technical"],
    effort: 120,
    prereqs: [],
    notebook: nb(["Ten terms with your own definition", "Three collocations per term", "One sentence you wrote with each"], ["Reading strategy for dense docs"], ["Full glossary"]),
    sources: ["src-cefr"],
  },
  {
    id: "l-en-2",
    courseId: "c-english",
    title: "Speaking Lab: Explain, Defend, Interview",
    sourceCategory: "Industry Extension",
    importance: "SUPPORT",
    level: 3,
    topics: ["spontaneous speaking", "technical explanation", "project presentation", "interview answers", "client communication", "shadowing", "pronunciation awareness"],
    objectives: ["Explain a concept aloud for 90 seconds without reading.", "Defend an architecture decision under questioning.", "Answer a behavioural question with a concrete structure."],
    mastery: ["Record an explanation and critique it against a rubric.", "Answer three unseen technical questions aloud."],
    skills: ["sk-english-technical", "sk-communication"],
    effort: 120,
    prereqs: ["l-en-1"],
    notebook: nb(["Your 90-second explanation skeleton", "Five hedging phrases that sound professional", "Three filler habits to remove"], ["STAR structure"], ["Pronunciation drills"]),
  },

  // ---------- Career ----------
  {
    id: "l-car-1",
    courseId: "c-career",
    title: "Target Roles, Evidence and Gap Analysis",
    sourceCategory: "Industry Extension",
    importance: "SUPPORT",
    level: 2,
    topics: ["role requirements", "skill taxonomy", "evidence", "gap analysis", "CV value classes", "resume evidence rule"],
    objectives: ["Translate a job description into a skill taxonomy.", "Map your own evidence against it honestly.", "Reject CV bullets that lack evidence."],
    mastery: ["Produce a gap report with no unsupported claim.", "Rewrite one weak CV bullet into an evidence-backed one."],
    skills: ["sk-communication"],
    effort: 120,
    prereqs: [],
    notebook: nb(["Evidence classes (§165)", "Gap report structure", "One bullet rewritten"], ["Role research sources"], ["Market snapshot method"]),
    sources: ["src-nuwave-ai-engineer", "src-navisoft-ai-engineer"],
  },
  {
    id: "l-car-2",
    courseId: "c-career",
    title: "System Design and Technical Interview Engineering",
    sourceCategory: "Industry Extension",
    importance: "SUPPORT",
    level: 4,
    topics: ["requirements", "components", "data flow", "interfaces", "failure modes", "scaling", "security", "observability", "cost", "trade-offs", "interview simulation"],
    objectives: ["Run a system design discussion in a repeatable order.", "Name trade-offs explicitly instead of asserting a 'best' design.", "Handle an interviewer's constraint change without panic."],
    mastery: ["Design an AI feature end to end on a whiteboard in 35 minutes.", "State three failure modes and their mitigations unprompted."],
    skills: ["sk-api-design", "sk-observability", "sk-communication"],
    effort: 240,
    prereqs: ["l-car-1", "l-se-3"],
    notebook: nb(["Design discussion order", "Trade-off phrasing patterns", "Failure-mode checklist"], ["Capacity estimation basics"], ["Case bank"]),
    roles: ["role-nuwave"],
  },

  // ---------- Freelance ----------
  {
    id: "l-fre-1",
    courseId: "c-freelance",
    title: "Discovery, Scope and Proposals",
    sourceCategory: "Industry Extension",
    importance: "SUPPORT",
    level: 2,
    topics: ["niche selection", "service selection", "value proposition", "client discovery", "requirements", "scope", "acceptance criteria", "estimate", "proposal", "negotiation", "change request"],
    objectives: ["Run a discovery conversation that surfaces the real constraint.", "Write a scope with explicit exclusions.", "Price work against risk, not hours alone."],
    mastery: ["Convert a vague client sentence into a scoped proposal with acceptance criteria.", "Handle a mid-project change request in writing."],
    skills: ["sk-client-discovery", "sk-communication"],
    effort: 180,
    prereqs: ["l-car-1"],
    notebook: nb(["Discovery question list (§169)", "Scope + exclusions template", "Change request policy"], ["Estimation with ranges"], ["Contract basics"]),
  },

  // ---------- Research ----------
  {
    id: "l-res-1",
    courseId: "c-research",
    title: "Reading Papers and Identifying Claims",
    sourceCategory: "Research Extension",
    importance: "RESEARCH",
    level: 4,
    topics: ["paper reading", "literature search", "claim identification", "baselines", "statistical reasoning", "critique"],
    objectives: ["Extract the central claim and the evidence offered for it.", "Identify the baseline that would make the result meaningful.", "Separate contribution from presentation."],
    mastery: ["Summarise a paper in five sentences including its weakest point.", "Propose the experiment the authors should have run."],
    skills: ["sk-research"],
    effort: 180,
    prereqs: ["l-stat-2", "l-om7-2"],
    notebook: nb(["Five-sentence summary template", "Claim → evidence → gap table", "Baseline checklist"], ["Literature search strategy"], ["Citation management"]),
  },
  {
    id: "l-res-2",
    courseId: "c-research",
    title: "Reproduction, Ablation and Scientific Writing",
    sourceCategory: "Research Extension",
    importance: "RESEARCH",
    level: 5,
    topics: ["reproduction", "ablation", "experimental design", "reproducibility", "scientific writing", "presentation"],
    objectives: ["Reproduce a published result and document every deviation.", "Design an ablation that isolates one factor.", "Write results that survive a hostile reviewer."],
    mastery: ["Report a reproduction including what you could not reproduce.", "Produce an ablation table with a clear conclusion."],
    skills: ["sk-research", "sk-communication"],
    effort: 420,
    prereqs: ["l-res-1"],
    notebook: nb(["Reproduction log fields", "Ablation design rule", "Results-section structure"], ["Figure standards"], ["Venue conventions"]),
  },
];
