import type { HarvardMapping } from "./types";

/**
 * HARVARD REALITY CHECK + MAPPING (§2, §3, §53 Part A/C, §81).
 *
 * Rules enforced here:
 *  - Harvard College and Harvard Extension School are never merged.
 *  - Every identifier below was checked against the official page named in `sourceId`.
 *  - Identifiers discussed in §38 that were NOT found on an official page keep the
 *    status `likely_not_verified` and are shown to the student as unverified.
 *  - A mapping means "this Harvard course informs this part of my curriculum".
 *    It never means "this is the Harvard course" or "I have Harvard credit".
 */

const V = "2026-10-05";

export const HARVARD_REALITY_CHECK = {
  question: "Does Harvard offer a standalone bachelor's degree in Artificial Intelligence Engineering?",
  answer:
    "Not found on Harvard's official undergraduate CS advising pages during this verification pass. Harvard College offers a Computer Science concentration (basic / honors / joint / MBB tracks) whose requirements include an Artificial Intelligence tag for the honors and MBB plans. Separately, Harvard Extension School offers an online Artificial Intelligence Graduate Certificate and a Data Science and Artificial Intelligence master's degree (ALM in Extension Studies).",
  status: "confirmed_current" as const,
  checkedAt: V,
  evidence: ["src-harvard-cs-requirements", "src-harvard-ext-ai-cert", "src-harvard-ext-dsai-degree"],
  caveat:
    "Absence of evidence on these pages is not proof of absence across all of Harvard. The claim is scoped to the pages retrieved on 2026-10-05 and must be re-verified before any external use.",
};

export const HARVARD_MAPPINGS: HarvardMapping[] = [
  {
    id: "hv-cs50",
    identifier: "CS50",
    title: "Introduction to Computer Science",
    offeringBody: "Harvard College",
    verificationStatus: "confirmed_current",
    sourceId: "src-cs50-fall-2026-syllabus",
    evidence:
      "Fall 2026 syllabus: ten problem sets, three quizzes, eleven sections, final project; weeks cover Scratch, C, Arrays, Algorithms, Memory, Data Structures, Python, SQL, HTML/CSS/JS, Flask. Tagged corecs + programming1 on the CS concentration tags page.",
    mapsToCourses: ["c-cs-foundations", "c-python", "c-databases"],
    tags: ["corecs", "programming1"],
    lastVerified: V,
  },
  {
    id: "hv-cs20",
    identifier: "CS20",
    title: "Discrete Mathematics for Computer Science",
    offeringBody: "Harvard College",
    verificationStatus: "confirmed_current",
    sourceId: "src-harvard-cs-tags",
    evidence: "Listed with tags corecs, formalreasoning, discretemath on the official CS concentration course tags page.",
    mapsToCourses: ["c-cs-foundations", "c-math-foundations"],
    tags: ["formalreasoning", "discretemath"],
    lastVerified: V,
  },
  {
    id: "hv-cs51",
    identifier: "CS51",
    title: "Abstraction and Design in Computation",
    offeringBody: "Harvard College",
    verificationStatus: "confirmed_current",
    sourceId: "src-harvard-cs-tags",
    evidence: "Listed with tags corecs, programming2.",
    mapsToCourses: ["c-python", "c-software-engineering"],
    tags: ["programming2"],
    lastVerified: V,
  },
  {
    id: "hv-cs61",
    identifier: "CS61",
    title: "Systems Programming and Machine Organization",
    offeringBody: "Harvard College",
    verificationStatus: "confirmed_current",
    sourceId: "src-harvard-cs-tags",
    evidence: "Listed with tags corecs, programming2, systems.",
    mapsToCourses: ["c-cs-foundations"],
    tags: ["systems", "programming2"],
    lastVerified: V,
  },
  {
    id: "hv-cs1200",
    identifier: "CS1200 (formerly CS120)",
    title: "Introduction to Algorithms, Computability, and Complexity",
    offeringBody: "Harvard College",
    verificationStatus: "confirmed_current",
    sourceId: "src-harvard-cs-tags",
    evidence: "Listed with tags corecs, formalreasoning, complimitations, algorithms, advancedcs. Renumbering from CS120 confirmed on the same page.",
    mapsToCourses: ["c-cs-foundations"],
    tags: ["algorithms", "complimitations"],
    lastVerified: V,
  },
  {
    id: "hv-cs1240",
    identifier: "CS1240 (formerly CS124)",
    title: "Data Structures and Algorithms",
    offeringBody: "Harvard College",
    verificationStatus: "confirmed_current",
    sourceId: "src-harvard-cs-tags",
    evidence: "Listed with tags corecs, formalreasoning, algorithms, intermediatealgorithms, advancedcs.",
    mapsToCourses: ["c-cs-foundations"],
    tags: ["intermediatealgorithms"],
    lastVerified: V,
  },
  {
    id: "hv-cs1210",
    identifier: "CS1210 (formerly CS121)",
    title: "Introduction to Theoretical Computer Science",
    offeringBody: "Harvard College",
    verificationStatus: "confirmed_current",
    sourceId: "src-harvard-cs-tags",
    evidence: "Listed with tags corecs, formalreasoning, complimitations, advancedcs.",
    mapsToCourses: ["c-cs-foundations"],
    tags: ["complimitations"],
    lastVerified: V,
  },
  {
    id: "hv-stat110",
    identifier: "STAT 110",
    title: "Probability (satisfies the CS concentration probability requirement)",
    offeringBody: "Harvard College",
    verificationStatus: "confirmed_current",
    sourceId: "src-harvard-cs-requirements",
    evidence:
      "Requirements page: 'Probability: One course in probability. Satisfied by Statistics 110, Engineering Sciences 150, Mathematics 154, or a more advanced course.'",
    mapsToCourses: ["c-math-foundations", "c-statistics"],
    lastVerified: V,
  },
  {
    id: "hv-linear-algebra",
    identifier: "MATH 21B / MATH 22A / AM 22A",
    title: "Linear algebra options satisfying the CS concentration requirement",
    offeringBody: "Harvard College",
    verificationStatus: "confirmed_current",
    sourceId: "src-harvard-cs-requirements",
    evidence:
      "Requirements page: 'Linear algebra: One course in linear algebra. Satisfied by Applied Mathematics 22a, Mathematics 21b, Mathematics 22a, Mathematics 23a, Mathematics 25a, Mathematics 55a, or a more advanced course.'",
    mapsToCourses: ["c-math-foundations"],
    lastVerified: V,
  },
  {
    id: "hv-cs1280",
    identifier: "CS1280 / AM122 (formerly CS128)",
    title: "Convex Optimization and Applications in Machine Learning",
    offeringBody: "Harvard College",
    verificationStatus: "confirmed_current",
    sourceId: "src-harvard-cs-tags",
    evidence: "Listed with tags corecs, formalreasoning, advancedcs.",
    mapsToCourses: ["c-math-foundations", "c-ml"],
    lastVerified: V,
  },
  {
    id: "hv-cs1810",
    identifier: "CS1810 (formerly CS181)",
    title: "Machine Learning",
    offeringBody: "Harvard College",
    verificationStatus: "confirmed_current",
    sourceId: "src-harvard-cs-tags",
    evidence: "Listed with tags corecs, computationandtheworld, ai, advancedcs.",
    mapsToCourses: ["c-ml"],
    tags: ["ai"],
    lastVerified: V,
  },
  {
    id: "hv-cs1820",
    identifier: "CS1820 (formerly CS182)",
    title: "Artificial Intelligence",
    offeringBody: "Harvard College",
    verificationStatus: "confirmed_current",
    sourceId: "src-harvard-cs-tags",
    evidence: "Listed with tags corecs, computationandtheworld, ai, advancedcs.",
    mapsToCourses: ["c-ml", "c-agents"],
    tags: ["ai"],
    lastVerified: V,
  },
  {
    id: "hv-cs1840",
    identifier: "CS1840 (formerly CS184)",
    title: "Reinforcement learning",
    offeringBody: "Harvard College",
    verificationStatus: "confirmed_current",
    sourceId: "src-harvard-cs-tags",
    evidence: "Listed with tags corecs, computationandtheworld, ai, advancedcs.",
    mapsToCourses: ["c-research"],
    tags: ["ai"],
    lastVerified: V,
  },
  {
    id: "hv-cs1870",
    identifier: "CS1870 (formerly CS187)",
    title: "Introduction to Computational Linguistics and Natural-language Processing",
    offeringBody: "Harvard College",
    verificationStatus: "confirmed_current",
    sourceId: "src-harvard-cs-tags",
    evidence: "Listed with tags corecs, computationandtheworld, ai, advancedcs. Confirms the identifier discussed in §38.",
    mapsToCourses: ["c-deep-learning", "c-llm"],
    tags: ["ai"],
    lastVerified: V,
  },
  {
    id: "hv-cs1090ab",
    identifier: "CS1090A/B (formerly CS109A/B), also STAT109A/B, AC209A/B",
    title: "Data Science 1 & 2",
    offeringBody: "Harvard College",
    verificationStatus: "confirmed_current",
    sourceId: "src-harvard-cs-tags",
    evidence:
      "Both listed on the tags page. CS1090A note: 'Also advancedcs if approved on a plan of study before 2025-02-01' — i.e. the advanced tag was removed for 2025 and later plans.",
    mapsToCourses: ["c-data-analysis", "c-statistics"],
    lastVerified: V,
  },
  {
    id: "hv-cs1650",
    identifier: "CS1650 (formerly CS165)",
    title: "Data Systems",
    offeringBody: "Harvard College",
    verificationStatus: "confirmed_current",
    sourceId: "src-harvard-cs-tags",
    evidence: "Listed with tags corecs, programming2, systems, advancedcs.",
    mapsToCourses: ["c-databases", "c-data-engineering"],
    lastVerified: V,
  },
  {
    id: "hv-cs1050",
    identifier: "CS1050 (formerly CS105)",
    title: "Privacy and Technology",
    offeringBody: "Harvard College",
    verificationStatus: "confirmed_current",
    sourceId: "src-harvard-cs-tags",
    evidence: "Listed with tags corecs, advancedcs.",
    mapsToCourses: ["c-responsible-ai"],
    lastVerified: V,
  },
  {
    id: "hv-cs1410-1411",
    identifier: "CS1410 / ECE141 and CS1411 / ECE146",
    title: "Computing Hardware; Computer Architecture",
    offeringBody: "Harvard SEAS",
    verificationStatus: "confirmed_current",
    sourceId: "src-harvard-cs-tags",
    evidence: "Both listed with systems + advancedcs tags, cross-listed with ECE numbers.",
    mapsToCourses: ["c-cs-foundations"],
    lastVerified: V,
  },
  {
    id: "hv-ac215",
    identifier: "AC215",
    title: "Topics in Applied Computation: Advanced Practical Data Science, MLOps",
    offeringBody: "Harvard SEAS",
    verificationStatus: "confirmed_current",
    sourceId: "src-harvard-cs-tags",
    evidence: "Listed with tags corecs, advancedcs on the CS concentration tags page.",
    mapsToCourses: ["c-mlops", "c-cloud"],
    lastVerified: V,
  },
  {
    id: "hv-ext-ai-cert",
    identifier: "AI Graduate Certificate (Harvard Extension School)",
    title: "Four online courses: foundations of AI; advanced NLP and ML; deep learning and computer vision; AI ethics, governance and law",
    offeringBody: "Harvard Extension",
    verificationStatus: "confirmed_current",
    sourceId: "src-harvard-ext-ai-cert",
    evidence:
      "Program page lists exactly those four categories, a B-grade minimum in each course, a three-year completion window, and no formal application.",
    mapsToCourses: ["c-ml", "c-deep-learning", "c-llm", "c-responsible-ai"],
    lastVerified: V,
  },
  {
    id: "hv-ext-dsai",
    identifier: "ALM in Extension Studies — Data Science and Artificial Intelligence",
    title: "Harvard Extension master's degree (12 courses, 11 online + one 3-week on-campus)",
    offeringBody: "Harvard Extension",
    verificationStatus: "confirmed_current",
    sourceId: "src-harvard-ext-dsai-degree",
    evidence:
      "Program page lists example core courses (Data Mining; Dynamic Modeling and Forecasting in Big Data; Ethics, Governance and Laws of Data Science, AI and Creative Systems; Introduction to NLP; Data Engineering for Analytics) and electives including Deep Learning and Foundations of Large Language Models. Admission via CSCI 101 and CSCI 106.",
    mapsToCourses: ["c-data-engineering", "c-llm", "c-responsible-ai", "c-research"],
    lastVerified: V,
  },
  // ---- Identifiers discussed in §38 that were NOT confirmed in this pass ----
  {
    id: "hv-csci-e222",
    identifier: "CSCI E-222",
    title: "Foundations of Large Language Models (identifier unconfirmed)",
    offeringBody: "Harvard Extension",
    verificationStatus: "likely_not_verified",
    sourceId: "src-harvard-ext-dsai-degree",
    evidence:
      "A course titled 'Foundations of Large Language Models' appears as an example elective on the DSAI master's page, but the CSCI E-222 number was not shown there and was not confirmed in the course catalog during this pass.",
    mapsToCourses: ["c-llm"],
    lastVerified: V,
  },
  {
    id: "hv-csci-e25-e89-e104",
    identifier: "CSCI E-25 / CSCI E-89 / CSCI E-104",
    title: "Extension computer-vision / deep-learning identifiers (unconfirmed)",
    offeringBody: "Harvard Extension",
    verificationStatus: "likely_not_verified",
    sourceId: "src-harvard-ext-ai-cert",
    evidence:
      "Not located on the retrieved Extension pages. The certificate page states that course options vary by term and must be checked in the DCE Course Search platform.",
    mapsToCourses: ["c-deep-learning"],
    lastVerified: V,
  },
  {
    id: "hv-apcomp215",
    identifier: "APCOMP 215",
    title: "Advanced Practical Data Science / MLOps (cross-listing unconfirmed)",
    offeringBody: "Harvard SEAS",
    verificationStatus: "likely_not_verified",
    sourceId: "src-harvard-cs-tags",
    evidence:
      "AC215 with the title 'Topics in Applied Computation: Advanced Practical Data Science, MLOps' is confirmed on the tags page; the APCOMP 215 form of the identifier was not shown there.",
    mapsToCourses: ["c-mlops"],
    lastVerified: V,
  },
  {
    id: "hv-math55a",
    identifier: "MATH 55A",
    title: "Listed only as one option satisfying linear algebra — not recommended here",
    offeringBody: "Harvard College",
    verificationStatus: "confirmed_current",
    sourceId: "src-harvard-cs-requirements",
    evidence: "Appears in the official list of courses satisfying the linear algebra requirement.",
    mapsToCourses: ["c-math-foundations"],
    lastVerified: V,
  },
  {
    id: "hv-ece50-152-155-156",
    identifier: "ECE50 / ECE152 / ECE155 / ECE156",
    title: "ECE identifiers discussed in §38 (unconfirmed)",
    offeringBody: "Harvard SEAS",
    verificationStatus: "not_found",
    sourceId: "src-harvard-cs-tags",
    evidence:
      "Not present on the CS concentration tags page. The confirmed hardware-adjacent cross-listings there are CS1410/ECE141, CS1411/ECE146 and CS1480/ECE148. The SEAS ECE catalog was not retrieved in this pass.",
    mapsToCourses: ["c-cs-foundations"],
    lastVerified: V,
  },
];

export const HARVARD_GAP_MATRIX = [
  {
    area: "Programming",
    original: "Module 1 Python Programming (Python-only)",
    harvardAdds: "CS50 adds C, memory, pointers, compilation; CS51 adds abstraction/design; CS61 adds machine organization",
    decision: "Add a C + systems layer alongside Python. Python depth is unchanged.",
    status: "design_decision" as const,
  },
  {
    area: "Algorithms & theory",
    original: "Linear/binary search, bubble sort, recursion inside Module 1 session 4",
    harvardAdds: "CS1200 (algorithms, computability, complexity), CS1240 (data structures & algorithms), CS1210 (theory)",
    decision: "Add a dedicated algorithms + complexity course. Original items stay where they are and are revisited (spiral, §101).",
    status: "design_decision" as const,
  },
  {
    area: "Mathematics",
    original: "Module 2: linear algebra, calculus/optimization, statistics, probability (5 sessions)",
    harvardAdds: "Dedicated linear algebra course, STAT 110 probability, CS1280 convex optimization",
    decision: "Keep Module 2 intact as the spine; add depth courses afterwards rather than replacing it.",
    status: "design_decision" as const,
  },
  {
    area: "Machine learning",
    original: "Module 6 (12 sessions, applied scikit-learn)",
    harvardAdds: "CS1810 Machine Learning, CS1820 AI, CS1840 Reinforcement Learning",
    decision: "Original applied ML first, theory layer second (§41 layered depth).",
    status: "design_decision" as const,
  },
  {
    area: "Data systems",
    original: "Module 5 SQL, scraping, ETL",
    harvardAdds: "CS1650 Data Systems (indexing, concurrency, recovery)",
    decision: "Keep BeautifulSoup/Regex/Selenium/ETL; add systems-level database internals as ADVANCED.",
    status: "design_decision" as const,
  },
  {
    area: "Excel & Power BI",
    original: "Module 4 (4 sessions)",
    harvardAdds: "No Harvard equivalent found in the CS concentration",
    decision: "Preserved as an explicit Industry/business analytics layer, labelled Original Curriculum. Not deleted (§69).",
    status: "design_decision" as const,
  },
  {
    area: "MLOps / production AI",
    original: "Module 8 (FastAPI, Streamlit, Docker, CI/CD)",
    harvardAdds: "AC215 Advanced Practical Data Science, MLOps",
    decision: "Original tools kept; full lifecycle (§136) added as an Industry Extension course.",
    status: "design_decision" as const,
  },
  {
    area: "LLMs / RAG / agents",
    original: "Module 7 session 6 (Transformers, RAG, vector DBs, agents)",
    harvardAdds: "Extension 'Foundations of Large Language Models'; CS1870 NLP",
    decision: "Original topics preserved; RAG/GraphRAG/agents expanded into their own Industry Extension courses (§137, §138).",
    status: "design_decision" as const,
  },
];
