import type { ProjectSpec } from "./types";

/**
 * §171 ORIGINAL 21+ PROJECT CATALOG — all 21 preserved, in the original order,
 * placed on the §170 project ladder and given a §172 data policy, §173 submission
 * architecture and §174 definition of done.
 *
 * Dataset links were NOT re-fetched during this build pass, so every recommended
 * source is marked `likely_not_verified`: the student must confirm the link,
 * licence and terms before use, and the UI shows that status.
 */

const MUST_RECORD = [
  "source URL",
  "licence / terms of use",
  "acquisition date",
  "version or snapshot id",
  "schema",
  "data dictionary",
  "known limitations",
  "bias risks",
  "leakage risks",
  "reproducibility notes",
];

const dod = (title: string, items: string[]) => ({ id: title.toLowerCase().replace(/[^a-z0-9]+/g, "-"), title, definitionOfDone: items });

export const PROJECTS: ProjectSpec[] = [
  {
    id: "pj-skin-disease",
    title: "Skin Disease Prediction",
    ladderLevel: 6,
    ladderTrack: "CV/NLP",
    sourceCategory: "Original Curriculum",
    problem: "Classify dermatoscopic images into diagnostic categories, with explicit handling of class imbalance and an honest statement of clinical limitations.",
    dataPolicy: {
      recommendedSources: [
        { name: "HAM10000 dermatoscopic image dataset (Harvard Dataverse)", url: "https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/DBW86T", verificationStatus: "likely_not_verified" },
      ],
      mustRecord: MUST_RECORD,
      syntheticAllowed: false,
    },
    requirements: ["Transfer learning from a pretrained backbone", "Per-class metrics, not just accuracy", "Calibration check", "Explicit non-clinical-use statement"],
    acceptanceCriteria: ["Per-class recall reported for every class", "Confusion matrix analysed in writing", "Model card includes intended use and prohibited use"],
    milestones: [
      dod("Data audit", ["Licence recorded", "Class distribution documented", "Duplicate/leakage check across patients"]),
      dod("Baseline", ["Majority-class and simple CNN baselines recorded before transfer learning"]),
      dod("Model + evaluation", ["Per-class metrics", "Error analysis on 20 misclassified images"]),
      dod("Model card", ["Limitations, bias risks and prohibited uses written"]),
    ],
    skills: ["sk-cv", "sk-dl-training", "sk-ml-workflow"],
    careerRoles: ["role-navisoft"],
    evidenceExpected: ["repository", "model card", "error analysis", "metrics table"],
    cvClass: "Portfolio Project",
  },
  {
    id: "pj-face-recognition",
    title: "Face Recognition / Detection / Verification",
    ladderLevel: 6,
    ladderTrack: "CV/NLP",
    sourceCategory: "Original Curriculum",
    problem: "Build detection, recognition and verification as three distinct tasks with three distinct evaluations, and address the privacy and consent questions before writing code.",
    dataPolicy: {
      recommendedSources: [{ name: "Labeled Faces in the Wild (LFW)", url: "https://vis-www.cs.umass.edu/lfw/", verificationStatus: "likely_not_verified" }],
      mustRecord: [...MUST_RECORD, "consent basis", "demographic composition"],
      syntheticAllowed: false,
    },
    requirements: ["Separate detection / recognition / verification pipelines", "Verification evaluated with ROC and a defended threshold", "Written privacy analysis"],
    acceptanceCriteria: ["Demographic performance breakdown reported", "Threshold justified by error cost", "Privacy/consent section completed"],
    milestones: [dod("Privacy analysis", ["Lawful basis and consent documented before any data use"]), dod("Pipelines", ["Three tasks implemented and separately evaluated"]), dod("Fairness review", ["Performance disaggregated across available groups"])],
    skills: ["sk-cv", "sk-security"],
    careerRoles: ["role-navisoft"],
    evidenceExpected: ["repository", "ROC curve", "privacy analysis"],
    cvClass: "Portfolio Project",
  },
  {
    id: "pj-text-classification",
    title: "Text Classification",
    ladderLevel: 6,
    ladderTrack: "CV/NLP",
    sourceCategory: "Original Curriculum",
    problem: "Classify real text with a TF-IDF baseline, an embedding model and a transformer, and justify which one you would actually ship.",
    dataPolicy: {
      recommendedSources: [{ name: "UCI SMS Spam Collection", url: "https://archive.ics.uci.edu/dataset/228/sms+spam+collection", verificationStatus: "likely_not_verified" }],
      mustRecord: MUST_RECORD,
      syntheticAllowed: false,
    },
    requirements: ["Three models compared on identical splits", "Cost/latency comparison", "Error analysis by class"],
    acceptanceCriteria: ["Ship recommendation defended with accuracy, latency and cost", "Baseline beats a trivial rule"],
    milestones: [dod("Baseline", ["TF-IDF + linear model recorded first"]), dod("Comparison", ["Identical splits across all three models"]), dod("Decision memo", ["Ship recommendation written with trade-offs"])],
    skills: ["sk-nlp", "sk-classification"],
    careerRoles: ["role-navisoft", "role-nuwave"],
    evidenceExpected: ["repository", "comparison table", "decision memo"],
    cvClass: "Skill Evidence",
  },
  {
    id: "pj-stock-prediction",
    title: "Stock Market Prediction",
    ladderLevel: 5,
    ladderTrack: "Deep learning",
    sourceCategory: "Original Curriculum",
    problem: "Forecast a financial series honestly: strict time-ordered splits, a persistence baseline, and a written statement of why most published results are invalid.",
    dataPolicy: {
      recommendedSources: [{ name: "Public market data via a provider whose terms allow it (check before use)", url: "https://www.nasdaq.com/market-activity", verificationStatus: "likely_not_verified" }],
      mustRecord: [...MUST_RECORD, "exact time range", "survivorship bias assessment"],
      syntheticAllowed: false,
    },
    requirements: ["Walk-forward validation", "Persistence baseline", "No feature computed with future information"],
    acceptanceCriteria: ["Model compared against persistence baseline", "Lookahead audit documented", "Conclusion states whether the model beats the baseline — including if it does not"],
    milestones: [dod("Split design", ["Time-ordered split proven to exclude future data"]), dod("Baseline", ["Persistence baseline metric recorded"]), dod("Honest conclusion", ["Result reported even if negative"])],
    skills: ["sk-sequence", "sk-statistics"],
    careerRoles: ["role-navisoft"],
    evidenceExpected: ["repository", "walk-forward results", "lookahead audit"],
    cvClass: "Skill Evidence",
  },
  {
    id: "pj-sign-language",
    title: "Sign Language Classifier",
    ladderLevel: 6,
    ladderTrack: "CV/NLP",
    sourceCategory: "Original Curriculum",
    problem: "Classify sign-language gestures from images, with augmentation chosen for the domain rather than copied from a tutorial.",
    dataPolicy: {
      recommendedSources: [{ name: "Sign Language MNIST (Kaggle)", url: "https://www.kaggle.com/datasets/datamunge/sign-language-mnist", verificationStatus: "likely_not_verified" }],
      mustRecord: MUST_RECORD,
      syntheticAllowed: false,
    },
    requirements: ["Domain-appropriate augmentation (no horizontal flips where handedness matters)", "Per-class analysis", "Live-inference demo"],
    acceptanceCriteria: ["Augmentation choices justified in writing", "Confusable class pairs identified"],
    milestones: [dod("Augmentation rationale", ["Each transform justified or rejected"]), dod("Model", ["Per-class metrics reported"]), dod("Demo", ["Inference runs on a new image end to end"])],
    skills: ["sk-cv"],
    careerRoles: ["role-navisoft"],
    evidenceExpected: ["repository", "demo", "augmentation rationale"],
    cvClass: "Skill Evidence",
  },
  {
    id: "pj-object-detection",
    title: "Real-time Object Detection",
    ladderLevel: 6,
    ladderTrack: "CV/NLP",
    sourceCategory: "Original Curriculum",
    problem: "Run detection at interactive frame rates and report the accuracy/latency trade-off on measured hardware.",
    dataPolicy: {
      recommendedSources: [{ name: "COCO dataset", url: "https://cocodataset.org/", verificationStatus: "likely_not_verified" }],
      mustRecord: MUST_RECORD,
      syntheticAllowed: false,
    },
    requirements: ["Measured FPS on named hardware", "mAP reported at stated IoU", "Trade-off curve across model sizes"],
    acceptanceCriteria: ["Hardware named", "mAP and FPS reported together, never separately"],
    milestones: [dod("Measurement harness", ["FPS measured, not estimated"]), dod("Trade-off", ["At least two model sizes compared"])],
    skills: ["sk-cv", "sk-observability"],
    careerRoles: ["role-navisoft"],
    evidenceExpected: ["repository", "latency measurements", "demo video"],
    cvClass: "Portfolio Project",
  },
  {
    id: "pj-breast-cancer",
    title: "Breast Cancer Detection",
    ladderLevel: 4,
    ladderTrack: "Classical ML",
    sourceCategory: "Original Curriculum",
    problem: "Classify tumours from the Wisconsin diagnostic features, with a threshold chosen from the asymmetric cost of a false negative.",
    dataPolicy: {
      recommendedSources: [{ name: "UCI Breast Cancer Wisconsin (Diagnostic)", url: "https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic", verificationStatus: "likely_not_verified" }],
      mustRecord: MUST_RECORD,
      syntheticAllowed: false,
    },
    requirements: ["Recall-prioritised threshold with written justification", "Calibration curve", "Clear non-clinical-use statement"],
    acceptanceCriteria: ["Threshold defended numerically", "Calibration assessed", "Limitations written"],
    milestones: [dod("Cost analysis", ["Cost of FN vs FP stated before modelling"]), dod("Model + calibration", ["Calibration plot produced"]), dod("Model card", ["Prohibited uses stated"])],
    skills: ["sk-classification", "sk-ml-workflow"],
    careerRoles: ["role-navisoft"],
    evidenceExpected: ["repository", "calibration plot", "model card"],
    cvClass: "Skill Evidence",
  },
  {
    id: "pj-brain-tumor",
    title: "Brain Tumor Detection",
    ladderLevel: 6,
    ladderTrack: "CV/NLP",
    sourceCategory: "Original Curriculum",
    problem: "Detect tumours in MRI images, with patient-level splits so that slices from one patient never appear in both train and test.",
    dataPolicy: {
      recommendedSources: [{ name: "Brain MRI public dataset (verify licence before use)", url: "https://www.cancerimagingarchive.net/", verificationStatus: "likely_not_verified" }],
      mustRecord: [...MUST_RECORD, "patient-level grouping"],
      syntheticAllowed: false,
    },
    requirements: ["Patient-level grouped splits", "Sensitivity prioritised", "Explainability overlay (e.g. activation maps) with stated limits"],
    acceptanceCriteria: ["Grouping proven — no patient crosses the split", "Sensitivity reported with confidence interval"],
    milestones: [dod("Split integrity", ["Patient grouping verified programmatically"]), dod("Model", ["Sensitivity and specificity reported"]), dod("Explainability", ["Overlay produced with a caveat about what it does not prove"])],
    skills: ["sk-cv", "sk-ml-workflow"],
    careerRoles: ["role-navisoft"],
    evidenceExpected: ["repository", "split verification script", "model card"],
    cvClass: "Portfolio Project",
  },
  {
    id: "pj-gan-images",
    title: "Image Generation using GANs",
    ladderLevel: 5,
    ladderTrack: "Deep learning",
    sourceCategory: "Original Curriculum",
    problem: "Train a GAN, diagnose mode collapse, and evaluate with a metric you can defend rather than by picking the nicest samples.",
    dataPolicy: {
      recommendedSources: [{ name: "CelebA or a licensed alternative (check terms)", url: "https://mmlab.ie.cuhk.edu.hk/projects/CelebA.html", verificationStatus: "likely_not_verified" }],
      mustRecord: [...MUST_RECORD, "synthetic-output labelling policy"],
      syntheticAllowed: true,
    },
    requirements: ["Training stability log", "Mode-collapse diagnosis", "Quantitative evaluation, not cherry-picked samples", "Generated images labelled as synthetic"],
    acceptanceCriteria: ["Failure modes documented", "Random (not selected) sample grid shown"],
    milestones: [dod("Stability log", ["Discriminator/generator losses tracked and interpreted"]), dod("Evaluation", ["Quantitative metric reported with its known weaknesses"])],
    skills: ["sk-dl-training"],
    careerRoles: [],
    evidenceExpected: ["repository", "training log analysis", "random sample grid"],
    cvClass: "Skill Evidence",
  },
  {
    id: "pj-library-management",
    title: "Library Management System",
    ladderLevel: 1,
    ladderTrack: "Python engineering",
    sourceCategory: "Original Curriculum",
    problem: "Build a small system with real object modelling, persistence, validation and tests — the project where software engineering habits are formed.",
    dataPolicy: { recommendedSources: [], mustRecord: ["schema", "test fixtures are labelled as test data"], syntheticAllowed: true },
    requirements: ["Domain model with classes", "Persistence", "Input validation", "Unit tests", "CLI or simple interface"],
    acceptanceCriteria: ["Tests pass from a clean checkout", "Invalid input produces a useful error, never a stack trace", "README lets a stranger run it"],
    milestones: [dod("Domain model", ["Classes and invariants written down"]), dod("Persistence + validation", ["Round-trip test passes"]), dod("Tests + README", ["Clean-checkout run documented"])],
    skills: ["sk-python-oop", "sk-testing"],
    careerRoles: [],
    evidenceExpected: ["repository", "test suite"],
    cvClass: "Practice Only",
  },
  {
    id: "pj-uber-analysis",
    title: "Uber Data Analysis",
    ladderLevel: 2,
    ladderTrack: "Data analysis",
    sourceCategory: "Original Curriculum",
    problem: "Analyse real trip data: temporal patterns, geography, demand peaks — and state what the data cannot tell you.",
    dataPolicy: {
      recommendedSources: [{ name: "NYC TLC Trip Record Data", url: "https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page", verificationStatus: "likely_not_verified" }],
      mustRecord: MUST_RECORD,
      syntheticAllowed: false,
    },
    requirements: ["Reproducible notebook or script", "Data dictionary", "At least three findings with uncertainty stated"],
    acceptanceCriteria: ["Another person reruns it and gets identical numbers", "Each finding has a limitation"],
    milestones: [dod("Provenance", ["Source, licence and snapshot recorded"]), dod("Analysis", ["Findings with uncertainty"]), dod("Review", ["Code review completed"])],
    skills: ["sk-pandas", "sk-eda", "sk-visualisation"],
    careerRoles: ["role-navisoft"],
    evidenceExpected: ["repository", "report"],
    cvClass: "Skill Evidence",
  },
  {
    id: "pj-superstore-dashboard",
    title: "Superstore Data Analysis Dashboard",
    ladderLevel: 2,
    ladderTrack: "Data analysis",
    sourceCategory: "Original Curriculum",
    problem: "Turn a sales dataset into a dashboard that answers specific business questions, with a defined refresh path.",
    dataPolicy: {
      recommendedSources: [{ name: "Sample Superstore dataset (Tableau public sample)", url: "https://public.tableau.com/app/learn/sample-data", verificationStatus: "likely_not_verified" }],
      mustRecord: MUST_RECORD,
      syntheticAllowed: false,
    },
    requirements: ["Questions defined before charts", "Refreshable pipeline", "Accessible colour choices"],
    acceptanceCriteria: ["Every chart answers a written question", "Refresh procedure documented"],
    milestones: [dod("Questions", ["Business questions written and signed off"]), dod("Model", ["Data model and relationships built"]), dod("Dashboard", ["Refresh tested"])],
    skills: ["sk-excel-powerbi", "sk-visualisation"],
    careerRoles: ["role-navisoft"],
    evidenceExpected: ["dashboard file", "screenshots", "question list"],
    cvClass: "Skill Evidence",
  },
  {
    id: "pj-hr-dashboard",
    title: "HR Dashboard",
    ladderLevel: 2,
    ladderTrack: "Data analysis",
    sourceCategory: "Original Curriculum",
    problem: "Build an HR analytics dashboard, including an explicit discussion of which metrics are ethical to display about individuals.",
    dataPolicy: {
      recommendedSources: [{ name: "IBM HR Analytics Attrition dataset (Kaggle)", url: "https://www.kaggle.com/datasets/pavansubhasht/ibm-hr-analytics-attrition-dataset", verificationStatus: "likely_not_verified" }],
      mustRecord: [...MUST_RECORD, "individual-privacy assessment"],
      syntheticAllowed: false,
    },
    requirements: ["Aggregate-level reporting by default", "Privacy note", "Attrition analysis with uncertainty"],
    acceptanceCriteria: ["No individual is identifiable in the delivered view", "Privacy note written"],
    milestones: [dod("Privacy design", ["Aggregation thresholds defined"]), dod("Dashboard", ["Metrics implemented"]), dod("Review", ["Ethical review written"])],
    skills: ["sk-excel-powerbi"],
    careerRoles: [],
    evidenceExpected: ["dashboard file", "privacy note"],
    cvClass: "Skill Evidence",
  },
  {
    id: "pj-bank-loan",
    title: "Bank Loan Data Analysis",
    ladderLevel: 3,
    ladderTrack: "SQL/data pipeline",
    sourceCategory: "Original Curriculum",
    problem: "Analyse lending data with explicit attention to fairness: which features are proxies for protected attributes?",
    dataPolicy: {
      recommendedSources: [{ name: "UCI Statlog (German Credit Data)", url: "https://archive.ics.uci.edu/dataset/144/statlog+german+credit+data", verificationStatus: "likely_not_verified" }],
      mustRecord: [...MUST_RECORD, "protected attributes and proxies"],
      syntheticAllowed: false,
    },
    requirements: ["Proxy-variable analysis", "Disaggregated metrics", "SQL-based aggregation layer"],
    acceptanceCriteria: ["At least two proxy risks identified and discussed", "Metrics disaggregated"],
    milestones: [dod("Fairness scoping", ["Protected attributes and proxies listed"]), dod("Analysis", ["Disaggregated results"]), dod("Write-up", ["Fairness discussion completed"])],
    skills: ["sk-sql", "sk-pandas", "sk-security"],
    careerRoles: ["role-navisoft"],
    evidenceExpected: ["repository", "SQL scripts", "fairness analysis"],
    cvClass: "Skill Evidence",
  },
  {
    id: "pj-sales-database",
    title: "Sales Database",
    ladderLevel: 3,
    ladderTrack: "SQL/data pipeline",
    sourceCategory: "Original Curriculum",
    problem: "Design and build a normalised sales database with constraints, indexes and analytical queries that run efficiently.",
    dataPolicy: { recommendedSources: [], mustRecord: ["schema", "seed data provenance", "test data clearly labelled"], syntheticAllowed: true },
    requirements: ["3NF schema with constraints", "Indexes justified by query plans", "Window-function reporting queries"],
    acceptanceCriteria: ["Plans shown before and after indexing", "Constraints prevent at least three invalid states"],
    milestones: [dod("Schema", ["ERD and DDL complete with constraints"]), dod("Queries", ["Reporting queries written"]), dod("Performance", ["Plans compared before/after indexes"])],
    skills: ["sk-sql"],
    careerRoles: ["role-navisoft"],
    evidenceExpected: ["repository", "DDL", "query plans"],
    cvClass: "Technical Artifact",
  },
  {
    id: "pj-credit-fraud",
    title: "Credit Card Fraud Detection",
    ladderLevel: 4,
    ladderTrack: "Classical ML",
    sourceCategory: "Original Curriculum",
    problem: "Detect fraud under extreme class imbalance, with a threshold derived from the cost of each error type and an estimate of production precision.",
    dataPolicy: {
      recommendedSources: [{ name: "Credit Card Fraud Detection (ULB, Kaggle)", url: "https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud", verificationStatus: "likely_not_verified" }],
      mustRecord: [...MUST_RECORD, "base rate in data vs assumed production base rate"],
      syntheticAllowed: false,
    },
    requirements: ["Precision-recall analysis", "Cost-based threshold", "Production base-rate adjustment", "Drift monitoring plan"],
    acceptanceCriteria: ["Expected production precision estimated and explained", "Threshold defended in currency, not in F1"],
    milestones: [dod("Cost model", ["Cost per FP and FN agreed before modelling"]), dod("Model", ["PR curve and cost curve produced"]), dod("Monitoring plan", ["Drift signals and thresholds defined"])],
    skills: ["sk-classification", "sk-ensembles", "sk-mlops"],
    careerRoles: ["role-navisoft", "role-nuwave"],
    evidenceExpected: ["repository", "cost curve", "monitoring plan"],
    cvClass: "Portfolio Project",
  },
  {
    id: "pj-titanic",
    title: "Titanic Prediction",
    ladderLevel: 4,
    ladderTrack: "Classical ML",
    sourceCategory: "Original Curriculum",
    problem: "The canonical first classification problem — used here to practise disciplined validation and honest reporting, not leaderboard chasing.",
    dataPolicy: {
      recommendedSources: [{ name: "Titanic - Machine Learning from Disaster (Kaggle)", url: "https://www.kaggle.com/competitions/titanic", verificationStatus: "likely_not_verified" }],
      mustRecord: MUST_RECORD,
      syntheticAllowed: false,
    },
    requirements: ["Cross-validated comparison", "Feature engineering justified", "No leaderboard overfitting"],
    acceptanceCriteria: ["Validation protocol documented", "Gap between CV and holdout explained"],
    milestones: [dod("Protocol", ["Validation scheme fixed in advance"]), dod("Models", ["At least three compared on identical folds"])],
    skills: ["sk-classification", "sk-ml-workflow"],
    careerRoles: [],
    evidenceExpected: ["repository", "validation report"],
    cvClass: "Practice Only",
  },
  {
    id: "pj-house-pricing",
    title: "House Pricing Prediction",
    ladderLevel: 4,
    ladderTrack: "Classical ML",
    sourceCategory: "Original Curriculum",
    problem: "Predict prices with interpretable regression, residual diagnostics and an honest discussion of distribution shift over time.",
    dataPolicy: {
      recommendedSources: [{ name: "Ames Housing dataset", url: "https://www.openintro.org/data/index.php?data=ames", verificationStatus: "likely_not_verified" }],
      mustRecord: MUST_RECORD,
      syntheticAllowed: false,
    },
    requirements: ["Residual analysis", "Interpretable coefficients or feature importances", "Temporal shift discussion"],
    acceptanceCriteria: ["Residual plots analysed in writing", "At least one coefficient interpreted in business units"],
    milestones: [dod("Baseline", ["Simple linear baseline recorded"]), dod("Diagnostics", ["Residual analysis written"]), dod("Interpretation", ["Coefficients explained with caveats"])],
    skills: ["sk-regression"],
    careerRoles: [],
    evidenceExpected: ["repository", "residual analysis"],
    cvClass: "Skill Evidence",
  },
  {
    id: "pj-chatbot",
    title: "Chatbot",
    ladderLevel: 7,
    ladderTrack: "LLM/RAG",
    sourceCategory: "Original Curriculum",
    problem: "Build a chatbot that is scoped, evaluated and safe — including refusal behaviour, logging and a cost model.",
    dataPolicy: { recommendedSources: [], mustRecord: ["conversation logging policy", "PII handling", "retention period"], syntheticAllowed: true },
    requirements: ["Written scope and non-goals", "Evaluation set created before launch", "Refusal behaviour", "Cost and latency measured", "Prompt injection test"],
    acceptanceCriteria: ["Evaluation set of at least 30 cases", "Documented refusal on out-of-scope input", "Cost per conversation estimated"],
    milestones: [
      dod("Scope", ["Users, goals, non-goals written"]),
      dod("Evaluation set", ["Cases written before implementation"]),
      dod("Implementation", ["Logging, refusal, limits in place"]),
      dod("Security", ["Injection attempts tested and documented"]),
    ],
    skills: ["sk-transformers", "sk-llm-eval", "sk-security"],
    careerRoles: ["role-nuwave"],
    evidenceExpected: ["repository", "evaluation set", "cost analysis", "security notes"],
    cvClass: "Portfolio Project",
  },
  {
    id: "pj-document-summarisation",
    title: "Document Summarization",
    ladderLevel: 7,
    ladderTrack: "LLM/RAG",
    sourceCategory: "Original Curriculum",
    problem: "Summarise long documents with a faithfulness evaluation — the hard part is proving the summary did not invent anything.",
    dataPolicy: {
      recommendedSources: [{ name: "Public documents whose licence permits processing (verify per document)", url: "https://www.govinfo.gov/", verificationStatus: "likely_not_verified" }],
      mustRecord: MUST_RECORD,
      syntheticAllowed: false,
    },
    requirements: ["Chunking strategy for long inputs", "Faithfulness check against source", "Human review of a sample"],
    acceptanceCriteria: ["Faithfulness measured, not assumed", "At least 20 summaries human-reviewed with findings recorded"],
    milestones: [dod("Strategy", ["Chunking and aggregation approach documented"]), dod("Faithfulness", ["Measurement method implemented"]), dod("Review", ["Human review sample completed"])],
    skills: ["sk-nlp", "sk-llm-eval"],
    careerRoles: ["role-nuwave"],
    evidenceExpected: ["repository", "faithfulness report"],
    cvClass: "Portfolio Project",
  },
  {
    id: "pj-rag-system",
    title: "RAG System",
    ladderLevel: 9,
    ladderTrack: "Production AI",
    sourceCategory: "Original Curriculum",
    problem: "A production-shaped retrieval system: ingestion, hybrid search, grounding, citations, evaluation, monitoring, access control and cost control.",
    dataPolicy: {
      recommendedSources: [{ name: "A corpus you are permitted to index (own documents or an open-licensed collection)", url: "https://www.gutenberg.org/", verificationStatus: "likely_not_verified" }],
      mustRecord: [...MUST_RECORD, "per-document permission scope"],
      syntheticAllowed: false,
    },
    requirements: [
      "Ingestion pipeline with provenance",
      "Hybrid retrieval",
      "Permission filtering in the query, not the prompt",
      "Separate retrieval and generation metrics",
      "Citations that resolve to real source locations",
      "Latency and cost dashboard",
      "Deployed and reachable",
    ],
    acceptanceCriteria: [
      "Retrieval metric and generation metric both reported",
      "A user cannot retrieve a document outside their scope",
      "Every answer carries a citation a human can open",
      "Documented behaviour when retrieval returns nothing",
    ],
    milestones: [
      dod("Ingestion", ["Provenance and permissions stored per chunk"]),
      dod("Retrieval", ["Hybrid search with measured retrieval metrics"]),
      dod("Generation + grounding", ["Citations verified, refusal implemented"]),
      dod("Production", ["Deployed, monitored, cost tracked, rollback defined"]),
    ],
    skills: ["sk-rag", "sk-llm-eval", "sk-security", "sk-observability", "sk-mlops"],
    careerRoles: ["role-nuwave"],
    evidenceExpected: ["repository", "deployment URL", "evaluation report", "architecture diagram", "monitoring evidence"],
    cvClass: "Signature Project",
  },
];

/** §170 — the ladder itself, so the UI can show progression rather than a flat list. */
export const PROJECT_LADDER = [
  { level: 1, track: "Python engineering" },
  { level: 2, track: "Data analysis" },
  { level: 3, track: "SQL/data pipeline" },
  { level: 4, track: "Classical ML" },
  { level: 5, track: "Deep learning" },
  { level: 6, track: "CV/NLP" },
  { level: 7, track: "LLM/RAG" },
  { level: 8, track: "Agents" },
  { level: 9, track: "Production AI" },
  { level: 10, track: "Research" },
];
