import type { SourceRecord } from "./types";

/**
 * Source registry (§184). Every record below was retrieved during the build
 * research pass. `extract` contains statements actually present on the page at
 * `accessedAt`. Records that were NOT fetched are marked `likely_not_verified`
 * and carry no extract — they must never be cited as proof of a fact.
 */
const RETRIEVED = "2026-10-05";

export const SOURCES: SourceRecord[] = [
  {
    sourceId: "src-harvard-cs-requirements",
    url: "https://csadvising.seas.harvard.edu/concentration/requirements/",
    title: "Concentration Requirements :: Harvard CS Concentration",
    publisher: "Harvard SEAS — CS Advising",
    sourceType: "official_catalog",
    accessedAt: RETRIEVED,
    verificationStatus: "confirmed_current",
    extract: [
      "Basic plan: 9 core computer science courses are required, covering programming, formal reasoning, systems, computation and the world, and advanced computer science.",
      "A strict majority of the core courses must carry Harvard CS course numbers.",
      "Mathematical preparation is 2–5 courses, including early calculus as needed, one linear algebra course, and one probability course.",
      "Linear algebra is satisfied by Applied Mathematics 22a, Mathematics 21b, 22a, 23a, 25a, 55a, or a more advanced course.",
      "Probability is satisfied by Statistics 110, Engineering Sciences 150, Mathematics 154, or a more advanced course.",
      "Formal Reasoning requires 3 courses; Systems 1 course; Computation and the World 1 course; Advanced Computer Science (CS 1000+) 4 courses for the basic plan.",
      "Honors plan requires 11 core courses including an Intermediate Algorithms course and an Artificial Intelligence course.",
    ],
    notes:
      "Primary evidence that Harvard College offers a Computer Science concentration with these tag requirements. It is NOT evidence of a standalone 'AI Engineering' bachelor's degree — no such degree was found on Harvard's official pages during this pass.",
  },
  {
    sourceId: "src-harvard-cs-tags",
    url: "https://csadvising.seas.harvard.edu/concentration/courses/tags/",
    title: "Course Tags :: Harvard CS Concentration",
    publisher: "Harvard SEAS — CS Advising",
    sourceType: "official_catalog",
    accessedAt: RETRIEVED,
    verificationStatus: "confirmed_current",
    extract: [
      "CS20 Discrete Mathematics for Computer Science — tags: corecs, formalreasoning, discretemath.",
      "CS50 Introduction to Computer Science — tags: corecs, programming1. Mutually exclusive with CS32 and CSCI S-111.",
      "CS51 Abstraction and Design in Computation — tags: corecs, programming2.",
      "CS61 Systems Programming and Machine Organization — tags: corecs, programming2, systems.",
      "CS1200 (formerly CS120) Introduction to Algorithms, Computability, and Complexity — tags: formalreasoning, complimitations, algorithms, advancedcs.",
      "CS1210 (formerly CS121) Introduction to Theoretical Computer Science — tags: formalreasoning, complimitations, advancedcs.",
      "CS1240 (formerly CS124) Data Structures and Algorithms — tags: formalreasoning, algorithms, intermediatealgorithms, advancedcs.",
      "CS1280 / AM122 (formerly CS128) Convex Optimization and Applications in Machine Learning — tags: formalreasoning, advancedcs.",
      "CS1650 (formerly CS165) Data Systems — tags: programming2, systems, advancedcs.",
      "CS1810 (formerly CS181) Machine Learning — tags: computationandtheworld, ai, advancedcs.",
      "CS1820 (formerly CS182) Artificial Intelligence — tags: computationandtheworld, ai, advancedcs.",
      "CS1840 (formerly CS184) Reinforcement learning — tags: computationandtheworld, ai, advancedcs.",
      "CS1870 (formerly CS187) Introduction to Computational Linguistics and Natural-language Processing — tags: computationandtheworld, ai, advancedcs.",
      "CS1090A / STAT109A / AC209A (formerly CS109A) Data Science 1: Introduction to Data Science.",
      "CS1090B / STAT109B / AC209B (formerly CS109B) Data Science 2: Advanced Topics in Data Science.",
      "CS1050 (formerly CS105) Privacy and Technology — tags: corecs, advancedcs.",
      "CS1410 / ECE141 Computing Hardware and CS1411 / ECE146 Computer Architecture — tags: systems, advancedcs.",
      "AC215 Topics in Applied Computation: Advanced Practical Data Science, MLOps — tags: corecs, advancedcs.",
      "CS10 / STAT10 Elements of Data Science — listed as 'No longer offered'.",
    ],
    notes:
      "Confirms the current course numbers (CS 1200/1210/1240/1810/1820/1840/1870 etc.) and the renumbering from the older three-digit identifiers. This resolves the 'verify every identifier' instruction in §38.",
  },
  {
    sourceId: "src-cs50-fall-2026-syllabus",
    url: "https://cs50.harvard.edu/college/2026/fall/syllabus/",
    title: "CS50 Syllabus — Fall 2026, Harvard College",
    publisher: "Harvard University / CS50",
    sourceType: "syllabus",
    accessedAt: RETRIEVED,
    verificationStatus: "confirmed_current",
    extract: [
      "Expectations: watch all lectures, complete three quizzes, attend eleven sections, solve ten problem sets, design and implement a final project.",
      "Grade weights: 3 quizzes 45% (15% each), problem sets 35%, final project 10%, attendance 10%.",
      "Problem sets and the final project are evaluated along correctness, design and style, scored as 2 × correctness + 2 × design + 1 × style.",
      "Week 0 Scratch; Week 1 C; Week 2 Arrays; Week 3 Algorithms; Week 4 Memory; Week 5 Data Structures; Week 6 Python; Week 7 SQL; Week 8 HTML/CSS/JavaScript; Week 9 Flask; Week 10 The End.",
      "Week 3 covers linear search, binary search, bubble/selection/merge sort, asymptotic notation O/Ω/Θ, recursion.",
      "Week 4 covers pointers, segmentation faults, dynamic memory allocation, stack, heap, buffer overflow, file I/O.",
      "Week 5 covers abstract data types, queues, stacks, linked lists, trees, binary search trees, hash tables, tries.",
      "Instructor listed for Fall 2026: Henry H. Leitner. No books are required or recommended.",
    ],
    notes:
      "Used for the assessment-model design (correctness/design/style) and to anchor the CS fundamentals spine. CS50 is Programming 1 only — it is not the Harvard CS curriculum (§3.11).",
  },
  {
    sourceId: "src-harvard-ext-ai-cert",
    url: "https://extension.harvard.edu/academics/programs/artificial-intelligence-graduate-certificate/",
    title: "Artificial Intelligence Graduate Certificate (Online) — Harvard Extension School",
    publisher: "Harvard Extension School",
    sourceType: "program_page",
    accessedAt: RETRIEVED,
    verificationStatus: "confirmed_current",
    extract: [
      "Four online courses: 1 foundations of AI course, 1 advanced NLP and machine learning course, 1 deep learning and computer vision course, 1 AI ethics, governance and law course.",
      "Flexible pace: finish in 8 months to 3 years. Tuition listed as $3,580 per course, $14,320 total (2026–27 rate).",
      "Requirements: complete the four certificate courses for graduate credit, earn at least a B in each, complete within three years. No formal application required.",
      "Recommended prerequisites: statistics and basic programming at the level of STAT 100 or equivalent; Python knowledge (CSCI 7, CSCI 50 or equivalent) recommended.",
      "Page states the next start term as Fall 2026 and an upcoming term of Spring 2027 with registration November 5, 2026 – January 19, 2027.",
    ],
    notes:
      "Confirms the four category structure discussed in §39. This is Harvard Extension School, NOT Harvard College (§3.10).",
  },
  {
    sourceId: "src-harvard-ext-dsai-degree",
    url: "https://extension.harvard.edu/academics/programs/data-science-artificial-intelligence-graduate-program/",
    title: "Data Science and Artificial Intelligence Master's Degree Program — Harvard Extension School",
    publisher: "Harvard Extension School",
    sourceType: "program_page",
    accessedAt: RETRIEVED,
    verificationStatus: "confirmed_current",
    extract: [
      "11 of 12 total courses online, plus one 3-week on-campus course. Tuition $3,580 per course.",
      "Degree awarded: Master of Liberal Arts (ALM) in Extension Studies, field of Data Science and Artificial Intelligence.",
      "Example core courses: Data Mining, Discovery, and Exploration; Dynamic Modeling and Forecasting in Big Data; Ethics, Governance, and Laws of Data Science, AI, and Creative Systems; Introduction to Natural Language Processing; Data Engineering for Analytics to Solve Business Challenges.",
      "Example electives: Artificial Intelligence, the Internet-of-Things, and Cybersecurity; Deep Learning; Foundations of Large Language Models; Remote Sensing Data and Applications.",
      "Performance-based admission via CSCI 101 Foundations of Data Science and Engineering and CSCI 106 Statistical Data Modeling.",
      "Next start term listed as Spring 2027.",
    ],
    notes:
      "Confirms that 'Foundations of Large Language Models' exists as an Extension elective. The page lists it by title; the CSCI E-222 identifier discussed in §38 was NOT confirmed on this page and remains unverified.",
  },
  {
    sourceId: "src-puter-deepseek-v4",
    url: "https://developer.puter.com/blog/deepseek-v4-flash-and-pro-in-puter-js/",
    title: "DeepSeek V4 Flash and DeepSeek V4 Pro Are Now Available in Puter.js",
    publisher: "Puter",
    sourceType: "vendor_docs",
    publishedAt: "2026-04-25",
    accessedAt: RETRIEVED,
    verificationStatus: "confirmed_current",
    extract: [
      "Model identifiers are `deepseek/deepseek-v4-flash` and `deepseek/deepseek-v4-pro`.",
      "Called as puter.ai.chat(prompt, { model }) with an optional { stream: true } option returning an async iterable of parts with `reasoning` and `text`.",
      "Flash: 284B total / 13B activated parameters, 1M token context window, 384K max output tokens, configurable reasoning modes.",
      "Pro: 1.6T parameter MoE with 49B activated per token, same 1M-token context window; positioned for complex reasoning and agentic coding.",
      "Install via `npm install @heyputer/puter.js` or the https://js.puter.com/v2/ script tag.",
    ],
    notes: "Basis for the model routing policy in §201 (Pro for reasoning, Flash for low-latency help).",
  },
  {
    sourceId: "src-owasp-api-top10-2023",
    url: "https://owasp.org/API-Security/editions/2023/en/0x11-t10/",
    title: "OWASP API Security Top 10 — 2023 edition",
    publisher: "OWASP Foundation",
    sourceType: "standard",
    accessedAt: RETRIEVED,
    verificationStatus: "likely_not_verified",
    notes:
      "Listed in §241 and used as the checklist structure for the API security review. Not re-fetched during this pass — treated as a design reference, not as a cited fact.",
  },
  {
    sourceId: "src-nextjs-auth",
    url: "https://nextjs.org/docs/app/guides/authentication",
    title: "Authentication — Next.js App Router guide",
    publisher: "Vercel",
    sourceType: "vendor_docs",
    accessedAt: RETRIEVED,
    verificationStatus: "likely_not_verified",
    notes:
      "Referenced for the server-side session/authorization pattern (Data Access Layer, server-derived user id). Not re-fetched during this pass.",
  },
  {
    sourceId: "src-mongodb-multitenant",
    url: "https://www.mongodb.com/docs/atlas/build-multi-tenant-arch/",
    title: "Build a Multi-Tenant Architecture — MongoDB Atlas",
    publisher: "MongoDB",
    sourceType: "vendor_docs",
    accessedAt: RETRIEVED,
    verificationStatus: "likely_not_verified",
    notes: "Referenced for the shared-collection + ownerId isolation model implemented in the data access layer.",
  },
  {
    sourceId: "src-wcag22",
    url: "https://www.w3.org/TR/WCAG22/",
    title: "Web Content Accessibility Guidelines (WCAG) 2.2",
    publisher: "W3C",
    sourceType: "standard",
    accessedAt: RETRIEVED,
    verificationStatus: "likely_not_verified",
    notes: "Accessibility target for contrast, focus visibility, reduced motion and resizable text.",
  },
  {
    sourceId: "src-cefr",
    url: "https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors-search",
    title: "CEFR Descriptors — Council of Europe",
    publisher: "Council of Europe",
    sourceType: "standard",
    accessedAt: RETRIEVED,
    verificationStatus: "likely_not_verified",
    notes:
      "The English engine tracks CEFR-style dimensions but never asserts a CEFR level from vocabulary counts (§158).",
  },
  {
    sourceId: "src-dunlosky-2013",
    url: "https://doi.org/10.1177/1529100612453266",
    title: "Improving Students' Learning With Effective Learning Techniques (Dunlosky et al., 2013)",
    publisher: "Psychological Science in the Public Interest",
    sourceType: "research",
    publishedAt: "2013",
    accessedAt: RETRIEVED,
    verificationStatus: "likely_not_verified",
    notes:
      "Evidence base for rating practice testing and distributed practice as high-utility (strong evidence) and rereading/highlighting as low-utility.",
  },
  {
    sourceId: "src-cepeda-2006",
    url: "https://pubmed.ncbi.nlm.nih.gov/16719566/",
    title: "Distributed practice in verbal recall tasks: A review and quantitative synthesis (Cepeda et al., 2006)",
    publisher: "Psychological Bulletin",
    sourceType: "research",
    publishedAt: "2006",
    accessedAt: RETRIEVED,
    verificationStatus: "likely_not_verified",
    notes: "Evidence base for the spacing schedule shape used by the review engine.",
  },
  {
    sourceId: "src-nuwave-ai-engineer",
    url: "https://jobs.nuwave.com/apply/JshTpQ8tb8/AI-Engineer",
    title: "AI Engineer — NUWAVE (reference role listing)",
    publisher: "NUWAVE",
    sourceType: "job_posting",
    accessedAt: RETRIEVED,
    verificationStatus: "likely_not_verified",
    notes:
      "Role blueprint supplied by the student in §162 and encoded as a target. The live posting was NOT re-verified in this pass: availability, seniority and location restrictions are unknown and are displayed as unknown.",
  },
  {
    sourceId: "src-navisoft-ai-engineer",
    url: "https://app.devfound.ai/jobs/ai-engineers-navisoft/140943",
    title: "AI Engineers — Navisoft (reference role listing)",
    publisher: "Navisoft / DevFound",
    sourceType: "job_posting",
    accessedAt: RETRIEVED,
    verificationStatus: "likely_not_verified",
    notes:
      "Role blueprint supplied by the student in §161 and encoded as a target. Live posting not re-verified in this pass.",
  },
];

export const SOURCE_BY_ID = Object.fromEntries(SOURCES.map((s) => [s.sourceId, s]));
