import type { Stage, Course } from "./types";

/** §129 MASTER CURRICULUM SPINE — 22 stages, in order. */
export const STAGES: Stage[] = [
  { id: "st-01", order: 1, spineIndex: 1, title: "Mathematical Foundations", summary: "The mathematics an AI engineer actually uses: linear algebra, calculus and optimisation, probability." },
  { id: "st-02", order: 2, spineIndex: 2, title: "Programming Foundations", summary: "Python to a professional standard: correctness, structure, errors, I/O, objects, packaging." },
  { id: "st-03", order: 3, spineIndex: 3, title: "Computer Science Foundations", summary: "Memory, C, data structures, algorithms, complexity, systems, networking — the engineer layer under the ML layer." },
  { id: "st-04", order: 4, spineIndex: 4, title: "Data Foundations", summary: "Spreadsheet and BI literacy, data formats, business analytics deliverables." },
  { id: "st-05", order: 5, spineIndex: 5, title: "Statistics and Probability", summary: "Inference, uncertainty, hypothesis testing and experimental reasoning." },
  { id: "st-06", order: 6, spineIndex: 6, title: "Data Analysis", summary: "NumPy, Pandas, visualisation and end-to-end exploratory analysis." },
  { id: "st-07", order: 7, spineIndex: 7, title: "Data Engineering", summary: "Relational modelling, SQL depth, collection, ETL/ELT, warehouses and big-data concepts." },
  { id: "st-08", order: 8, spineIndex: 8, title: "Classical Machine Learning", summary: "Supervised and unsupervised learning, evaluation, ensembles, model selection." },
  { id: "st-09", order: 9, spineIndex: 9, title: "Deep Learning", summary: "Neural networks from the gradient up, then trained properly with real tooling." },
  { id: "st-10", order: 10, spineIndex: 10, title: "Computer Vision", summary: "CNNs, transfer learning, detection, segmentation and classical image processing." },
  { id: "st-11", order: 11, spineIndex: 11, title: "NLP", summary: "Text processing, embeddings, sequence models and language tasks." },
  { id: "st-12", order: 12, spineIndex: 12, title: "Transformers / LLMs", summary: "Attention, architecture, tokenisation, inference controls, fine-tuning and evaluation." },
  { id: "st-13", order: 13, spineIndex: 13, title: "RAG / GraphRAG", summary: "Retrieval pipelines, hybrid search, grounding, reranking, graph-augmented retrieval." },
  { id: "st-14", order: 14, spineIndex: 14, title: "Agents / Multi-Agent Systems", summary: "Tool use, planning, memory, orchestration — and when not to use an agent." },
  { id: "st-15", order: 15, spineIndex: 15, title: "Software Engineering for AI", summary: "Git, testing, API design, typing, review, release engineering, maintainability." },
  { id: "st-16", order: 16, spineIndex: 16, title: "Cloud Engineering", summary: "AWS depth, Azure working familiarity, containers, infrastructure as code." },
  { id: "st-17", order: 17, spineIndex: 17, title: "MLOps / Production ML", summary: "The full lifecycle from data validation to monitoring, drift, retraining and rollback." },
  { id: "st-18", order: 18, spineIndex: 18, title: "Security / Responsible AI / Governance", summary: "API and LLM security, privacy, fairness, model cards, governance frameworks." },
  { id: "st-19", order: 19, spineIndex: 19, title: "Technical English", summary: "Reading, writing, listening, speaking and interaction for engineering work." },
  { id: "st-20", order: 20, spineIndex: 20, title: "Career and Interview Engineering", summary: "Role requirements, evidence, CV, portfolio, interview and system-design practice." },
  { id: "st-21", order: 21, spineIndex: 21, title: "Freelancing", summary: "Niche, discovery, scoping, proposals, delivery, maintenance, case studies." },
  { id: "st-22", order: 22, spineIndex: 22, title: "Research Engineering", summary: "Paper reading, reproduction, ablation, experimental design, critique and writing." },
];

/**
 * Courses. `sourceCategory` is exactly one label (§127). Harvard mappings are
 * informative only — they never relabel original material as Harvard material.
 */
export const COURSES: Course[] = [
  {
    id: "c-math-foundations",
    stageId: "st-01",
    title: "Math & Statistics (Original Module 2)",
    sourceCategory: "Original Curriculum",
    importance: "CORE",
    originalSessionCount: 5,
    summary: "Linear algebra through probability, preserved exactly as specified, taught with derivations and hand-worked examples.",
    harvardMappings: ["hv-linear-algebra", "hv-stat110", "hv-cs1280", "hv-cs20"],
    sources: ["src-harvard-cs-requirements"],
    note: "Harvard depth is added after this module, never instead of it (§131).",
  },
  {
    id: "c-python",
    stageId: "st-02",
    title: "Python Programming (Original Module 1)",
    sourceCategory: "Original Curriculum",
    importance: "CORE",
    originalSessionCount: 10,
    summary: "From syntax to objects, packaging and a mini-project — the full original ten-session workload.",
    harvardMappings: ["hv-cs50", "hv-cs51"],
  },
  {
    id: "c-cs-foundations",
    stageId: "st-03",
    title: "Computer Science Foundations for AI Engineers",
    sourceCategory: "Harvard College",
    secondarySourceCategories: ["Industry Extension"],
    importance: "CORE",
    summary:
      "The CS layer §130 requires: C and the memory model, Linux, data structures, algorithms, complexity, systems, concurrency and networking — scoped to AI engineering rather than a full CS degree.",
    harvardMappings: ["hv-cs50", "hv-cs61", "hv-cs1200", "hv-cs1240", "hv-cs1210", "hv-cs1410-1411"],
    sources: ["src-cs50-fall-2026-syllabus", "src-harvard-cs-tags"],
  },
  {
    id: "c-excel-powerbi",
    stageId: "st-04",
    title: "Excel & Power BI (Original Module 4)",
    sourceCategory: "Original Curriculum",
    importance: "SUPPORT",
    originalSessionCount: 4,
    summary: "Business analytics deliverables: formulas, pivots, Power Query, data modelling, DAX, dashboards and publishing.",
    note: "Deliberately retained. No Harvard CS equivalent was found; that is a reason to label it, not to delete it (§69).",
  },
  {
    id: "c-statistics",
    stageId: "st-05",
    title: "Statistical Inference Depth",
    sourceCategory: "Harvard College",
    importance: "CORE",
    summary: "The probability and inference layer that the original statistics sessions open up: estimation, testing, intervals, Bayesian reasoning.",
    harvardMappings: ["hv-stat110", "hv-cs1090ab"],
    sources: ["src-harvard-cs-requirements"],
  },
  {
    id: "c-data-analysis",
    stageId: "st-06",
    title: "Data Analysis with Python (Original Module 3)",
    sourceCategory: "Original Curriculum",
    importance: "CORE",
    originalSessionCount: 10,
    summary: "NumPy, inferential statistics in practice, Pandas wrangling, visualisation and a full EDA capstone.",
    harvardMappings: ["hv-cs1090ab"],
  },
  {
    id: "c-databases",
    stageId: "st-07",
    title: "Databases & Data Engineering (Original Module 5)",
    sourceCategory: "Original Curriculum",
    importance: "CORE",
    originalSessionCount: 8,
    summary: "ERD and normalisation, SQL to window functions, lawful collection, and an end-to-end ETL capstone.",
    harvardMappings: ["hv-cs1650"],
  },
  {
    id: "c-data-engineering",
    stageId: "st-07",
    title: "Data Engineering and Big Data Systems",
    sourceCategory: "Industry Extension",
    importance: "INDUSTRY_EXTENSION",
    summary: "§134: modelling, warehouse and lakehouse concepts, batch vs streaming, Airflow, dbt, Spark, partitioning, Hadoop concepts.",
    harvardMappings: ["hv-cs1650", "hv-ext-dsai"],
  },
  {
    id: "c-ml",
    stageId: "st-08",
    title: "Machine Learning (Original Module 6)",
    sourceCategory: "Original Curriculum",
    importance: "CORE",
    originalSessionCount: 12,
    summary: "Preprocessing through ensembles and unsupervised learning, ending in a model-card-backed capstone.",
    harvardMappings: ["hv-cs1810", "hv-cs1820", "hv-ext-ai-cert"],
  },
  {
    id: "c-deep-learning",
    stageId: "st-09",
    title: "Deep Learning (Original Module 7)",
    sourceCategory: "Original Curriculum",
    importance: "CORE",
    originalSessionCount: 16,
    summary: "Neural network foundations, real training practice, computer vision, sequence models, NLP and transformers.",
    harvardMappings: ["hv-cs1870", "hv-ext-ai-cert", "hv-csci-e25-e89-e104"],
  },
  {
    id: "c-llm",
    stageId: "st-12",
    title: "LLM Engineering Depth",
    sourceCategory: "Industry Extension",
    secondarySourceCategories: ["Harvard Extension"],
    importance: "CORE",
    summary: "§137 beyond prompting: tokenisation, inference controls, evaluation, hallucination analysis, fine-tuning, quantisation, cost and latency.",
    harvardMappings: ["hv-csci-e222", "hv-ext-dsai"],
  },
  {
    id: "c-rag",
    stageId: "st-13",
    title: "RAG and GraphRAG Systems",
    sourceCategory: "Industry Extension",
    importance: "CORE",
    summary: "Retrieval pipelines end to end: chunking, embeddings, hybrid search, metadata filtering, reranking, grounding, evaluation, graphs.",
  },
  {
    id: "c-agents",
    stageId: "st-14",
    title: "Agents and Multi-Agent Systems",
    sourceCategory: "Industry Extension",
    importance: "SPECIALIZATION",
    summary: "§138 decision framework first, then tool calling, planning, memory, orchestration, permissions, safety and observability.",
    harvardMappings: ["hv-cs1820"],
  },
  {
    id: "c-software-engineering",
    stageId: "st-15",
    title: "Software Engineering for AI Systems",
    sourceCategory: "Industry Extension",
    importance: "CORE",
    summary: "§132 in full: requirements, Git, review, typing, tests, logging, API design, caching, retries, idempotency, release and rollback.",
    harvardMappings: ["hv-cs51"],
  },
  {
    id: "c-cloud",
    stageId: "st-16",
    title: "Cloud Engineering (AWS depth, Azure familiarity)",
    sourceCategory: "Industry Extension",
    importance: "CORE",
    summary: "§133: IAM, S3, Lambda, API Gateway, EC2/ECR/ECS, CloudWatch, VPC basics; Entra ID, Azure storage/compute/serverless; containers and IaC.",
    harvardMappings: ["hv-ac215"],
  },
  {
    id: "c-deployment",
    stageId: "st-17",
    title: "Development & MLOps (Original Module 8)",
    sourceCategory: "Original Curriculum",
    importance: "CORE",
    originalSessionCount: 2,
    summary: "APIs, FastAPI, Streamlit, Docker, CI/CD and the final capstone — the original tooling, kept as specified.",
    harvardMappings: ["hv-ac215"],
  },
  {
    id: "c-mlops",
    stageId: "st-17",
    title: "Production ML Lifecycle",
    sourceCategory: "Industry Extension",
    importance: "CORE",
    summary: "§136 lifecycle: validation, experiment tracking, registry, packaging, deployment, monitoring, drift, retraining and rollback.",
    harvardMappings: ["hv-ac215", "hv-apcomp215"],
  },
  {
    id: "c-responsible-ai",
    stageId: "st-18",
    title: "Security, Responsible AI and Governance",
    sourceCategory: "Industry Extension",
    secondarySourceCategories: ["Harvard College", "Harvard Extension"],
    importance: "CORE",
    summary: "API and LLM security, prompt injection, privacy, fairness, data provenance, model and system cards, governance frameworks.",
    harvardMappings: ["hv-cs1050", "hv-ext-ai-cert", "hv-ext-dsai"],
    sources: ["src-owasp-api-top10-2023"],
  },
  {
    id: "c-english",
    stageId: "st-19",
    title: "Technical English for Engineers",
    sourceCategory: "Industry Extension",
    importance: "SUPPORT",
    summary: "§153–§159: standard technical English by default, B1–B2 support on demand, vocabulary assistance, reading, writing, speaking lab.",
    sources: ["src-cefr"],
  },
  {
    id: "c-career",
    stageId: "st-20",
    title: "Career and Interview Engineering",
    sourceCategory: "Industry Extension",
    importance: "SUPPORT",
    summary: "§160–§167: target-role requirements, evidence-driven gap analysis, CV value, portfolio case studies, interview and system-design practice.",
    sources: ["src-nuwave-ai-engineer", "src-navisoft-ai-engineer"],
  },
  {
    id: "c-freelance",
    stageId: "st-21",
    title: "Freelancing and Client Engineering",
    sourceCategory: "Industry Extension",
    importance: "SUPPORT",
    summary: "§168–§169: niche and service selection, discovery, scope, estimates, proposals, change requests, delivery and maintenance.",
  },
  {
    id: "c-research",
    stageId: "st-22",
    title: "Research Engineering",
    sourceCategory: "Research Extension",
    importance: "RESEARCH",
    summary: "§178: paper reading, literature search, claim identification, baselines, ablations, reproduction, critique and scientific writing.",
    harvardMappings: ["hv-cs1840", "hv-ext-dsai"],
  },
];

export const COURSE_BY_ID = Object.fromEntries(COURSES.map((c) => [c.id, c]));
