export type ProjectSeed = {
  id: string;
  title: string;
  ladderLevel: number;
  track: string;
  sourceCategory: string;
  problem: string;
  constraints: string[];
  dataPolicy: string;
  suggestedData: { name: string; url: string; note: string }[];
  milestones: string[];
  definitionOfDone: string[];
  skills: string[];
  prerequisites: string[];
};

const DOD_BASE = [
  "Stated requirements and acceptance criteria are met",
  "Tests pass and edge cases are considered",
  "Data source, licence/terms and acquisition date are documented",
  "Evaluation design is valid for the decision being made",
  "Failure analysis is written, not just headline metrics",
  "README explains how to reproduce the result from a clean clone",
  "Security and privacy review completed for the data used",
  "Limitations and next steps stated honestly",
];

const DOD_DEPLOY = [
  ...DOD_BASE,
  "Service is deployed and reachable, or the deployment is documented as not performed",
  "Monitoring signals and thresholds are defined",
  "Rollback procedure is written and tested once",
];

const p = (
  id: string,
  title: string,
  ladderLevel: number,
  track: string,
  problem: string,
  constraints: string[],
  suggestedData: { name: string; url: string; note: string }[],
  skills: string[],
  prerequisites: string[],
  deploy = false,
  milestones: string[] = [],
): ProjectSeed => ({
  id,
  title,
  ladderLevel,
  track,
  sourceCategory: "Original Curriculum",
  problem,
  constraints,
  dataPolicy:
    "Use real public data or a real public API where lawful. Record source, licence/terms, acquisition date, schema, known limitations, bias risks and leakage risks. Synthetic data is permitted only for explicit synthetic-data lessons or deterministic tests and must be labelled as synthetic.",
  suggestedData,
  milestones:
    milestones.length > 0
      ? milestones
      : [
          "Write the problem statement and acceptance criteria before any code",
          "Acquire data and record provenance",
          "Exploratory analysis and baseline",
          "Implementation",
          "Evaluation and failure analysis",
          "Documentation and portfolio case study",
        ],
  definitionOfDone: deploy ? DOD_DEPLOY : DOD_BASE,
  skills,
  prerequisites,
});

const KAGGLE = (name: string, note: string) => ({
  name,
  url: "https://www.kaggle.com/datasets",
  note: `${note} Search Kaggle Datasets for a current, licensed dataset and record its exact URL, licence and download date. Do not assume a specific dataset still exists.`,
});

const UCI = (name: string, note: string) => ({
  name,
  url: "https://archive.ics.uci.edu/",
  note: `${note} Use the UCI Machine Learning Repository listing page and record the exact dataset URL, citation requirement and download date.`,
});

export const projectSeeds: ProjectSeed[] = [
  /* ---- Original 21 project catalog, preserved, mapped onto the ladder ---- */
  p(
    "proj-library-management",
    "Library Management System",
    1,
    "Python engineering",
    "Build a library management system with members, catalogue, loans, returns and overdue handling. The engineering point is domain modelling, persistence and tests — not CRUD typing practice.",
    ["No framework magic: the domain logic must be testable without a web server", "Loan rules enforced in one place", "At least 15 meaningful unit tests including boundary cases"],
    [{ name: "Self-defined domain data", url: "internal://domain", note: "No external dataset required. Seed data must be clearly labelled as fixture data." }],
    ["python", "software-engineering", "testing"],
    ["orig-m1-python"],
  ),
  p(
    "proj-uber-analysis",
    "Uber Data Analysis",
    2,
    "Data analysis",
    "Analyse real trip data to answer a stated operational question (for example: where and when does demand outstrip typical supply?). The deliverable is a decision, not a gallery of charts.",
    ["State the question before opening the data", "Document every cleaning decision and its effect on row count", "Every chart must answer a stated question"],
    [KAGGLE("Uber / ride-hailing trip data", "Public ride-hailing trip datasets are commonly published.")],
    ["pandas", "visualization", "statistics"],
    ["orig-m3-data-analysis"],
  ),
  p(
    "proj-superstore-dashboard",
    "Superstore Data Analysis Dashboard",
    2,
    "Business analytics",
    "Build a dashboard over retail transaction data that a category manager could actually use to decide what to stock and discount.",
    ["Star-schema model, not a single flat table", "Every visual maps to a named decision", "Measures must survive filter-context changes"],
    [KAGGLE("Retail / superstore transactions", "Widely republished retail transaction datasets exist.")],
    ["excel-powerbi", "visualization", "sql"],
    ["orig-m4-excel-powerbi"],
  ),
  p(
    "proj-hr-dashboard",
    "HR Dashboard",
    2,
    "Business analytics",
    "Build an HR analytics dashboard covering headcount, attrition and tenure, including an explicit note on which questions the data cannot answer.",
    ["Attrition definition stated and defended", "No inference about individuals", "Privacy review required before any real data is used"],
    [KAGGLE("HR analytics / attrition dataset", "Public HR attrition datasets exist and are frequently synthetic — label this honestly.")],
    ["excel-powerbi", "visualization", "responsible-ai"],
    ["orig-m4-excel-powerbi"],
  ),
  p(
    "proj-bank-loan-analysis",
    "Bank Loan Data Analysis",
    3,
    "Data analysis",
    "Analyse loan performance data and quantify which applicant characteristics are associated with default — while explicitly separating association from causation and flagging fairness risks.",
    ["Protected-attribute analysis required", "No causal language without a causal design", "Missing-data mechanism discussed"],
    [UCI("Credit / loan default data", "Credit datasets are available in public repositories.")],
    ["pandas", "statistics", "responsible-ai"],
    ["orig-m3-data-analysis"],
  ),
  p(
    "proj-sales-database",
    "Sales Database",
    3,
    "SQL / data pipeline",
    "Design and build a normalised sales database with an ingest pipeline, then answer ten analytical questions with SQL including window functions.",
    ["3NF schema with an ERD", "Idempotent loader", "Each query must include its execution plan observation"],
    [{ name: "Public sales/transaction CSV", url: "https://archive.ics.uci.edu/", note: "Use a public transactional dataset and record its exact source and licence." }],
    ["sql", "data-engineering"],
    ["orig-m5-databases"],
  ),
  p(
    "proj-titanic",
    "Titanic Prediction",
    4,
    "Classical ML",
    "Build a survival classifier — then do the part most people skip: a rigorous leakage audit, a calibration check and an honest comparison against a trivial baseline.",
    ["Must beat a stated trivial baseline by a stated margin", "Leakage audit documented", "Calibration plot required"],
    [KAGGLE("Titanic", "The Titanic dataset is a long-standing public teaching dataset.")],
    ["classical-ml", "model-evaluation", "pandas"],
    ["orig-m6-ml"],
  ),
  p(
    "proj-house-pricing",
    "House Pricing Prediction",
    4,
    "Classical ML",
    "Predict house prices with a regression model, with explicit treatment of skewed targets, outliers, and the difference between MAE, RMSE and business cost.",
    ["Justify the loss/metric in terms of the decision", "Residual analysis by segment", "Report uncertainty, not a single number"],
    [KAGGLE("House prices / housing data", "Housing price datasets are widely published.")],
    ["classical-ml", "model-evaluation", "statistics"],
    ["orig-m6-ml"],
  ),
  p(
    "proj-credit-fraud",
    "Credit Card Fraud Detection",
    4,
    "Classical ML",
    "Build a fraud detector on severely imbalanced data and present the operating point in analyst workload terms, not in ROC-AUC.",
    ["PR-AUC primary, ROC-AUC secondary", "Threshold chosen from an alert-budget argument", "Temporal validation if timestamps exist"],
    [KAGGLE("Credit card fraud detection", "A widely used anonymised fraud dataset is publicly available.")],
    ["classical-ml", "model-evaluation"],
    ["orig-m6-ml"],
  ),
  p(
    "proj-stock-prediction",
    "Stock Market Prediction",
    5,
    "Sequence modelling",
    "Forecast a financial time series — and demonstrate why most published results of this kind are invalid. Walk-forward validation and a naive-persistence baseline are mandatory.",
    ["Walk-forward (not random) splits", "Must compare against the naive last-value baseline", "No claim of trading profitability"],
    [{ name: "Public market data API", url: "https://www.alphavantage.co/documentation/", note: "Use a public market-data API within its terms of service; record the endpoint, symbol, interval and retrieval date." }],
    ["deep-learning", "statistics", "model-evaluation"],
    ["orig-m7-deep-learning"],
  ),
  p(
    "proj-breast-cancer",
    "Breast Cancer Detection",
    4,
    "Classical ML / health",
    "Build a diagnostic-support classifier where false negatives dominate the cost function, and write the clinical-context limitations section properly.",
    ["Recall-primary metric with stated minimum precision", "Explicit statement that this is not a medical device", "Subgroup analysis where data permits"],
    [UCI("Breast cancer diagnostic data", "Classic diagnostic datasets are available in public repositories.")],
    ["classical-ml", "model-evaluation", "responsible-ai"],
    ["orig-m6-ml"],
  ),
  p(
    "proj-skin-disease",
    "Skin Disease Prediction",
    6,
    "Computer vision / health",
    "Image classification over dermatology images with transfer learning, including a skin-tone representation audit of the dataset and a refusal-to-deploy statement.",
    ["Document dataset demographic coverage and its gaps", "Report per-class and, where possible, per-subgroup performance", "State explicitly that this is not a diagnostic tool"],
    [KAGGLE("Dermatology image dataset", "Public dermatology image collections exist; licences vary and must be checked individually.")],
    ["computer-vision", "deep-learning", "responsible-ai"],
    ["orig-m7-deep-learning"],
  ),
  p(
    "proj-brain-tumor",
    "Brain Tumor Detection",
    6,
    "Computer vision / health",
    "Detect tumours in MRI images with a CNN and transfer learning; quantify the effect of patient-level versus image-level splitting.",
    ["Patient-level split required — image-level splitting is a leakage defect", "Report sensitivity and specificity", "Not a medical device"],
    [KAGGLE("Brain MRI image dataset", "Public MRI classification datasets exist; verify licence and citation terms.")],
    ["computer-vision", "deep-learning", "model-evaluation"],
    ["orig-m7-deep-learning"],
  ),
  p(
    "proj-face-recognition",
    "Face Recognition / Detection / Verification",
    6,
    "Computer vision",
    "Build detection, then verification (same/different person) with an embedding model, and write the privacy and consent analysis before writing the code.",
    ["Consent and privacy analysis precedes implementation", "Report accuracy disparities across available demographic groups", "No deployment against people who have not consented"],
    [KAGGLE("Public face verification benchmark", "Public benchmarks exist; several have restrictive or contested licences — verify before use.")],
    ["computer-vision", "deep-learning", "responsible-ai"],
    ["orig-m7-deep-learning"],
  ),
  p(
    "proj-object-detection",
    "Real-time Object Detection",
    6,
    "Computer vision",
    "Run and evaluate a real-time detector, measuring the accuracy/latency trade-off across input resolutions on your actual hardware.",
    ["Measure FPS and mAP on the same machine", "Report the trade-off curve, not one configuration", "Document hardware explicitly"],
    [{ name: "Public detection benchmark subset", url: "https://cocodataset.org/", note: "Use a public detection benchmark and record its licence and the subset used." }],
    ["computer-vision", "deep-learning", "observability"],
    ["orig-m7-deep-learning"],
  ),
  p(
    "proj-sign-language",
    "Sign Language Classifier",
    6,
    "Computer vision",
    "Classify sign-language gestures, with explicit discussion of signer-independent evaluation and why signer-dependent splits overstate performance.",
    ["Signer-independent split", "Confusion analysis for visually similar classes", "Consult accessibility considerations in the write-up"],
    [KAGGLE("Sign language image dataset", "Public sign-language image datasets exist.")],
    ["computer-vision", "deep-learning"],
    ["orig-m7-deep-learning"],
  ),
  p(
    "proj-text-classification",
    "Text Classification",
    6,
    "NLP",
    "Build a text classifier and compare a TF-IDF linear baseline against a transformer fine-tune on cost, latency and accuracy — then argue which you would actually ship.",
    ["Linear baseline is mandatory", "Report cost and latency alongside accuracy", "Error analysis on the 50 worst examples"],
    [KAGGLE("Public labelled text corpus", "Public labelled text classification corpora are widely available.")],
    ["nlp", "transformers", "model-evaluation"],
    ["orig-m7-deep-learning"],
  ),
  p(
    "proj-gan-image-generation",
    "Image Generation using GANs",
    7,
    "Generative modelling",
    "Train a small generative model and confront evaluation honestly: what does a generated-sample grid actually prove, and what does it not?",
    ["Report training instability observations", "Discuss evaluation limitations explicitly", "No claim of photorealism without a quantitative measure"],
    [{ name: "Small public image dataset", url: "https://www.cs.toronto.edu/~kriz/cifar.html", note: "Use a small, clearly licensed public image dataset; record the version." }],
    ["deep-learning", "computer-vision", "research"],
    ["orig-m7-deep-learning"],
  ),
  p(
    "proj-chatbot",
    "Chatbot",
    7,
    "LLM application",
    "Build a task-oriented assistant with an explicit scope boundary, a refusal policy, and an evaluation set that can actually fail.",
    ["Written scope: what it must refuse", "Evaluation set of at least 30 real questions", "Log every response for review"],
    [{ name: "Your own documented corpus", url: "internal://corpus", note: "Use a real document corpus you have the right to use; record its origin." }],
    ["transformers", "rag", "security"],
    ["llm-engineering"],
    true,
  ),
  p(
    "proj-document-summarization",
    "Document Summarization",
    7,
    "LLM application",
    "Summarise long documents with a measurable faithfulness criterion — including detection of claims that do not appear in the source.",
    ["Define faithfulness operationally before building", "Human-rated sample of at least 20 summaries", "Report hallucination rate"],
    [{ name: "Public long-document corpus", url: "https://www.gutenberg.org/", note: "Use clearly public-domain or licensed long documents and record the source." }],
    ["transformers", "nlp", "model-evaluation"],
    ["llm-engineering"],
  ),
  p(
    "proj-rag-system",
    "RAG System",
    7,
    "LLM application",
    "Build a retrieval-augmented system with citations, an evaluation harness measuring recall@k and faithfulness separately, and a documented defence against prompt injection from retrieved content.",
    ["Separate retrieval and generation metrics", "Every answer carries citations or refuses", "Injection defence documented and tested"],
    [{ name: "A real document corpus you may lawfully index", url: "internal://corpus", note: "Record the corpus origin, licence and refresh policy." }],
    ["rag", "transformers", "security", "model-evaluation"],
    ["rag-engineering"],
    true,
  ),

  /* ---- Ladder completion: agents, production, research ---- */
  p(
    "proj-agentic-ops-assistant",
    "Agentic Operations Assistant",
    8,
    "Agents",
    "Build a bounded agent that investigates a failing data pipeline across logs and the warehouse, proposes a fix, and never executes a write without human approval.",
    ["Hard iteration, time and cost caps enforced in code", "Read-only tools by default", "Full per-step trace with a run ID", "Written justification of why a deterministic workflow is insufficient"],
    [{ name: "Your own pipeline telemetry", url: "internal://telemetry", note: "Use telemetry from a system you own; never from a third party without permission." }],
    ["agents", "observability", "security", "system-design"],
    ["agent-engineering"],
    true,
  ),
  p(
    "proj-production-ai-service",
    "Production-Style AI Service",
    9,
    "Production AI",
    "Take one earlier model and ship it properly: containerised API, CI/CD, authentication, rate limiting, monitoring with thresholds, a load test, and one deliberate rehearsed rollback.",
    ["Authentication and per-user rate limiting", "Monitoring table with owners and thresholds", "Documented and rehearsed rollback", "Cost estimate per 1k requests"],
    [{ name: "Reuse an earlier project's data", url: "internal://prior-project", note: "Carry forward the original provenance record." }],
    ["mlops", "docker", "aws", "api-design", "observability", "security"],
    ["orig-m8-mlops", "cloud-engineering"],
    true,
  ),
  p(
    "proj-research-reproduction",
    "Research Reproduction and Ablation",
    10,
    "Research",
    "Select a paper with a public implementation, reproduce one reported number, run one ablation, and write a report that states honestly what did not replicate.",
    ["State the falsifiable claim being tested", "Pin seeds, versions and hardware", "Report the gap between your number and the published one", "One ablation with a stated hypothesis"],
    [{ name: "The paper's stated dataset", url: "https://arxiv.org/", note: "Use the dataset specified by the paper; record version and access date." }],
    ["research", "deep-learning", "model-evaluation", "technical-english"],
    ["research-engineering"],
    false,
    [
      "Select the paper and extract its falsifiable claim",
      "Locate the official implementation and pin the environment",
      "Reproduce the headline number",
      "Design and run one ablation",
      "Write the reproduction report including failures",
      "Present a 10-minute defence",
    ],
  ),
  p(
    "proj-final-capstone",
    "Final Capstone: End-to-End AI System",
    10,
    "Capstone",
    "A single system combining problem definition, literature context, real data, EDA, baseline, modelling, evaluation, failure analysis, ablations, deployment, monitoring, a model/system card, an ethics and safety analysis, a demo, a technical report and an oral defence.",
    ["Real data with full provenance", "Baseline before model", "Monitoring and rollback required", "Oral defence required", "Portfolio case study required"],
    [{ name: "Chosen in the proposal stage", url: "internal://capstone", note: "Dataset selection and provenance are part of the capstone proposal deliverable." }],
    ["mlops", "model-evaluation", "system-design", "responsible-ai", "technical-english", "communication"],
    ["proj-production-ai-service"],
    true,
    [
      "Proposal: problem, stakeholders, success criteria, data plan",
      "Literature and context review",
      "Data acquisition with provenance record",
      "EDA and baseline",
      "Modelling and evaluation",
      "Failure analysis and ablations",
      "Deployment with monitoring and rollback",
      "Model/system card and ethics analysis",
      "Technical report and demo",
      "Oral defence and portfolio case study",
    ],
  ),
];
