import type { HarvardMapping } from "@/db/schema";

export type SourceRecord = {
  id: string;
  url: string;
  title: string;
  publisher: string;
  sourceType: string;
  verificationStatus: "confirmed_current" | "confirmed_historical" | "likely_not_verified" | "not_found" | "design_decision" | "research_hypothesis";
  accessed: boolean;
  notes: string;
};

/** Retrieval date for sources fetched during this build session. */
export const RETRIEVAL_DATE = "2026-10-05";

export const SOURCES: SourceRecord[] = [
  { id: "harvard-cs-requirements", url: "https://csadvising.seas.harvard.edu/concentration/requirements/", title: "CS Concentration Requirements", publisher: "Harvard CS Advising (SEAS)", sourceType: "official_catalog", verificationStatus: "confirmed_current", accessed: true, notes: "Retrieved in-session. Basic plan: 9 CS core courses (11 honors) satisfying tags Programming 1/2, Formal Reasoning (3), Discrete Math, Computational Limitations, Algorithms, Systems, Computation and the World, Advanced CS (4). Math prep: calculus, Linear Algebra (Math 21b/22a, AM 22a…), Probability (Stat 110, ES 150…). Honors adds Intermediate Algorithms and an AI tag." },
  { id: "harvard-cs-tags", url: "https://csadvising.seas.harvard.edu/concentration/courses/tags/", title: "Course Tags", publisher: "Harvard CS Advising (SEAS)", sourceType: "official_catalog", verificationStatus: "confirmed_current", accessed: true, notes: "Retrieved in-session. Confirms current numbering: CS 1200/1210/1240 (formerly 120/121/124), CS 1810 ML, CS 1820 AI, CS 1840 RL, CS 1870 NLP, CS 1650 Data Systems, CS 1280 Convex Optimization, CS 1090A/B Data Science 1/2, AC215 Advanced Practical Data Science/MLOps, CS 2680 Building AI Systems with AI: Agents and Systems, CS 2831 Computer Vision, CS 1050 Privacy and Technology, CS 1260 Fairness and Privacy, CS 1410 Computing Hardware, CS 1411 Computer Architecture, CS 2420 Computing at Scale, CS 2620 Distributed Computing, ECE 50, ECE 143, ECE 150, STAT 110/111/195/210/220, MATH 21A/21B/22A/23A/25A/55A." },
  { id: "harvard-cs-advising", url: "https://csadvising.seas.harvard.edu/", title: "Harvard CS Advising", publisher: "Harvard SEAS", sourceType: "official_catalog", verificationStatus: "likely_not_verified", accessed: false, notes: "Listed in spec; landing page not fetched this session (requirements and tags sub-pages were)." },
  { id: "cs50-college-2026-syllabus", url: "https://cs50.harvard.edu/college/2026/fall/syllabus/", title: "CS50 Fall 2026 Syllabus (Harvard College)", publisher: "Harvard CS50", sourceType: "syllabus", verificationStatus: "confirmed_current", accessed: true, notes: "Retrieved in-session. Expectations: all lectures, 3 quizzes (15% each = 45%), 11 sections, 10 problem sets (35%), final project (10%), attendance (10%). Weeks: Scratch, C, Arrays, Algorithms, Memory, Data Structures, Python, SQL, HTML/CSS/JS, Flask, Ethics. Psets scored 2×correctness + 2×design + 1×style. Sections 1–2h weekly by comfort level; office hours. AI policy: only CS50's own duck; no ChatGPT/Claude/Copilot for psets." },
  { id: "cs50-college-2026-psets", url: "https://cs50.harvard.edu/college/2026/fall/psets/", title: "CS50 Fall 2026 Problem Sets", publisher: "Harvard CS50", sourceType: "syllabus", verificationStatus: "likely_not_verified", accessed: false, notes: "Pset list (0–9, languages and deadlines) confirmed via the syllabus page; individual pset pages not fetched." },
  { id: "cs50-extension-2026-syllabus", url: "https://cs50.harvard.edu/extension/2026/fall/syllabus/", title: "CS50 Extension Fall 2026 Syllabus", publisher: "Harvard Extension / CS50", sourceType: "syllabus", verificationStatus: "likely_not_verified", accessed: false, notes: "Not fetched this session. Do not assume identical to College syllabus." },
  { id: "hes-ai-certificate", url: "https://extension.harvard.edu/academics/programs/artificial-intelligence-graduate-certificate/", title: "Artificial Intelligence Graduate Certificate", publisher: "Harvard Extension School", sourceType: "program_page", verificationStatus: "confirmed_current", accessed: true, notes: "Retrieved in-session. Four online graduate courses: 1 foundations of AI; 1 advanced NLP and machine learning; 1 deep learning and computer vision; 1 AI ethics, governance, and law. Recommended prep: statistics/programming at STAT 100 level; Python strongly recommended (CSCI 7/50). Grade B or better; complete within 3 years. Upcoming term shown: Spring 2027." },
  { id: "hes-graduate-certificates", url: "https://extension.harvard.edu/academics/graduate-certificates/", title: "Graduate Certificates", publisher: "Harvard Extension School", sourceType: "program_page", verificationStatus: "likely_not_verified", accessed: false, notes: "Not fetched this session." },
  { id: "hes-ds-certificate", url: "https://extension.harvard.edu/academics/programs/data-science-graduate-certificate/", title: "Data Science Graduate Certificate", publisher: "Harvard Extension School", sourceType: "program_page", verificationStatus: "likely_not_verified", accessed: false, notes: "Not fetched this session." },
  { id: "hes-archive-2025-2026", url: "https://extension.harvard.edu/2025-2026-extension-course-archive/", title: "2025–2026 Extension Course Archive", publisher: "Harvard Extension School", sourceType: "official_catalog", verificationStatus: "likely_not_verified", accessed: false, notes: "Not fetched. Specific Extension course identifiers (CSCI E-25, E-89, E-104, E-222) are therefore marked likely_not_verified." },
  { id: "hes-pursuing-certificate", url: "https://extension.harvard.edu/registration-admissions/pursuing-a-certificate/", title: "Pursuing a Certificate", publisher: "Harvard Extension School", sourceType: "program_page", verificationStatus: "likely_not_verified", accessed: false, notes: "Not fetched." },
  { id: "bok-sections", url: "https://bokcenter.harvard.edu/sections", title: "Sections", publisher: "Harvard Bok Center", sourceType: "docs", verificationStatus: "likely_not_verified", accessed: false, notes: "Not fetched; section model encoded from CS50 syllabus instead." },
  { id: "hsph-case-resources", url: "https://www.caseresources.hsph.harvard.edu/resources/", title: "Case Resources", publisher: "Harvard T.H. Chan School", sourceType: "docs", verificationStatus: "likely_not_verified", accessed: false, notes: "Not fetched." },
  { id: "wwc-organizing-instruction", url: "https://ies.ed.gov/ncee/wwc/PracticeGuide/1", title: "Organizing Instruction and Study to Improve Student Learning", publisher: "IES What Works Clearinghouse", sourceType: "research", verificationStatus: "confirmed_historical", accessed: false, notes: "2007 practice guide; recommendations (spacing, interleaving worked examples, quizzing, deep questions) are stable published findings. Not re-fetched this session." },
  { id: "wwc-practice-guides", url: "https://ies.ed.gov/ncee/wwc/PracticeGuides", title: "WWC Practice Guides", publisher: "IES", sourceType: "research", verificationStatus: "likely_not_verified", accessed: false, notes: "Index page not fetched." },
  { id: "dunlosky-2013", url: "https://doi.org/10.1177/1529100612453266", title: "Improving Students' Learning With Effective Learning Techniques", publisher: "Psychological Science in the Public Interest (2013)", sourceType: "research", verificationStatus: "confirmed_historical", accessed: false, notes: "Practice testing and distributed practice rated high utility; rereading/highlighting low utility. Strong evidence." },
  { id: "cepeda-2006", url: "https://pubmed.ncbi.nlm.nih.gov/16719566/", title: "Distributed practice in verbal recall tasks: a review and quantitative synthesis", publisher: "Psychological Bulletin (2006)", sourceType: "research", verificationStatus: "confirmed_historical", accessed: false, notes: "Meta-analysis supporting spacing; optimal gap scales with retention interval." },
  { id: "coursera-guided-projects", url: "https://blog.coursera.org/coursera-white-paper-details-the-pedagogy-underlying-guided-projects-on-coursera/", title: "Pedagogy underlying Guided Projects", publisher: "Coursera", sourceType: "docs", verificationStatus: "likely_not_verified", accessed: false, notes: "Not fetched." },
  { id: "coursera-mastery", url: "https://blog.coursera.org/how-to-integrate-mastery-learning-into-course-design/", title: "Integrating mastery learning", publisher: "Coursera", sourceType: "docs", verificationStatus: "likely_not_verified", accessed: false, notes: "Not fetched." },
  { id: "coursera-skills", url: "https://blog.coursera.org/courseras-commitment-to-learning-how-we-support-skill-development/", title: "Supporting skill development", publisher: "Coursera", sourceType: "docs", verificationStatus: "likely_not_verified", accessed: false, notes: "Not fetched." },
  { id: "cefr", url: "https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors-search", title: "CEFR Descriptors", publisher: "Council of Europe", sourceType: "standard", verificationStatus: "confirmed_historical", accessed: false, notes: "CEFR levels A1–C2 across reception, production, interaction, mediation. Used for English dimension naming only; the platform never assigns C1/C2 from vocabulary counts." },
  { id: "puter-deepseek", url: "https://developer.puter.com/blog/deepseek-v4-flash-and-pro-in-puter-js/", title: "DeepSeek V4 Flash and Pro in Puter.js", publisher: "Puter", sourceType: "docs", verificationStatus: "likely_not_verified", accessed: false, notes: "Blog page not fetched; model ids confirmed via developer.puter.com model page instead." },
  { id: "puter-openai-compatible", url: "https://developer.puter.com/tutorials/access-deepseek-using-openai-compatible-api/", title: "Access DeepSeek Using OpenAI-Compatible API", publisher: "Puter", sourceType: "docs", verificationStatus: "confirmed_current", accessed: true, notes: "Retrieved in-session (page dated 2026-07-29). Endpoint https://api.puter.com/puterai/openai/v1/chat/completions with Bearer <PUTER_AUTH_TOKEN>; models deepseek/deepseek-v4-flash and deepseek/deepseek-v4-pro." },
  { id: "puter-docs", url: "https://docs.puter.com/", title: "Puter Docs", publisher: "Puter", sourceType: "docs", verificationStatus: "likely_not_verified", accessed: false, notes: "Not fetched." },
  { id: "wcag22", url: "https://www.w3.org/TR/WCAG22/", title: "WCAG 2.2", publisher: "W3C", sourceType: "standard", verificationStatus: "confirmed_historical", accessed: false, notes: "W3C Recommendation (2023). Applied: semantic HTML, focus visibility, contrast, reduced motion, labels." },
  { id: "nextjs-auth", url: "https://nextjs.org/docs/app/guides/authentication", title: "Next.js Authentication guide", publisher: "Vercel", sourceType: "docs", verificationStatus: "likely_not_verified", accessed: false, notes: "Not fetched; implementation follows the documented pattern (server-side session verification in a data access layer, httpOnly cookies)." },
  { id: "owasp-api-top10", url: "https://owasp.org/API-Security/editions/2023/en/0x11-t10/", title: "OWASP API Security Top 10 (2023)", publisher: "OWASP", sourceType: "standard", verificationStatus: "confirmed_historical", accessed: false, notes: "API1 BOLA, API2 broken auth, API3 property-level auth, API4 unrestricted resource consumption, etc. Mapped in SECURITY.md." },
  { id: "mongodb-multitenant", url: "https://www.mongodb.com/docs/atlas/build-multi-tenant-arch/", title: "Build a Multi-Tenant Architecture", publisher: "MongoDB", sourceType: "docs", verificationStatus: "design_decision", accessed: false, notes: "This deployment target provides PostgreSQL (Drizzle ORM) rather than MongoDB; the same owner-scoped tenant isolation pattern is implemented relationally. Recorded as a design decision." },
  { id: "mongodb-hybrid-search", url: "https://www.mongodb.com/docs/search/tutorial/hybrid-search/", title: "Hybrid Search", publisher: "MongoDB", sourceType: "docs", verificationStatus: "design_decision", accessed: false, notes: "Retrieval implemented with PostgreSQL full-text search over curriculum nodes; vector search is a documented future extension." },
  { id: "better-auth-mongo", url: "https://www.better-auth.com/docs/adapters/mongo", title: "Better Auth Mongo adapter", publisher: "Better Auth", sourceType: "docs", verificationStatus: "design_decision", accessed: false, notes: "Not applicable to the PostgreSQL target; sessions use opaque random tokens (hashed at rest) in httpOnly cookies with scrypt password hashing via Node's crypto module." },
  { id: "marktrack", url: "https://kufah-institute.marktrack.com/blog/marktrack-is-the-simplest-school-software", title: "MarkTrack", publisher: "MarkTrack", sourceType: "docs", verificationStatus: "likely_not_verified", accessed: false, notes: "Visual reference only (navy/blue, cool neutrals). Not fetched." },
  { id: "github-codespaces", url: "https://docs.github.com/en/codespaces/", title: "GitHub Codespaces", publisher: "GitHub", sourceType: "docs", verificationStatus: "likely_not_verified", accessed: false, notes: "Not fetched." },
  { id: "terraform-intro", url: "https://developer.hashicorp.com/terraform/intro", title: "Terraform intro", publisher: "HashiCorp", sourceType: "docs", verificationStatus: "likely_not_verified", accessed: false, notes: "Not fetched." },
  { id: "kubernetes-concepts", url: "https://kubernetes.io/docs/concepts/", title: "Kubernetes Concepts", publisher: "CNCF", sourceType: "docs", verificationStatus: "likely_not_verified", accessed: false, notes: "Not fetched." },
  { id: "ms-ai-103", url: "https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/ai-103", title: "AI-103 study guide", publisher: "Microsoft Learn", sourceType: "docs", verificationStatus: "likely_not_verified", accessed: false, notes: "Not fetched." },
  { id: "ms-azure-ai-engineer", url: "https://learn.microsoft.com/en-us/credentials/certifications/azure-ai-engineer/", title: "Azure AI Engineer Associate", publisher: "Microsoft Learn", sourceType: "docs", verificationStatus: "likely_not_verified", accessed: false, notes: "Not fetched." },
  { id: "wef-future-jobs-2025", url: "https://www.weforum.org/publications/the-future-of-jobs-report-2025/", title: "Future of Jobs Report 2025", publisher: "World Economic Forum", sourceType: "research", verificationStatus: "likely_not_verified", accessed: false, notes: "Not fetched; no statistics from it are shown in the product." },
  { id: "upwork-2026-skills", url: "https://www.upwork.com/press/releases/upworks-in-demand-skills-2026-demand-for-top-ai-skills-more-than-doubles-as-ai-is-embedded-into-everyday-work", title: "Upwork In-Demand Skills 2026", publisher: "Upwork", sourceType: "research", verificationStatus: "likely_not_verified", accessed: false, notes: "Not fetched; no statistics from it are shown in the product." },
  { id: "nuwave-ai-engineer", url: "https://jobs.nuwave.com/apply/JshTpQ8tb8/AI-Engineer", title: "NUWAVE AI Engineer posting", publisher: "NUWAVE", sourceType: "job_posting", verificationStatus: "likely_not_verified", accessed: false, notes: "Requirements encoded from the student-supplied blueprint; the live posting (location, seniority, availability) was not re-verified this session." },
  { id: "nuwave-jobs", url: "https://jobs.nuwave.com/", title: "NUWAVE openings", publisher: "NUWAVE", sourceType: "job_posting", verificationStatus: "likely_not_verified", accessed: false, notes: "Not fetched." },
  { id: "navisoft-ai-engineers", url: "https://app.devfound.ai/jobs/ai-engineers-navisoft/140943", title: "Navisoft AI Engineers posting", publisher: "Navisoft via devfound", sourceType: "job_posting", verificationStatus: "likely_not_verified", accessed: false, notes: "Requirements encoded from the student-supplied blueprint; live posting not re-verified." },
  { id: "indeed-crosscheck", url: "https://www.indeed.com/q-artificial-intelligence-chatbot-l-remote-jobs.html?l=remote&q=artificial+intelligence+chatbot", title: "Indeed cross-check", publisher: "Indeed", sourceType: "job_posting", verificationStatus: "likely_not_verified", accessed: false, notes: "Aggregator; not used as evidence." },
];

/* ------------------------------------------------------------------ */
/* Harvard course registry (status from the tags/requirements pages)   */
/* ------------------------------------------------------------------ */

type HCourse = { code: string; title: string; school: HarvardMapping["school"]; status: HarvardMapping["status"]; sourceId: string; note: string };

export const HARVARD_COURSES: Record<string, HCourse> = {
  CS50: { code: "CS 50", title: "Introduction to Computer Science", school: "Harvard College", status: "confirmed_current", sourceId: "cs50-college-2026-syllabus", note: "Programming 1 tag. Fall 2026 syllabus verified." },
  CS51: { code: "CS 51", title: "Abstraction and Design in Computation", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Programming 2 tag." },
  CS61: { code: "CS 61", title: "Systems Programming and Machine Organization", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Programming 2 + Systems tags." },
  CS20: { code: "CS 20", title: "Discrete Mathematics for Computer Science", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Discrete Math + Formal Reasoning tags." },
  CS1200: { code: "CS 1200", title: "Introduction to Algorithms, Computability, and Complexity", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Formerly CS 120. Computational Limitations + Algorithms tags." },
  CS1210: { code: "CS 1210", title: "Introduction to Theoretical Computer Science", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Formerly CS 121." },
  CS1240: { code: "CS 1240", title: "Data Structures and Algorithms", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Formerly CS 124. Intermediate Algorithms tag." },
  CS1280: { code: "CS 1280 / AM 122", title: "Convex Optimization and Applications in Machine Learning", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Formerly CS 128." },
  CS1090A: { code: "CS 1090A / STAT 109A / AC 209A", title: "Data Science 1: Introduction to Data Science", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Formerly CS 109A." },
  CS1090B: { code: "CS 1090B / STAT 109B / AC 209B", title: "Data Science 2: Advanced Topics in Data Science", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Formerly CS 109B." },
  CS1650: { code: "CS 1650", title: "Data Systems", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Formerly CS 165. Systems tag." },
  CS1810: { code: "CS 1810", title: "Machine Learning", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Formerly CS 181. AI tag." },
  CS1820: { code: "CS 1820", title: "Artificial Intelligence", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Formerly CS 182." },
  CS1840: { code: "CS 1840", title: "Reinforcement Learning", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Formerly CS 184." },
  CS1870: { code: "CS 1870", title: "Introduction to Computational Linguistics and Natural-language Processing", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Formerly CS 187." },
  CS2831: { code: "CS 2831", title: "Computer Vision", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Graduate-level; formerly CS 283." },
  CS2680: { code: "CS 2680", title: "Building AI Systems with AI: Agents and Systems", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Listed on the current tags page." },
  CS2280: { code: "CS 2280", title: "Computational Learning Theory", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Formerly CS 228." },
  CS1050: { code: "CS 1050", title: "Privacy and Technology", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Formerly CS 105." },
  CS1260: { code: "CS 1260", title: "Fairness and Privacy: Perspectives of Law and Probability", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Formerly CS 126." },
  CS1610: { code: "CS 1610", title: "Operating Systems", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Formerly CS 161." },
  CS1430: { code: "CS 1430", title: "Computer Networks", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Formerly CS 143." },
  CS2620: { code: "CS 2620", title: "Introduction to Distributed Computing", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Formerly CS 262." },
  CS2420: { code: "CS 2420", title: "Computing at Scale", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Formerly CS 242." },
  CS2650: { code: "CS 2650", title: "Big Data Systems", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Formerly CS 265." },
  CS1410: { code: "CS 1410 / ECE 141", title: "Computing Hardware", school: "Harvard SEAS", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Formerly CS 141." },
  CS1411: { code: "CS 1411 / ECE 146", title: "Computer Architecture", school: "Harvard SEAS", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Formerly CS 146." },
  ECE50: { code: "ECE 50", title: "Introduction to Electrical Engineering", school: "Harvard SEAS", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Formerly ES 50." },
  ECE143: { code: "ECE 143", title: "Computer Vision", school: "Harvard SEAS", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Formerly ES 143." },
  AC215: { code: "AC 215", title: "Topics in Applied Computation: Advanced Practical Data Science, MLOps", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Listed with corecs/advancedcs tags." },
  AM120: { code: "AM 120", title: "Applied Linear Algebra and Big Data", school: "Harvard SEAS", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "" },
  AM121: { code: "AM 121", title: "Introduction to Optimization: Models and Methods", school: "Harvard SEAS", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "" },
  MATH21A: { code: "MATH 21A", title: "Multivariable Calculus", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "" },
  MATH21B: { code: "MATH 21B", title: "Linear Algebra and Differential Equations", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "Satisfies CS linear-algebra requirement." },
  MATH22A: { code: "MATH 22A", title: "Vector Calculus and Linear Algebra I", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "" },
  MATH1A: { code: "MATH 1A / 1B", title: "Introduction to Calculus", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-requirements", note: "Mathematical preparation." },
  STAT110: { code: "STAT 110", title: "Introduction to Probability", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-requirements", note: "Satisfies CS probability requirement." },
  STAT111: { code: "STAT 111", title: "Introduction to Statistical Inference", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "" },
  STAT195: { code: "STAT 195", title: "Statistical Machine Learning", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "" },
  STAT220: { code: "STAT 220", title: "Bayesian Data Analysis", school: "Harvard College", status: "confirmed_current", sourceId: "harvard-cs-tags", note: "" },
  HES_AI_CERT: { code: "AI Graduate Certificate", title: "Artificial Intelligence Graduate Certificate (4 courses)", school: "Harvard Extension", status: "confirmed_current", sourceId: "hes-ai-certificate", note: "Categories: foundations of AI; advanced NLP & ML; deep learning & CV; AI ethics, governance & law." },
  CSCI_E222: { code: "CSCI E-222", title: "Foundations of Large Language Models", school: "Harvard Extension", status: "likely_not_verified", sourceId: "hes-archive-2025-2026", note: "Identifier from earlier conversation; not verified this session." },
  CSCI_E89: { code: "CSCI E-89", title: "Deep Learning (identifier unverified)", school: "Harvard Extension", status: "likely_not_verified", sourceId: "hes-archive-2025-2026", note: "Not verified this session." },
  CSCI_E25: { code: "CSCI E-25", title: "Computer Vision (identifier unverified)", school: "Harvard Extension", status: "likely_not_verified", sourceId: "hes-archive-2025-2026", note: "Not verified this session." },
  CSCI_E104: { code: "CSCI E-104", title: "Advanced Deep Learning (identifier unverified)", school: "Harvard Extension", status: "likely_not_verified", sourceId: "hes-archive-2025-2026", note: "Not verified this session." },
};

export function map(key: keyof typeof HARVARD_COURSES, exactMatch: boolean, depth: string, harvardAdds: string, weAddBeyond: string): HarvardMapping {
  const c = HARVARD_COURSES[key];
  return { course: c.code, title: c.title, school: c.school, exactMatch, depth, harvardAdds, weAddBeyond, status: c.status, sourceId: c.sourceId };
}

/** Harvard mapping per original section id. */
export const SECTION_MAPPINGS: Record<string, HarvardMapping[]> = {
  "m1-s1-fundamentals": [map("CS50", false, "Introductory; CS50 teaches these ideas first in C (week 1) then Python (week 6).", "C, memory model, compilation; correctness/design/style grading.", "Python-first depth; type casting pitfalls; IHLS prediction drills.")],
  "m1-s2-structures-functions": [map("CS50", false, "Introductory (weeks 5–6: data structures in C, then Python).", "Linked lists, trees, hash tables, tries implemented by hand.", "Pythonic idioms, lambda, scope rules.")],
  "m1-s3-errors-files": [map("CS50", false, "File I/O in C (week 4) and Python (week 6).", "Low-level file handling and buffer-overflow awareness.", "Custom exception hierarchies, CSV/JSON robustness.")],
  "m1-s4-algorithms-oop": [map("CS50", true, "Week 3: linear/binary search, bubble/selection/merge sort, O/Ω/Θ, recursion.", "Asymptotic notation taught formally; merge sort and selection sort.", "OOP (not a CS50 focus); Python implementation."), map("CS51", false, "Abstraction and design (Programming 2).", "Functional and object-oriented abstraction, design principles.", "")],
  "m1-s5-advanced-oop-ecosystem": [map("CS51", false, "Programming 2 depth on abstraction.", "Rigorous abstraction/design with significant software construction.", "Python packaging, venvs, magic methods.")],
  "m2-s1-linear-algebra": [map("MATH21B", false, "Full-semester linear algebra.", "Vector spaces, linear transformations, differential equations.", "Tensor framing for deep learning."), map("AM120", false, "Applied linear algebra for big data.", "SVD, low-rank approximation at scale.", "")],
  "m2-s2-linear-algebra-advanced": [map("MATH21B", false, "Eigen-theory in full.", "Diagonalisation, proofs, applications to ODEs.", "Norms as regularisers; dot product as attention similarity.")],
  "m2-s3-calculus-optimization": [map("MATH1A", false, "Single-variable calculus prerequisite.", "Rigorous differentiation foundations.", ""), map("MATH21A", false, "Multivariable calculus: partial derivatives, gradients.", "Jacobians, multiple integrals, vector fields.", "Gradient descent engineering trade-offs."), map("CS1280", false, "Convex optimisation with ML applications (advanced).", "Convexity, duality, convergence proofs.", "")],
  "m2-s4-statistics": [map("STAT111", false, "Statistical inference.", "Estimators, sufficiency, likelihood theory.", "EDA-oriented interpretation.")],
  "m2-s5-probability": [map("STAT110", true, "Full probability course; satisfies the CS probability requirement.", "Random variables, expectation, LLN/CLT, Markov chains.", "Direct links to ML loss functions.")],
  "m3-s1-numpy-foundations": [map("CS1090A", false, "Data Science 1 uses Python/NumPy/pandas as tools.", "Statistical modelling workflow.", "Memory-layout and shape mental models.")],
  "m3-s2-numpy-performance-inference-pandas": [map("CS1090A", false, "Inference within a data-science workflow.", "Regression inference, bootstrapping.", "Vectorisation/strides performance."), map("STAT111", false, "Hypothesis testing theory.", "Formal test construction and power.", "")],
  "m3-s3-pandas-wrangling": [map("CS1090A", true, "Data wrangling and EDA on messy real data is central to Data Science 1.", "Messy real-world datasets, modelling after EDA.", "Leakage checks in joins and imputation.")],
  "m3-s4-visualization": [map("CS1090A", false, "Visualisation as part of data science.", "Communication of statistical results.", "Plotly dashboards, chart selection drills.")],
  "m3-s5-eda-capstone": [map("CS1090A", false, "Project work.", "Team projects with real data.", "Code-review checklist, portfolio framing.")],
  "m4-s1-excel": [],
  "m4-s2-power-bi": [],
  "m5-s1-sql-design": [map("CS50", true, "Week 7: tables, types, constraints, indexes, transactions, race conditions, SQL injection.", "Transactions and injection taught early.", "ERD and normalisation depth."), map("CS1650", false, "Data Systems (advanced).", "Storage engines, indexing internals, query execution.", "")],
  "m5-s2-advanced-sql": [map("CS1650", false, "Query optimisation internals.", "Cost-based optimisation, concurrency, recovery.", "Window functions and CTE practice.")],
  "m5-s3-scraping-de-intro": [map("CS50", false, "Week 8 covers HTTP, regular expressions, HTML (as web foundations, not scraping).", "Internet fundamentals (TCP/IP, DNS, HTTP).", "Scraping tools, API collection, warehousing (industry).")],
  "m5-s4-etl-capstone": [map("CS2650", false, "Big data systems (graduate).", "Distributed storage/processing systems.", "Practical ETL/ELT tooling.")],
  "m6-s1-fundamentals-preprocessing": [map("CS1810", false, "Machine Learning (AI tag).", "Probabilistic framing, Bayesian methods.", "Pipeline leakage discipline.")],
  "m6-s2-regression": [map("CS1810", true, "Linear regression derived and analysed.", "MLE view, regularisation theory, bias-variance.", "scikit-learn practice layer."), map("CS1090A", true, "Regression in Data Science 1.", "Inference and interpretation.", "")],
  "m6-s3-classification": [map("CS1810", true, "Logistic regression, SVMs, kernels, generative vs discriminative.", "Kernel methods, generative models.", "Metric selection cases.")],
  "m6-s4-ensembles": [map("CS1810", false, "Ensembles appear; boosting theory.", "Theoretical treatment of boosting.", "XGBoost/CatBoost industrial practice.")],
  "m6-s5-unsupervised": [map("CS1810", true, "Clustering, PCA, mixture models, EM.", "EM algorithm, graphical models.", "Recommenders and Apriori (industry).")],
  "m6-s6-ml-capstone": [map("CS1090A", false, "Projects.", "Group project with presentation.", "Model cards.")],
  "m7-s1-nn-foundations": [map("CS1090B", true, "Data Science 2: neural networks and deep learning.", "Advanced topics, Bayesian methods.", ""), map("CS1810", false, "Neural networks within ML.", "Theoretical grounding.", "")],
  "m7-s2-ann-keras": [map("CS1090B", true, "Hands-on deep learning labs.", "", "Keras-specific labs."), map("CSCI_E89", false, "Extension deep learning course (identifier unverified).", "", "")],
  "m7-s3-computer-vision": [map("CS1090B", false, "CNNs in Data Science 2.", "", ""), map("CS2831", false, "Graduate computer vision.", "Geometry, recognition theory.", "YOLO/OpenCV practice."), map("ECE143", false, "SEAS computer vision.", "", ""), map("CSCI_E25", false, "Extension CV (unverified).", "", "")],
  "m7-s4-sequence-models": [map("CS1090B", true, "RNNs/LSTMs in Data Science 2.", "", "Time-series forecasting lab.")],
  "m7-s5-nlp-fundamentals": [map("CS1870", true, "Computational linguistics and NLP.", "Linguistic structure, parsing, statistical NLP.", "")],
  "m7-s6-transformers-llms": [map("CS1870", false, "Neural NLP and language models.", "", "LoRA/QLoRA, RAG, vector DBs, agents (industry)."), map("CS2680", false, "Building AI Systems with AI: Agents and Systems.", "Systems view of agents.", ""), map("CSCI_E222", false, "Foundations of LLMs (Extension; identifier unverified).", "", ""), map("HES_AI_CERT", false, "Extension certificate categories: advanced NLP & ML; deep learning & CV.", "Graduate credit structure.", "")],
  "m8-s1-deployment-capstone": [map("AC215", true, "Advanced Practical Data Science, MLOps.", "Full MLOps stack, cloud deployment, scalable systems.", "FastAPI/Streamlit/Docker as the original toolchain.")],
};

/* ------------------------------------------------------------------ */
/* Additive spine (non-original layers)                                 */
/* ------------------------------------------------------------------ */

export type ExtLesson = {
  id: string;
  title: string;
  stage: string;
  sourceCategory: "harvard_college" | "harvard_extension" | "industry" | "research";
  priority: "core" | "support" | "advanced" | "specialization" | "industry" | "research";
  level: "foundation" | "intermediate" | "advanced" | "graduate" | "research";
  minutes: number;
  why: string;
  objectives: string[];
  topics: string[];
  prerequisites: string[];
  skills: string[];
  mappings: HarvardMapping[];
};

export const STAGES: { id: string; title: string; summary: string; position: number }[] = [
  { id: "stage-math", title: "Mathematical Foundations", summary: "Calculus, linear algebra, optimisation.", position: 1 },
  { id: "stage-programming", title: "Programming Foundations", summary: "Python depth, C/memory, Bash, TypeScript.", position: 2 },
  { id: "stage-cs", title: "Computer Science Foundations", summary: "Data structures, algorithms, theory, systems, networks.", position: 3 },
  { id: "stage-data", title: "Data Foundations", summary: "NumPy, pandas, SQL, modelling.", position: 4 },
  { id: "stage-stats", title: "Statistics and Probability", summary: "Probability, inference, Bayes, MLE.", position: 5 },
  { id: "stage-analysis", title: "Data Analysis", summary: "EDA, visualisation, business analytics.", position: 6 },
  { id: "stage-de", title: "Data Engineering", summary: "ETL/ELT, warehouses, Airflow, dbt, Spark.", position: 7 },
  { id: "stage-ml", title: "Classical Machine Learning", summary: "Regression to ensembles and unsupervised learning.", position: 8 },
  { id: "stage-dl", title: "Deep Learning", summary: "Networks, optimisation, training dynamics.", position: 9 },
  { id: "stage-cv", title: "Computer Vision", summary: "CNNs, transfer learning, detection.", position: 10 },
  { id: "stage-nlp", title: "NLP", summary: "Classical to neural NLP.", position: 11 },
  { id: "stage-llm", title: "Transformers / LLMs", summary: "Attention, pretraining, fine-tuning, evaluation.", position: 12 },
  { id: "stage-rag", title: "RAG / GraphRAG", summary: "Retrieval, vector and hybrid search, graphs.", position: 13 },
  { id: "stage-agents", title: "Agents / Multi-Agent Systems", summary: "Tool use, planning, orchestration, decision framework.", position: 14 },
  { id: "stage-se", title: "Software Engineering for AI", summary: "Git, testing, API design, release engineering.", position: 15 },
  { id: "stage-cloud", title: "Cloud Engineering", summary: "AWS primary, Azure familiarity.", position: 16 },
  { id: "stage-mlops", title: "MLOps / Production ML", summary: "Lifecycle, tracking, deployment, monitoring.", position: 17 },
  { id: "stage-security", title: "Security / Responsible AI / Governance", summary: "OWASP, privacy, fairness, model cards.", position: 18 },
  { id: "stage-english", title: "Technical English", summary: "Reading, writing, speaking, interaction.", position: 19 },
  { id: "stage-career", title: "Career and Interview Engineering", summary: "Evidence-driven readiness.", position: 20 },
  { id: "stage-freelance", title: "Freelancing", summary: "Discovery to delivery.", position: 21 },
  { id: "stage-research", title: "Research Engineering", summary: "Reading, reproduction, ablation, writing.", position: 22 },
];

/** Which stage each original module belongs to. */
export const MODULE_STAGE: Record<string, string> = {
  "m1-python": "stage-programming",
  "m2-math-stats": "stage-math",
  "m3-data-analysis": "stage-analysis",
  "m4-excel-powerbi": "stage-analysis",
  "m5-databases-de": "stage-data",
  "m6-machine-learning": "stage-ml",
  "m7-deep-learning": "stage-dl",
  "m8-mlops": "stage-mlops",
};

export const EXT_LESSONS: ExtLesson[] = [
  // --- CS foundations (Harvard College layer) ---
  { id: "cs-c-memory", title: "C, Memory, Pointers, Stack/Heap, Compilation", stage: "stage-programming", sourceCategory: "harvard_college", priority: "core", level: "foundation", minutes: 240, why: "Python hides memory. CS50 starts in C precisely so that you later understand why a Python list is slow, why NumPy is fast, and what a segmentation fault in a CUDA kernel means.", objectives: ["Explain source → machine code via preprocessing, compiling, assembling, linking", "Draw stack vs heap for a small C program", "Explain pointers, dynamic allocation and buffer overflow", "Use a debugger to find a memory bug"], topics: ["C syntax", "Compiler", "Machine code", "Pointers", "Segmentation faults", "malloc/free", "Stack", "Heap", "Buffer overflow", "Integer overflow", "Floating-point imprecision", "Linux/CLI", "Debugging"], prerequisites: ["m1-s1-fundamentals"], skills: ["c", "systems", "linux"], mappings: [map("CS50", true, "Weeks 1, 2 and 4.", "Hands-on C psets graded on correctness/design/style.", "Framed for ML engineers: why tensors are contiguous memory.")] },
  { id: "cs-data-structures", title: "Data Structures: Linked Lists, Stacks/Queues, Trees, Hash Tables, Tries, Graphs", stage: "stage-cs", sourceCategory: "harvard_college", priority: "core", level: "intermediate", minutes: 300, why: "A vector index, a tokenizer trie, a dependency graph in Airflow and a hash-based feature store are all data structures. Interviews for the target roles test these directly.", objectives: ["Implement linked lists, stacks, queues, BSTs, hash tables and tries", "State operation complexities and justify them", "Choose a structure given access patterns", "Represent and traverse graphs (BFS/DFS)"], topics: ["Abstract data types", "Linked lists", "Stacks", "Queues", "Trees", "Binary search trees", "Hash tables", "Tries", "Graphs", "BFS/DFS"], prerequisites: ["cs-c-memory", "m1-s4-algorithms-oop"], skills: ["algorithms", "data-structures"], mappings: [map("CS50", true, "Week 5.", "Implemented in C.", ""), map("CS1240", false, "Data Structures and Algorithms with proofs.", "Amortised analysis, advanced structures.", "")] },
  { id: "cs-algorithms-complexity", title: "Algorithms: Asymptotics, Sorting, Greedy, Divide & Conquer, Dynamic Programming", stage: "stage-cs", sourceCategory: "harvard_college", priority: "core", level: "intermediate", minutes: 360, why: "Complexity reasoning tells you whether a retrieval pipeline will survive 10× more documents. Dynamic programming reappears as Viterbi, edit distance and beam search.", objectives: ["Analyse running time with O/Ω/Θ and recurrences", "Prove correctness informally for greedy and divide-and-conquer algorithms", "Design dynamic-programming solutions from subproblem structure", "Compare sorting algorithms and choose by constraints"], topics: ["Asymptotic notation", "Recurrences", "Merge sort", "Quick sort", "Selection sort", "Greedy algorithms", "Divide and conquer", "Dynamic programming", "Shortest paths", "Correctness arguments"], prerequisites: ["cs-data-structures", "cs-discrete-math"], skills: ["algorithms"], mappings: [map("CS1200", true, "Algorithms + computability/complexity.", "Formal reasoning and proofs.", ""), map("CS1240", true, "Intermediate algorithms.", "Randomised algorithms, network flow.", "")] },
  { id: "cs-discrete-math", title: "Discrete Mathematics, Logic and Proof Techniques", stage: "stage-cs", sourceCategory: "harvard_college", priority: "core", level: "foundation", minutes: 300, why: "Proof is how you know an algorithm is correct rather than believing it. Sets, functions, counting and graphs are the vocabulary of ML theory and of every algorithms interview.", objectives: ["Write direct, contrapositive, contradiction and induction proofs", "Use sets, relations, functions and counting", "Reason with propositional and predicate logic", "Apply basic graph theory"], topics: ["Propositional logic", "Predicate logic", "Proof techniques", "Induction", "Sets", "Functions", "Relations", "Counting", "Graphs", "Probability basics (discrete)"], prerequisites: ["m1-s1-fundamentals"], skills: ["discrete-math"], mappings: [map("CS20", true, "Discrete Mathematics for Computer Science.", "Full proof-based course.", "")] },
  { id: "cs-computational-limits", title: "Computational Limitations: Computability and Complexity", stage: "stage-cs", sourceCategory: "harvard_college", priority: "support", level: "advanced", minutes: 240, why: "Knowing what cannot be computed efficiently stops you from promising an exact solution to an NP-hard scheduling problem to a client.", objectives: ["Explain finite automata, Turing machines and undecidability", "Explain P, NP and NP-completeness at an intuitive and formal level", "Recognise intractable problems in practice"], topics: ["Automata", "Turing machines", "Undecidability", "Reductions", "P vs NP", "NP-completeness"], prerequisites: ["cs-discrete-math"], skills: ["theory"], mappings: [map("CS1210", true, "Introduction to Theoretical Computer Science.", "Rigorous proofs.", ""), map("CS1200", true, "Computability and complexity component.", "", "")] },
  { id: "cs-systems-os", title: "Computer Organisation, Operating Systems, Processes, Threads, Concurrency", stage: "stage-cs", sourceCategory: "harvard_college", priority: "core", level: "intermediate", minutes: 360, why: "GPU utilisation, data-loader bottlenecks, async API servers and race conditions in feature pipelines are operating-systems problems wearing ML clothing.", objectives: ["Explain CPU, memory hierarchy and caching effects on performance", "Distinguish processes vs threads and explain the GIL's consequences", "Reason about concurrency, locks and race conditions", "Explain virtual memory at a conceptual level"], topics: ["CPU", "Memory hierarchy", "Caching", "Processes", "Threads", "Concurrency", "Locks", "Race conditions", "Virtual memory", "Parallelism", "GPU concepts", "Accelerators"], prerequisites: ["cs-c-memory"], skills: ["systems"], mappings: [map("CS61", true, "Systems Programming and Machine Organization.", "Extensive systems psets.", ""), map("CS1610", false, "Operating Systems.", "Kernel-level implementation.", ""), map("CS1411", false, "Computer Architecture.", "Pipelining, caches, ISA.", "")] },
  { id: "cs-networking", title: "Networking Fundamentals: TCP/IP, DNS, HTTP, REST", stage: "stage-cs", sourceCategory: "harvard_college", priority: "core", level: "foundation", minutes: 180, why: "Every model you serve is reached over HTTP; every latency incident starts with a packet. You cannot debug a 504 from an inference endpoint without this.", objectives: ["Trace a request from URL to response through DNS, TCP and HTTP", "Explain HTTP methods, status codes, headers and cookies", "Design a small REST interface"], topics: ["Routers", "TCP/IP", "DNS", "HTTP", "URLs", "GET/POST", "Status codes", "Sessions", "Cookies", "TLS basics"], prerequisites: ["m1-s3-errors-files"], skills: ["networking", "apis"], mappings: [map("CS50", true, "Week 8 internet fundamentals.", "", "REST design depth."), map("CS1430", false, "Computer Networks.", "Protocol internals.", "")] },
  { id: "cs-distributed", title: "Distributed Systems and Data Systems at Scale", stage: "stage-cs", sourceCategory: "harvard_college", priority: "advanced", level: "advanced", minutes: 300, why: "Training clusters, vector databases and streaming feature pipelines are distributed systems. Partition tolerance and idempotency are not optional once you leave one machine.", objectives: ["Explain replication, partitioning, consistency models and failure modes", "Reason about idempotency, retries and exactly-once illusions", "Explain transactions, isolation levels and recovery", "Describe shared-nothing architectures and stream processing"], topics: ["Replication", "Partitioning", "Consistency", "Consensus (intuition)", "Transactions", "Isolation", "Recovery", "Shared-nothing", "Stream processing", "Key-value stores"], prerequisites: ["cs-systems-os", "m5-s2-advanced-sql", "cs-networking"], skills: ["distributed-systems", "systems"], mappings: [map("CS1650", true, "Data Systems.", "Build a storage engine.", ""), map("CS2620", true, "Introduction to Distributed Computing.", "", ""), map("CS2420", false, "Computing at Scale.", "", "")] },
  { id: "cs-software-design", title: "Abstraction, Software Design and Functional Thinking", stage: "stage-se", sourceCategory: "harvard_college", priority: "support", level: "intermediate", minutes: 240, why: "Pipelines that cannot be reasoned about compositionally cannot be tested. Immutability and pure functions are why reproducible data transformations are possible.", objectives: ["Design interfaces and abstraction barriers", "Apply invariants and assertions", "Use higher-order functions and immutability deliberately", "Refactor toward testable design"], topics: ["Abstraction barriers", "Invariants", "Assertions", "Higher-order functions", "Immutability", "Modularity", "Design principles"], prerequisites: ["m1-s5-advanced-oop-ecosystem"], skills: ["software-engineering"], mappings: [map("CS51", true, "Abstraction and Design in Computation.", "OCaml-based rigorous design.", "")] },
  // --- Math depth ---
  { id: "math-multivariable", title: "Multivariable Calculus: Gradients, Jacobians, Hessians, Matrix Calculus", stage: "stage-math", sourceCategory: "harvard_college", priority: "core", level: "intermediate", minutes: 360, why: "Backpropagation is Jacobian products; second-order methods and learning-rate stability are Hessian eigenvalues; the loss landscape is a multivariable surface.", objectives: ["Compute gradients, Jacobians and Hessians for small functions", "Apply the multivariable chain rule to a two-layer network", "Explain convexity via the Hessian", "Differentiate common matrix expressions"], topics: ["Partial derivatives", "Gradients", "Directional derivatives", "Jacobians", "Hessians", "Multivariable chain rule", "Taylor expansion", "Matrix calculus"], prerequisites: ["m2-s3-calculus-optimization", "m2-s2-linear-algebra-advanced"], skills: ["calculus", "optimization"], mappings: [map("MATH21A", true, "Multivariable Calculus.", "Multiple integrals, vector fields, theorems of vector calculus.", "ML-specific matrix calculus.")] },
  { id: "math-vector-spaces", title: "Vector Spaces, Linear Transformations, SVD", stage: "stage-math", sourceCategory: "harvard_college", priority: "support", level: "intermediate", minutes: 300, why: "Embedding spaces, low-rank adapters (LoRA) and PCA are all statements about subspaces and the SVD.", objectives: ["Explain span, basis, rank and null space", "Interpret a matrix as a linear transformation", "Compute and interpret the SVD and connect it to PCA and low-rank approximation"], topics: ["Vector spaces", "Span", "Basis", "Rank", "Null space", "Linear transformations", "Orthogonality", "Projections", "SVD", "Low-rank approximation"], prerequisites: ["m2-s2-linear-algebra-advanced"], skills: ["linear-algebra"], mappings: [map("MATH21B", true, "Linear Algebra and Differential Equations.", "Differential equations; proofs.", ""), map("AM120", true, "Applied Linear Algebra and Big Data.", "", "")] },
  { id: "math-mle-bayes", title: "Random Variables, Expectation, Likelihood, MLE and MAP", stage: "stage-stats", sourceCategory: "harvard_college", priority: "core", level: "intermediate", minutes: 360, why: "Cross-entropy loss is negative log-likelihood. L2 regularisation is a Gaussian prior. Without MLE/MAP, loss functions are arbitrary recipes.", objectives: ["Define random variables, expectation, variance and common distributions", "Derive MLE for Bernoulli, Gaussian and linear regression", "Explain MAP and connect priors to regularisers", "State LLN and CLT and their role in evaluation"], topics: ["Random variables", "Expectation", "Variance", "Covariance", "Common distributions", "Law of large numbers", "Central limit theorem", "Likelihood", "Maximum likelihood", "MAP", "Conjugate priors (intuition)"], prerequisites: ["m2-s5-probability", "m2-s3-calculus-optimization"], skills: ["probability", "statistics"], mappings: [map("STAT110", true, "Introduction to Probability.", "Full rigorous probability.", "ML loss derivations."), map("STAT111", true, "Statistical inference.", "", ""), map("STAT220", false, "Bayesian Data Analysis.", "Hierarchical models, MCMC.", "")] },
  { id: "math-convex-optimization", title: "Convexity, Optimisation Theory and Numerical Methods", stage: "stage-math", sourceCategory: "harvard_college", priority: "advanced", level: "advanced", minutes: 300, why: "Knowing when a problem is convex tells you whether gradient descent will find the global optimum — and why deep learning's non-convexity makes initialisation and schedules matter.", objectives: ["Recognise convex sets and functions", "Explain Lagrangian duality at an intuitive level and relate it to SVMs", "Compare gradient descent, SGD, momentum and Adam as numerical methods", "Explain conditioning and its effect on convergence"], topics: ["Convex sets", "Convex functions", "Duality", "KKT (intuition)", "Gradient methods", "Momentum", "Adam", "Conditioning", "Numerical stability"], prerequisites: ["math-multivariable"], skills: ["optimization"], mappings: [map("CS1280", true, "Convex Optimization and Applications in Machine Learning.", "Proof-based.", ""), map("AM121", false, "Introduction to Optimization.", "LP/IP modelling.", "")] },
  // --- Software engineering ---
  { id: "se-git-workflow", title: "Git, GitHub, Branching, Pull Requests and Code Review", stage: "stage-se", sourceCategory: "industry", priority: "core", level: "foundation", minutes: 180, why: "GitHub is the source of truth for every project in this program and the primary portfolio artifact recruiters open.", objectives: ["Use branches, commits, rebases and pull requests", "Write a reviewable PR description", "Perform a code review against a checklist", "Apply semantic versioning and dependency pinning"], topics: ["Git", "GitHub", "Branching", "Commits", "Pull requests", "Code review", "Semantic versioning", "Dependency management", "Issue tracking"], prerequisites: ["m1-s5-advanced-oop-ecosystem"], skills: ["git", "software-engineering"], mappings: [] },
  { id: "se-testing-quality", title: "Typing, Linting, Unit/Integration/E2E Testing and Debugging", stage: "stage-se", sourceCategory: "industry", priority: "core", level: "intermediate", minutes: 240, why: "An ML pipeline without tests is a rumour. The target roles list testing explicitly.", objectives: ["Add type hints and run a type checker", "Write unit, integration and end-to-end tests for a data/ML service", "Use logging and configuration correctly", "Debug systematically with hypotheses"], topics: ["Typing", "Linting", "Formatting", "Unit tests", "Integration tests", "E2E tests", "Test doubles", "Logging", "Configuration", "Debugging strategy"], prerequisites: ["se-git-workflow"], skills: ["testing", "software-engineering"], mappings: [] },
  { id: "se-api-design", title: "API Design, REST, Auth, Caching, Retries, Idempotency, Background Jobs", stage: "stage-se", sourceCategory: "industry", priority: "core", level: "intermediate", minutes: 240, why: "The model API you build in Module 8 becomes production only when it handles auth, retries, idempotency and queues correctly.", objectives: ["Design REST resources and error contracts", "Implement authentication vs authorization correctly", "Add caching, retries with backoff and idempotency keys", "Move slow work to background jobs and queues"], topics: ["REST", "API design", "Authentication", "Authorization", "Caching", "Retries", "Idempotency", "Background jobs", "Queues", "Async", "Rate limiting"], prerequisites: ["cs-networking", "m8-s1-deployment-capstone"], skills: ["apis", "software-engineering"], mappings: [] },
  { id: "se-languages", title: "TypeScript, Bash, Java, R and SAS at Target Depth", stage: "stage-programming", sourceCategory: "industry", priority: "industry", level: "intermediate", minutes: 480, why: "The target roles list TypeScript, Bash, Java, R, SAS and VBA. Depth targets: Python deep, SQL deep, TypeScript strong, Bash strong, C foundation, R applied statistics, SAS/Java/VBA familiarity — do not spend core AI time reaching equal depth everywhere.", objectives: ["Write a typed TypeScript module with tests", "Automate a data task in Bash", "Fit and interpret a regression in R", "Read Java and SAS/VBA code and explain what it does"], topics: ["TypeScript", "Bash", "Java", "R", "SAS", "VBA"], prerequisites: ["m1-s5-advanced-oop-ecosystem"], skills: ["typescript", "bash", "java", "r", "sas", "vba"], mappings: [] },
  // --- Data engineering ---
  { id: "de-modern-stack", title: "Warehouses, Lakehouse, Airflow, dbt, Spark, Hadoop Concepts", stage: "stage-de", sourceCategory: "industry", priority: "core", level: "advanced", minutes: 480, why: "Navisoft-style roles list Hadoop, Spark, ETL and Talend; production ML depends on orchestrated, tested transformations.", objectives: ["Model a warehouse (star schema) and explain lake vs lakehouse", "Build and schedule an Airflow DAG with retries and idempotent tasks", "Write dbt models with tests", "Explain Spark execution, partitioning and shuffle; write Spark SQL", "Explain HDFS/MapReduce concepts and where Databricks/Talend fit"], topics: ["Data modeling", "Warehouse concepts", "Lake/lakehouse", "Batch vs streaming", "Airflow", "dbt", "Spark", "Spark SQL", "Partitioning", "Shuffle", "Hadoop", "HDFS", "MapReduce", "Databricks", "Talend"], prerequisites: ["m5-s4-etl-capstone"], skills: ["data-engineering", "spark", "airflow", "dbt", "hadoop"], mappings: [map("CS2650", false, "Big Data Systems.", "Systems internals.", "Tooling practice.")] },
  // --- Cloud ---
  { id: "cloud-aws", title: "AWS: IAM, S3, Lambda, API Gateway, EC2, ECR/ECS, CloudWatch, VPC", stage: "stage-cloud", sourceCategory: "industry", priority: "core", level: "intermediate", minutes: 480, why: "Both target roles require AWS. Serverless model hosting and container deployment are the two patterns you must be able to do without a tutorial.", objectives: ["Explain IAM principals, policies and least privilege", "Deploy a model endpoint with Lambda + API Gateway", "Containerise and run a service on ECS from ECR", "Set up CloudWatch logs/metrics/alarms", "Describe VPC basics and secrets handling"], topics: ["IAM", "S3", "Lambda", "API Gateway", "EC2", "ECR", "ECS", "CloudWatch", "VPC", "Secrets", "Serverless patterns"], prerequisites: ["m8-s1-deployment-capstone", "cs-networking"], skills: ["aws", "cloud"], mappings: [] },
  { id: "cloud-azure", title: "Azure: Entra ID, Storage, Compute, Serverless, Azure AI, Monitoring", stage: "stage-cloud", sourceCategory: "industry", priority: "support", level: "intermediate", minutes: 300, why: "NUWAVE-style roles are Microsoft-ecosystem heavy: Entra ID, Microsoft Graph, Teams apps. Working familiarity is the target, not parity with AWS.", objectives: ["Explain Entra ID identities, app registrations and tokens", "Deploy a function app and storage account", "Describe the Azure AI service landscape and monitoring"], topics: ["Entra ID", "Storage", "Compute", "Serverless", "Azure AI ecosystem", "Monitoring", "Microsoft Graph", "Teams apps"], prerequisites: ["cloud-aws"], skills: ["azure", "cloud"], mappings: [] },
  { id: "cloud-iac", title: "Infrastructure as Code: Terraform/OpenTofu, Containers, Orchestration", stage: "stage-cloud", sourceCategory: "industry", priority: "support", level: "advanced", minutes: 300, why: "Reproducible infrastructure is reproducible ML. Rollback is only possible when infrastructure is code.", objectives: ["Write Terraform for a small deployment", "Explain state, plan/apply and drift", "Explain Kubernetes core concepts"], topics: ["Terraform", "OpenTofu", "State", "Modules", "Docker", "Kubernetes concepts", "Rollback"], prerequisites: ["cloud-aws"], skills: ["terraform", "docker", "cloud"], mappings: [] },
  // --- MLOps ---
  { id: "mlops-lifecycle", title: "MLOps Lifecycle: Validation, Experiment Tracking, Registry, CI/CD, Monitoring, Drift, Rollback", stage: "stage-mlops", sourceCategory: "industry", priority: "core", level: "advanced", minutes: 480, why: "Data → validation → training → tracking → evaluation → packaging → deployment → monitoring → drift → retraining/rollback. This is the job.", objectives: ["Validate data and detect schema drift", "Track experiments with MLflow and register models", "Build CI/CD for a model service", "Monitor quality and latency and define rollback triggers"], topics: ["Data validation", "Experiment tracking", "MLflow", "Model registry", "CI/CD", "Containerization", "Orchestration", "Monitoring", "Drift", "Retraining", "Rollback", "Reproducibility"], prerequisites: ["m8-s1-deployment-capstone", "se-testing-quality"], skills: ["mlops", "ci-cd", "mlflow"], mappings: [map("AC215", true, "Advanced Practical Data Science, MLOps.", "", "")] },
  // --- LLM / RAG / Agents ---
  { id: "llm-foundations", title: "LLM Foundations: Pretraining Objectives, Inference, Context, Generation Controls, Quantization", stage: "stage-llm", sourceCategory: "harvard_extension", priority: "core", level: "advanced", minutes: 420, why: "Prompting is the surface. Latency, cost, context limits, hallucination and quantisation are the engineering reality of the target roles.", objectives: ["Explain next-token pretraining and instruction tuning", "Explain KV cache, sampling parameters and context-window limits", "Compute rough cost/latency for an LLM workload", "Explain quantisation trade-offs"], topics: ["Pretraining objectives", "Instruction tuning", "Inference", "KV cache", "Temperature/top-p", "Context windows", "Quantization", "Hallucination analysis", "Evaluation datasets", "Cost", "Latency"], prerequisites: ["m7-s6-transformers-llms"], skills: ["llm"], mappings: [map("CSCI_E222", false, "Foundations of LLMs (identifier unverified).", "", ""), map("HES_AI_CERT", false, "Advanced NLP & ML category.", "", "")] },
  { id: "rag-engineering", title: "RAG Engineering: Chunking, Embeddings, Vector/Hybrid Search, Reranking, Grounded Citations, Evaluation", stage: "stage-rag", sourceCategory: "industry", priority: "core", level: "advanced", minutes: 420, why: "RAG is the most common production LLM pattern and is explicitly required by the NUWAVE-style role. Most RAG failures are retrieval failures, not model failures.", objectives: ["Design chunking and metadata strategies", "Compare vector, keyword and hybrid search", "Add reranking and citation grounding", "Evaluate retrieval and answer faithfulness separately"], topics: ["Chunking", "Embeddings", "Vector search", "Hybrid search", "Metadata filtering", "Reranking", "Citation grounding", "RAG evaluation", "Prompt injection via documents"], prerequisites: ["llm-foundations", "m5-s2-advanced-sql"], skills: ["rag", "vector-search"], mappings: [] },
  { id: "graphrag", title: "Knowledge Graphs, Graph Databases and GraphRAG", stage: "stage-rag", sourceCategory: "industry", priority: "specialization", level: "advanced", minutes: 300, why: "Multi-hop questions over entities and relations break flat retrieval; GraphRAG is listed by the NUWAVE-style role.", objectives: ["Model entities and relations as a graph", "Query a graph database", "Explain when GraphRAG beats vector RAG and its costs"], topics: ["Knowledge graphs", "Graph databases", "Cypher basics", "Entity extraction", "GraphRAG", "Community summaries"], prerequisites: ["rag-engineering"], skills: ["graphrag", "graph-databases"], mappings: [] },
  { id: "agents-engineering", title: "Agents: Tool Calling, Planning, Memory, Orchestration, Multi-Agent Patterns, Safety, Observability", stage: "stage-agents", sourceCategory: "harvard_college", priority: "core", level: "advanced", minutes: 420, why: "Agents multiply both capability and failure surface. Permissions, observability and cost control are what make them deployable.", objectives: ["Implement tool calling with validated schemas", "Design state and memory explicitly", "Build a LangGraph/LangChain-style workflow with deterministic components", "Add permissions, tracing and cost limits", "Decide deterministic workflow vs single call vs tool workflow vs single agent vs multi-agent"], topics: ["Tool calling", "Planning", "Memory/state", "Orchestration", "LangGraph", "LangChain", "Multi-agent patterns", "Permissions", "Safety", "Observability", "Cost/latency", "Agent decision framework"], prerequisites: ["rag-engineering", "se-api-design"], skills: ["agents", "langgraph"], mappings: [map("CS2680", true, "Building AI Systems with AI: Agents and Systems.", "Systems research perspective.", "Industrial framework practice.")] },
  { id: "ai-advanced-topics", title: "AI Search/Planning, Reinforcement Learning, Learning Theory, Generative Models", stage: "stage-dl", sourceCategory: "harvard_college", priority: "advanced", level: "graduate", minutes: 600, why: "These are the Harvard advanced AI layers: they turn a practitioner into someone who can read and challenge papers.", objectives: ["Explain search and planning formulations", "Explain MDPs, value functions, policy gradients", "State PAC learning and generalisation bounds at an intuitive level", "Compare GANs, VAEs and diffusion models"], topics: ["Search", "Planning", "MDPs", "Q-learning", "Policy gradients", "PAC learning", "Generalization bounds", "GANs", "VAEs", "Diffusion models", "Graphical models", "HMMs"], prerequisites: ["m7-s1-nn-foundations", "math-mle-bayes"], skills: ["reinforcement-learning", "ml-theory", "generative-models"], mappings: [map("CS1820", true, "Artificial Intelligence.", "", ""), map("CS1840", true, "Reinforcement Learning.", "", ""), map("CS2280", true, "Computational Learning Theory.", "", ""), map("CS1090B", false, "Generative models in Data Science 2.", "", "")] },
  { id: "hw-ai-accelerators", title: "Hardware for AI: Digital Logic, Architecture, GPUs, Accelerators, Inference Optimisation", stage: "stage-cs", sourceCategory: "harvard_college", priority: "specialization", level: "advanced", minutes: 300, why: "Serving constraints — memory bandwidth, batch size, quantisation — are hardware facts. Selected ECE depth, not a full EE degree.", objectives: ["Explain digital logic and the hardware/software interface at a conceptual level", "Explain GPU parallelism and memory bandwidth limits", "Apply quantisation and batching to inference", "Describe FPGA/Verilog/verification at awareness level"], topics: ["Digital logic", "Hardware/software interface", "CPU architecture", "Memory hierarchy", "GPU", "AI accelerators", "Parallel computing", "Quantization", "Model serving constraints", "FPGA", "Verilog", "Hardware verification", "Signals and systems (awareness)"], prerequisites: ["cs-systems-os"], skills: ["systems", "hardware"], mappings: [map("ECE50", false, "Introduction to Electrical Engineering.", "", ""), map("CS1410", false, "Computing Hardware.", "", ""), map("CS1411", false, "Computer Architecture.", "", "")] },
  // --- Security / Responsible AI ---
  { id: "security-responsible-ai", title: "Security, Privacy, Fairness, Governance, Model/System Cards, OWASP API & LLM Risks", stage: "stage-security", sourceCategory: "harvard_college", priority: "core", level: "intermediate", minutes: 360, why: "Integrated throughout the program, not a final lecture: bias, leakage, prompt injection, access control and provenance are project requirements.", objectives: ["Audit a dataset for bias, provenance and leakage", "Write a model card and a system card", "Map an API against OWASP API Top 10 and an LLM app against prompt-injection risks", "Explain fairness definitions and their conflicts", "Describe ISO/IEC 42001 and AI regulation at a concept level"], topics: ["Bias", "Fairness", "Privacy", "Security", "Governance", "Accountability", "AI regulation", "Model cards", "Data provenance", "Prompt injection", "Access control", "OWASP API Top 10", "ISO/IEC 42001 concepts", "Human oversight"], prerequisites: ["m6-s3-classification"], skills: ["responsible-ai", "security"], mappings: [map("CS1050", false, "Privacy and Technology.", "", ""), map("CS1260", false, "Fairness and Privacy: Perspectives of Law and Probability.", "", ""), map("HES_AI_CERT", false, "AI ethics, governance & law category.", "", "")] },
  // --- English / Career / Freelance / Research ---
  { id: "english-technical", title: "Technical English: Reading, Writing, Speaking, Interaction, Professional Communication", stage: "stage-english", sourceCategory: "industry", priority: "core", level: "foundation", minutes: 600, why: "Every project here is also the English classroom: bug reports, PR descriptions, architecture explanations, interviews and client summaries.", objectives: ["Read technical documentation and papers efficiently", "Write PR descriptions, READMEs, ADRs and incident reports", "Explain code and architecture aloud", "Handle interviews and client discovery conversations"], topics: ["Technical vocabulary", "Collocations", "Technical reading", "Listening", "Pronunciation awareness", "Shadowing", "Spontaneous speaking", "Technical writing", "Project presentation", "Interview answers", "Client communication"], prerequisites: [], skills: ["english", "communication"], mappings: [] },
  { id: "career-engineering", title: "Career and Interview Engineering: Evidence, CV, Portfolio, System Design and Behavioural Interviews", stage: "stage-career", sourceCategory: "industry", priority: "core", level: "intermediate", minutes: 300, why: "Readiness is a rubric backed by evidence, not a feeling. Every CV bullet must map to a repository, PR, deployment, report or metric.", objectives: ["Map target-role requirements to owned evidence and gaps", "Write evidence-backed CV bullets", "Build portfolio case studies", "Practise coding, system-design and behavioural interviews"], topics: ["Skill taxonomy", "Gap analysis", "CV evidence rule", "Portfolio case studies", "Coding interviews", "System design interviews", "Behavioural interviews", "Negotiation basics"], prerequisites: ["se-git-workflow"], skills: ["career", "communication"], mappings: [] },
  { id: "freelance-engineering", title: "Freelancing: Niche, Discovery, Scope, Estimates, Proposals, Delivery, Maintenance", stage: "stage-freelance", sourceCategory: "industry", priority: "support", level: "intermediate", minutes: 240, why: "Clients say 'I need an AI chatbot'. The engineer's job is to turn that into users, data, integrations, security, volume, latency, evaluation, budget and maintenance.", objectives: ["Run a discovery conversation that surfaces requirements", "Write scope, acceptance criteria and an estimate", "Write a proposal and handle change requests", "Deliver, document and create a case study"], topics: ["Niche selection", "Service selection", "Value proposition", "Client discovery", "Requirements", "Scope", "Acceptance criteria", "Estimates", "Proposals", "Negotiation", "Change requests", "Delivery", "Maintenance", "Case studies"], prerequisites: ["english-technical"], skills: ["freelancing", "communication"], mappings: [] },
  { id: "research-engineering", title: "Research Engineering: Paper Reading, Reproduction, Ablation, Experimental Design, Scientific Writing", stage: "stage-research", sourceCategory: "research", priority: "research", level: "research", minutes: 600, why: "Foundation → reproduction → ablation → extension → research question → experiment → analysis → write-up → review → replication.", objectives: ["Read a paper and extract claims, assumptions and evidence", "Reproduce a published result and document deviations", "Design an ablation with controlled variables", "Write a scientific report and respond to review"], topics: ["Paper reading", "Literature search", "Claim identification", "Experimental design", "Baselines", "Ablation", "Reproduction", "Statistical reasoning", "Reproducibility", "Critique", "Scientific writing", "Presentation"], prerequisites: ["m7-s1-nn-foundations", "math-mle-bayes"], skills: ["research", "communication"], mappings: [] },
];

/** Prerequisite edges among ORIGINAL sections (DAG, not a flat list). */
export const ORIGINAL_PREREQS: Record<string, string[]> = {
  "m1-s2-structures-functions": ["m1-s1-fundamentals"],
  "m1-s3-errors-files": ["m1-s2-structures-functions"],
  "m1-s4-algorithms-oop": ["m1-s2-structures-functions"],
  "m1-s5-advanced-oop-ecosystem": ["m1-s4-algorithms-oop", "m1-s3-errors-files"],
  "m2-s2-linear-algebra-advanced": ["m2-s1-linear-algebra"],
  "m2-s3-calculus-optimization": ["m2-s1-linear-algebra"],
  "m2-s5-probability": ["m2-s4-statistics"],
  "m3-s1-numpy-foundations": ["m1-s2-structures-functions", "m2-s1-linear-algebra"],
  "m3-s2-numpy-performance-inference-pandas": ["m3-s1-numpy-foundations", "m2-s4-statistics", "m2-s5-probability"],
  "m3-s3-pandas-wrangling": ["m3-s2-numpy-performance-inference-pandas", "m1-s3-errors-files"],
  "m3-s4-visualization": ["m3-s3-pandas-wrangling"],
  "m3-s5-eda-capstone": ["m3-s4-visualization"],
  "m4-s1-excel": ["m2-s4-statistics"],
  "m4-s2-power-bi": ["m4-s1-excel", "m5-s1-sql-design"],
  "m5-s1-sql-design": ["m1-s1-fundamentals"],
  "m5-s2-advanced-sql": ["m5-s1-sql-design"],
  "m5-s3-scraping-de-intro": ["m5-s2-advanced-sql", "m1-s3-errors-files"],
  "m5-s4-etl-capstone": ["m5-s3-scraping-de-intro", "m3-s3-pandas-wrangling"],
  "m6-s1-fundamentals-preprocessing": ["m3-s3-pandas-wrangling", "m2-s5-probability"],
  "m6-s2-regression": ["m6-s1-fundamentals-preprocessing", "m2-s3-calculus-optimization"],
  "m6-s3-classification": ["m6-s2-regression"],
  "m6-s4-ensembles": ["m6-s3-classification"],
  "m6-s5-unsupervised": ["m6-s1-fundamentals-preprocessing", "m2-s2-linear-algebra-advanced"],
  "m6-s6-ml-capstone": ["m6-s4-ensembles", "m6-s5-unsupervised", "m3-s5-eda-capstone"],
  "m7-s1-nn-foundations": ["m6-s3-classification", "m2-s3-calculus-optimization"],
  "m7-s2-ann-keras": ["m7-s1-nn-foundations"],
  "m7-s3-computer-vision": ["m7-s2-ann-keras"],
  "m7-s4-sequence-models": ["m7-s2-ann-keras"],
  "m7-s5-nlp-fundamentals": ["m7-s2-ann-keras", "m5-s3-scraping-de-intro"],
  "m7-s6-transformers-llms": ["m7-s5-nlp-fundamentals", "m7-s4-sequence-models", "m2-s2-linear-algebra-advanced"],
  "m8-s1-deployment-capstone": ["m6-s6-ml-capstone", "m7-s6-transformers-llms"],
};
